--Create ext table for cdc
IF OBJECT_ID('stg_jde.ext_f0111_cdc') IS NOT NULL
    DROP EXTERNAL TABLE stg_jde.ext_f0111_cdc


CREATE EXTERNAL TABLE stg_jde.ext_f0111_cdc
(
	[sys_file_name] [NVARCHAR](100) 
	,[sys_file_ln] [VARCHAR](20) 
	,[sys_integration_id] [NVARCHAR](200) 
	,[sys_extract_dt] [NVARCHAR](40) 
	,[sys_cdc_dt] [NVARCHAR](40) 
	,[sys_cdc_scn] [NVARCHAR](14) 
	,[sys_cdc_operation_type] [NVARCHAR](15) 
	,[sys_cdc_before_after] [NVARCHAR](10) 
	,[sys_line_modified_ind] [VARCHAR](20) 
	,[wwan8] [DECIMAL](38, 4) 
	,[wwidln] [DECIMAL](38, 4) 
	,[wwdss5] [DECIMAL](38, 4) 
	,[wwmlnm] [NVARCHAR](40) 
	,[wwattl] [NVARCHAR](40) 
	,[wwrem1] [NVARCHAR](40) 
	,[wwslnm] [NVARCHAR](40) 
	,[wwalph] [NVARCHAR](40) 
	,[wwdc] [NVARCHAR](40) 
	,[wwgnnm] [NVARCHAR](25) 
	,[wwmdnm] [NVARCHAR](25) 
	,[wwsrnm] [NVARCHAR](25) 
	,[wwtyc] [NVARCHAR](1) 
	,[www001] [NVARCHAR](3) 
	,[www002] [NVARCHAR](3) 
	,[www003] [NVARCHAR](3) 
	,[www004] [NVARCHAR](3) 
	,[www005] [NVARCHAR](3) 
	,[www006] [NVARCHAR](3) 
	,[www007] [NVARCHAR](3) 
	,[www008] [NVARCHAR](3) 
	,[www009] [NVARCHAR](3) 
	,[www010] [NVARCHAR](3) 
	,[wwmln1] [NVARCHAR](40) 
	,[wwalp1] [NVARCHAR](40) 
	,[wwuser] [NVARCHAR](10) 
	,[wwpid] [NVARCHAR](10) 
	,[wwupmj] [VARCHAR](20) 
	,[wwjobn] [NVARCHAR](10) 
	,[wwupmt] [DECIMAL](38, 4) 
	,[wwntyp] [NVARCHAR](3) 
	,[wwnick] [NVARCHAR](40) 
	,[wwgend] [NVARCHAR](1) 
	,[wwddate] [DECIMAL](38, 4) 
	,[wwdmon] [DECIMAL](38, 4) 
	,[wwdyr] [DECIMAL](38, 4) 
	,[wwwn001] [NVARCHAR](3) 
	,[wwwn002] [NVARCHAR](3) 
	,[wwwn003] [NVARCHAR](3) 
	,[wwwn004] [NVARCHAR](3) 
	,[wwwn005] [NVARCHAR](3) 
	,[wwwn006] [NVARCHAR](3) 
	,[wwwn007] [NVARCHAR](3) 
	,[wwwn008] [NVARCHAR](3) 
	,[wwwn009] [NVARCHAR](3) 
	,[wwwn010] [NVARCHAR](3) 
	,[wwfuco] [NVARCHAR](10) 
	,[wwpcm] [NVARCHAR](10) 
	,[wwpcf] [NVARCHAR](3) 
	,[wwactin] [NVARCHAR](1) 
	,[wwcfrguid] [NVARCHAR](36) 
	,[wwsyncs] [DECIMAL](38, 4) 
	,[wwcaad] [DECIMAL](38, 4) 
)
WITH
(
    LOCATION='processing-clean/jde/f0111/cdc/'
    ,DATA_SOURCE = [dw-landing-fs]
    ,FILE_FORMAT = [jde_fileformat_124_127_no_header]
)
