--Create ext table for cdc
IF OBJECT_ID('stg_jde.ext_f4101_cdc') IS NOT NULL
    DROP EXTERNAL TABLE stg_jde.ext_f4101_cdc


CREATE EXTERNAL TABLE stg_jde.ext_f4101_cdc
(
	[sys_file_name] [NVARCHAR](100) 
	,[sys_file_ln] [VARCHAR](20) 
	,[sys_integration_id] [NVARCHAR](200) 
	,[sys_extract_dt] [NVARCHAR](40) 
	,[sys_cdc_dt] [NVARCHAR](40) 
	,[sys_cdc_scn] [NVARCHAR](14) 
	,[sys_cdc_operation_type] [NVARCHAR](15) 
	,[sys_cdc_before_after] [NVARCHAR](10) 
	,[sys_line_modified_ind] [VARCHAR](20) 
	,[imitm] [DECIMAL](38, 4) 
	,[imlitm] [NVARCHAR](25) 
	,[imaitm] [NVARCHAR](25) 
	,[imdsc1] [NVARCHAR](30) 
	,[imdsc2] [NVARCHAR](30) 
	,[imsrtx] [NVARCHAR](30) 
	,[imaln] [NVARCHAR](30) 
	,[imsrp1] [NVARCHAR](3) 
	,[imsrp2] [NVARCHAR](3) 
	,[imsrp3] [NVARCHAR](3) 
	,[imsrp4] [NVARCHAR](3) 
	,[imsrp5] [NVARCHAR](3) 
	,[imsrp6] [NVARCHAR](6) 
	,[imsrp7] [NVARCHAR](6) 
	,[imsrp8] [NVARCHAR](6) 
	,[imsrp9] [NVARCHAR](6) 
	,[imsrp0] [NVARCHAR](6) 
	,[imprp1] [NVARCHAR](3) 
	,[imprp2] [NVARCHAR](3) 
	,[imprp3] [NVARCHAR](3) 
	,[imprp4] [NVARCHAR](3) 
	,[imprp5] [NVARCHAR](3) 
	,[imprp6] [NVARCHAR](6) 
	,[imprp7] [NVARCHAR](6) 
	,[imprp8] [NVARCHAR](6) 
	,[imprp9] [NVARCHAR](6) 
	,[imprp0] [NVARCHAR](6) 
	,[imcdcd] [NVARCHAR](15) 
	,[impdgr] [NVARCHAR](3) 
	,[imdsgp] [NVARCHAR](3) 
	,[imprgr] [NVARCHAR](8) 
	,[imrprc] [NVARCHAR](8) 
	,[imorpr] [NVARCHAR](8) 
	,[imbuyr] [DECIMAL](38, 4) 
	,[imdraw] [NVARCHAR](20) 
	,[imrvno] [NVARCHAR](2) 
	,[imdsze] [NVARCHAR](1) 
	,[imvcud] [DECIMAL](38, 4) 
	,[imcars] [DECIMAL](38, 4) 
	,[imcarp] [DECIMAL](38, 4) 
	,[imshcn] [NVARCHAR](3) 
	,[imshcm] [NVARCHAR](3) 
	,[imuom1] [NVARCHAR](2) 
	,[imuom2] [NVARCHAR](2) 
	,[imuom3] [NVARCHAR](2) 
	,[imuom4] [NVARCHAR](2) 
	,[imuom6] [NVARCHAR](2) 
	,[imuom8] [NVARCHAR](2) 
	,[imuom9] [NVARCHAR](2) 
	,[imuwum] [NVARCHAR](2) 
	,[imuvm1] [NVARCHAR](2) 
	,[imsutm] [NVARCHAR](2) 
	,[imumvw] [NVARCHAR](1) 
	,[imcycl] [NVARCHAR](3) 
	,[imglpt] [NVARCHAR](4) 
	,[implev] [NVARCHAR](1) 
	,[impplv] [NVARCHAR](1) 
	,[imclev] [NVARCHAR](1) 
	,[imprpo] [NVARCHAR](1) 
	,[imckav] [NVARCHAR](1) 
	,[imbpfg] [NVARCHAR](1) 
	,[imsrce] [NVARCHAR](1) 
	,[imot1y] [NVARCHAR](1) 
	,[imot2y] [NVARCHAR](1) 
	,[imstdp] [DECIMAL](38, 4) 
	,[imfrmp] [DECIMAL](38, 4) 
	,[imthrp] [DECIMAL](38, 4) 
	,[imstdg] [NVARCHAR](3) 
	,[imfrgd] [NVARCHAR](3) 
	,[imthgd] [NVARCHAR](3) 
	,[imcoty] [NVARCHAR](1) 
	,[imstkt] [NVARCHAR](1) 
	,[imlnty] [NVARCHAR](2) 
	,[imcont] [NVARCHAR](1) 
	,[imback] [NVARCHAR](1) 
	,[imifla] [NVARCHAR](2) 
	,[imtfla] [NVARCHAR](2) 
	,[iminmg] [NVARCHAR](10) 
	,[imabcs] [NVARCHAR](1) 
	,[imabcm] [NVARCHAR](1) 
	,[imabci] [NVARCHAR](1) 
	,[imovr] [NVARCHAR](1) 
	,[imwarr] [NVARCHAR](8) 
	,[imcmcg] [NVARCHAR](8) 
	,[imsrnr] [NVARCHAR](1) 
	,[impmth] [NVARCHAR](1) 
	,[imfifo] [NVARCHAR](1) 
	,[imlots] [NVARCHAR](1) 
	,[imsld] [DECIMAL](38, 4) 
	,[imanpl] [DECIMAL](38, 4) 
	,[immpst] [NVARCHAR](1) 
	,[impctm] [DECIMAL](38, 4) 
	,[immmpc] [DECIMAL](38, 4) 
	,[imptsc] [NVARCHAR](2) 
	,[imsns] [NVARCHAR](1) 
	,[imltlv] [DECIMAL](38, 4) 
	,[imltmf] [DECIMAL](38, 4) 
	,[imltcm] [DECIMAL](38, 4) 
	,[imopc] [NVARCHAR](1) 
	,[imopv] [DECIMAL](38, 4) 
	,[imacq] [DECIMAL](38, 4) 
	,[immlq] [DECIMAL](38, 4) 
	,[imltpu] [DECIMAL](38, 4) 
	,[immpsp] [NVARCHAR](1) 
	,[immrpp] [NVARCHAR](1) 
	,[imitc] [NVARCHAR](1) 
	,[imordw] [NVARCHAR](1) 
	,[immtf1] [DECIMAL](38, 4) 
	,[immtf2] [DECIMAL](38, 4) 
	,[immtf3] [DECIMAL](38, 4) 
	,[immtf4] [DECIMAL](38, 4) 
	,[immtf5] [DECIMAL](38, 4) 
	,[imexpd] [DECIMAL](38, 4) 
	,[imdefd] [DECIMAL](38, 4) 
	,[imsflt] [DECIMAL](38, 4) 
	,[immake] [NVARCHAR](1) 
	,[imcoby] [NVARCHAR](1) 
	,[imllx] [DECIMAL](38, 4) 
	,[imcmgl] [NVARCHAR](1) 
	,[imcomh] [DECIMAL](38, 4) 
	,[imurcd] [NVARCHAR](2) 
	,[imurdt] [VARCHAR](20) 
	,[imurat] [DECIMAL](38, 4) 
	,[imurab] [DECIMAL](38, 4) 
	,[imurrf] [NVARCHAR](15) 
	,[imuser] [NVARCHAR](10) 
	,[impid] [NVARCHAR](10) 
	,[imjobn] [NVARCHAR](10) 
	,[imupmj] [VARCHAR](20) 
	,[imtday] [DECIMAL](38, 4) 
	,[imupcn] [NVARCHAR](13) 
	,[imscc0] [NVARCHAR](14) 
	,[imumup] [NVARCHAR](2) 
	,[imumdf] [NVARCHAR](2) 
	,[imums0] [NVARCHAR](2) 
	,[imums1] [NVARCHAR](2) 
	,[imums2] [NVARCHAR](2) 
	,[imums3] [NVARCHAR](2) 
	,[imums4] [NVARCHAR](2) 
	,[imums5] [NVARCHAR](2) 
	,[imums6] [NVARCHAR](2) 
	,[imums7] [NVARCHAR](2) 
	,[imums8] [NVARCHAR](2) 
	,[impoc] [NVARCHAR](1) 
	,[imavrt] [DECIMAL](38, 4) 
	,[imeqty] [NVARCHAR](5) 
	,[imwtrq] [NVARCHAR](1) 
	,[imtmpl] [NVARCHAR](20) 
	,[imseg1] [NVARCHAR](10) 
	,[imseg2] [NVARCHAR](10) 
	,[imseg3] [NVARCHAR](10) 
	,[imseg4] [NVARCHAR](10) 
	,[imseg5] [NVARCHAR](10) 
	,[imseg6] [NVARCHAR](10) 
	,[imseg7] [NVARCHAR](10) 
	,[imseg8] [NVARCHAR](10) 
	,[imseg9] [NVARCHAR](10) 
	,[imseg0] [NVARCHAR](10) 
	,[immic] [NVARCHAR](1) 
	,[imaing] [NVARCHAR](1) 
	,[imbbdd] [DECIMAL](38, 4) 
	,[imcmdm] [NVARCHAR](1) 
	,[imlecm] [NVARCHAR](1) 
	,[imledd] [DECIMAL](38, 4) 
	,[impefd] [DECIMAL](38, 4) 
	,[imsbdd] [DECIMAL](38, 4) 
	,[imu1dd] [DECIMAL](38, 4) 
	,[imu2dd] [DECIMAL](38, 4) 
	,[imu3dd] [DECIMAL](38, 4) 
	,[imu4dd] [DECIMAL](38, 4) 
	,[imu5dd] [DECIMAL](38, 4) 
	,[imdltl] [DECIMAL](38, 4) 
	,[imdppo] [NVARCHAR](1) 
	,[imdual] [NVARCHAR](1) 
	,[imxdck] [NVARCHAR](1) 
	,[imlaf] [NVARCHAR](1) 
	,[imltfm] [NVARCHAR](1) 
	,[imrwla] [NVARCHAR](1) 
	,[imlnpa] [NVARCHAR](1) 
	,[imlotc] [NVARCHAR](3) 
	,[imapsc] [NVARCHAR](1) 
	,[imauom] [NVARCHAR](9) 
	,[imconb] [NVARCHAR](1) 
	,[imgcmp] [NVARCHAR](1) 
	,[impri1] [DECIMAL](38, 4) 
	,[impri2] [DECIMAL](38, 4) 
	,[imashl] [NVARCHAR](1) 
	,[imvminv] [NVARCHAR](1) 
	,[imcmeth] [NVARCHAR](1) 
	,[imexpi] [NVARCHAR](1) 
	,[imopth] [DECIMAL](38, 4) 
	,[imcuth] [DECIMAL](38, 4) 
	,[imumth] [NVARCHAR](3) 
	,[imlmfg] [NVARCHAR](1) 
	,[imline] [NVARCHAR](12) 
	,[imdftpct] [DECIMAL](38, 4) 
	,[imkbit] [NVARCHAR](1) 
	,[imdfenditm] [NVARCHAR](1) 
	,[imkanexll] [NVARCHAR](1) 
	,[imscpsell] [NVARCHAR](1) 
	,[immopth] [DECIMAL](38, 4) 
	,[immcuth] [DECIMAL](38, 4) 
	,[imcumth] [NVARCHAR](3) 
	,[imatprn] [NVARCHAR](80) 
	,[imatpca] [NVARCHAR](1) 
	,[imatpac] [NVARCHAR](5) 
	,[imcoore] [NVARCHAR](1) 
	,[imvcpfc] [NVARCHAR](20) 
	,[impnyn] [NVARCHAR](1) 
)
WITH
(
    LOCATION='processing-clean/jde/f4101/cdc/'
    ,DATA_SOURCE = [dw-landing-fs]
    ,FILE_FORMAT = [jde_fileformat_124_127_no_header]
)
