# init blobstore folder structure
# assumes BlobFuse is mapped to /u01/data/dw-landing-fs
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f0005/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f0006/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f0010/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f0012/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f0014/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f0015/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f0092/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f0101/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f0111/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f0115/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f01151/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f0116/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f0150/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f03012/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f03b11/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f03b14/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f0401/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f0411/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f0413/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f060116/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f0902/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f1113/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f1201/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f1202/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f1207/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f1217/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f1620/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f3002/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f30026/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f3111/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f3112/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f3411/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f3412/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f3460/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f38010/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f38011/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f38012/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f38111/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f38112/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4006/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4008/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f40205/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f40540/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4070/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4071/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4072/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4074/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4075/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4076/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4092/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f40943/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4096/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f41002/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f41003/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4101/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f41011/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4102/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f41022/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4104/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4105/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f41061/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4111/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f41112/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f41291/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f41500/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f41511/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f41514/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4201/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f42019/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4209/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4211/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f42119/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4215/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f42199/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4229/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4301/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4311/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4321/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f46011/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4801/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4801t/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4906/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f49211/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f49219/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4930/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4931/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4941/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4942/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4945/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f49501/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4960/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4961/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f4981/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f550312/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f5509176/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f553402/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f554103/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f554217/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f554237/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f554347/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f554501/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f554503/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f554506/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f554900/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f554901/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f554904/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f554905/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f554915/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f554922/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f556103/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f556202/{cdc,init,skipped}
mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/f9210/{cdc,init,skipped}

mkdir -p /u01/data/dw-landing-fs/processing-clean/jde_qat/statistics
mkdir -p /u01/data/dw-landing-fs/incoming-raw/jde_qat/statistics

# init blobstore folder structure
# assumes BlobFuse is mapped to /u01/data/dw-permstore-fs
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f0005/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f0006/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f0010/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f0012/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f0014/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f0015/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f0092/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f0101/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f0111/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f0115/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f01151/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f0116/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f0150/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f03012/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f03b11/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f03b14/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f0401/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f0411/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f0413/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f060116/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f0902/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f1113/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f1201/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f1202/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f1207/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f1217/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f1620/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f3002/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f30026/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f3111/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f3112/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f3411/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f3412/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f3460/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f38010/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f38011/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f38012/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f38111/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f38112/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4006/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4008/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f40205/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f40540/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4070/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4071/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4072/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4074/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4075/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4076/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4092/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f40943/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4096/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f41002/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f41003/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4101/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f41011/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4102/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f41022/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4104/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4105/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f41061/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4111/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f41112/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f41291/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f41500/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f41511/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f41514/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4201/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f42019/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4209/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4211/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f42119/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4215/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f42199/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4229/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4301/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4311/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4321/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f46011/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4801/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4801t/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4906/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f49211/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f49219/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4930/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4931/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4941/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4942/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4945/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f49501/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4960/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4961/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f4981/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f50312/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f5509176/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f553402/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f554103/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f554217/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f554237/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f554347/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f554501/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f554503/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f554506/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f554900/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f554901/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f554904/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f554905/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f554915/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f554922/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f556103/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f556202/{cdc,init,skipped}
mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/f9210/{cdc,init,skipped}

mkdir -p /u01/data/dw-permstore-fs/archive-clean/jde_qat/statistics
