--Create ext table for init
IF OBJECT_ID('stg_jde_qat.ext_f0092_init') IS NOT NULL
    DROP EXTERNAL TABLE stg_jde_qat.ext_f0092_init

CREATE EXTERNAL TABLE stg_jde_qat.ext_f0092_init
(
	[sys_file_name] [NVARCHAR](100) 
	,[sys_file_ln] [VARCHAR](20) 
	,[sys_integration_id] [NVARCHAR](200) 
	,[sys_extract_dt] [NVARCHAR](40) 
	,[sys_cdc_dt] [NVARCHAR](40) 
	,[sys_cdc_scn] [NVARCHAR](14) 
	,[sys_cdc_operation_type] [NVARCHAR](15) 
	,[sys_cdc_before_after] [NVARCHAR](10) 
	,[sys_line_modified_ind] [VARCHAR](20) 
	,[uluser] [NVARCHAR](10) 
	,[ulmni] [NVARCHAR](10) 
	,[uloutq] [NVARCHAR](10) 
	,[uljobq] [NVARCHAR](10) 
	,[uljsp] [NVARCHAR](1) 
	,[uloutp] [NVARCHAR](1) 
	,[ulllvl] [NVARCHAR](1) 
	,[ullsev] [NVARCHAR](2) 
	,[ullmsg] [NVARCHAR](7) 
	,[ulprtl] [NVARCHAR](10) 
	,[ulul01] [NVARCHAR](10) 
	,[ulul02] [NVARCHAR](10) 
	,[ulul03] [NVARCHAR](10) 
	,[ulul04] [NVARCHAR](10) 
	,[ulul05] [NVARCHAR](10) 
	,[ulul06] [NVARCHAR](10) 
	,[ulul07] [NVARCHAR](10) 
	,[ulul08] [NVARCHAR](10) 
	,[ulul09] [NVARCHAR](10) 
	,[ulul10] [NVARCHAR](10) 
	,[ulul11] [NVARCHAR](10) 
	,[ulul12] [NVARCHAR](10) 
	,[ulul13] [NVARCHAR](10) 
	,[ulul14] [NVARCHAR](10) 
	,[ulul15] [NVARCHAR](10) 
	,[ulul16] [NVARCHAR](10) 
	,[ulul17] [NVARCHAR](10) 
	,[ulul18] [NVARCHAR](10) 
	,[ulul19] [NVARCHAR](10) 
	,[ulul20] [NVARCHAR](10) 
	,[ulul21] [NVARCHAR](10) 
	,[ulul22] [NVARCHAR](10) 
	,[ulul23] [NVARCHAR](10) 
	,[ulul24] [NVARCHAR](10) 
	,[ulul25] [NVARCHAR](10) 
	,[ulmska] [NVARCHAR](1) 
	,[ulmskj] [NVARCHAR](1) 
	,[ulmskk] [NVARCHAR](1) 
	,[ulmskd] [NVARCHAR](2) 
	,[ulmskf] [NVARCHAR](1) 
	,[ulan8] [DECIMAL](38, 4) 
	,[ulutyp] [NVARCHAR](10) 
	,[ulpid] [NVARCHAR](10) 
	,[ulmtvl] [NVARCHAR](1) 
	,[ulcmde] [NVARCHAR](1) 
	,[ulclib] [NVARCHAR](10) 
	,[ulugrp] [NVARCHAR](10) 
	,[ulipgm] [NVARCHAR](10) 
	,[ullod] [NVARCHAR](1) 
	,[ulfstp] [NVARCHAR](1) 
)
WITH
(
    LOCATION='processing-clean/jde_qat/f0092/init/'
    ,DATA_SOURCE = [dw-landing-fs]
    ,FILE_FORMAT = [jde_fileformat_124_127_no_header]
)
