--Create ext table for init
IF OBJECT_ID('stg_jde_qat.ext_f1207_init') IS NOT NULL
    DROP EXTERNAL TABLE stg_jde_qat.ext_f1207_init

CREATE EXTERNAL TABLE stg_jde_qat.ext_f1207_init
(
	[sys_file_name] [NVARCHAR](100) 
	,[sys_file_ln] [VARCHAR](20) 
	,[sys_integration_id] [NVARCHAR](200) 
	,[sys_extract_dt] [NVARCHAR](40) 
	,[sys_cdc_dt] [NVARCHAR](40) 
	,[sys_cdc_scn] [NVARCHAR](14) 
	,[sys_cdc_operation_type] [NVARCHAR](15) 
	,[sys_cdc_before_after] [NVARCHAR](10) 
	,[sys_line_modified_ind] [VARCHAR](20) 
	,[fwnumb] [DECIMAL](38, 4) 
	,[fwapid] [NVARCHAR](12) 
	,[fwasid] [NVARCHAR](25) 
	,[fwsrvt] [NVARCHAR](8) 
	,[fwmsts] [NVARCHAR](2) 
	,[fwmpri] [NVARCHAR](1) 
	,[fwky] [NVARCHAR](10) 
	,[fwanp] [DECIMAL](38, 4) 
	,[fwrmk] [NVARCHAR](30) 
	,[fwsrvd] [DECIMAL](38, 4) 
	,[fwsrvm] [DECIMAL](38, 4) 
	,[fwsrvh] [DECIMAL](38, 4) 
	,[fwtdt] [VARCHAR](20) 
	,[fwcplm] [DECIMAL](38, 4) 
	,[fwcplh] [DECIMAL](38, 4) 
	,[fwcpld] [VARCHAR](20) 
	,[fwlstm] [DECIMAL](38, 4) 
	,[fwlsth] [DECIMAL](38, 4) 
	,[fwlcpd] [VARCHAR](20) 
	,[fwuser] [NVARCHAR](10) 
	,[fwpid] [NVARCHAR](10) 
	,[fwupmj] [VARCHAR](20) 
	,[fwjobn] [NVARCHAR](10) 
	,[fwdoco] [DECIMAL](38, 4) 
	,[fwwona] [DECIMAL](38, 4) 
	,[fwmpc] [DECIMAL](38, 4) 
	,[fwsrvf] [DECIMAL](38, 4) 
	,[fwcplf] [DECIMAL](38, 4) 
	,[fwlstf] [DECIMAL](38, 4) 
	,[fwmltw] [NVARCHAR](1) 
	,[fworgm] [DECIMAL](38, 4) 
	,[fworgh] [DECIMAL](38, 4) 
	,[fworgf] [DECIMAL](38, 4) 
	,[fwoccu] [DECIMAL](38, 4) 
	,[fwfrin] [NVARCHAR](1) 
	,[fwupmt] [DECIMAL](38, 4) 
	,[fwmcu] [NVARCHAR](12) 
	,[fwaaid] [DECIMAL](38, 4) 
	,[fwcrtl] [DECIMAL](38, 4) 
	,[fwpnst] [VARCHAR](20) 
	,[fwpmc1] [NVARCHAR](3) 
	,[fwpmc2] [NVARCHAR](3) 
	,[fwdnhr] [DECIMAL](38, 4) 
	,[fwpdfl] [NVARCHAR](1) 
	,[fwukid] [DECIMAL](38, 4) 
	,[fwtolu] [DECIMAL](38, 4) 
	,[fwtoll] [DECIMAL](38, 4) 
	,[fwhldd] [VARCHAR](20) 
	,[fwsphr] [DECIMAL](38, 4) 
	,[fwspwk] [DECIMAL](38, 4) 
	,[fwspmn] [DECIMAL](38, 4) 
	,[fwwk] [DECIMAL](38, 4) 
	,[fwspdw] [NVARCHAR](1) 
	,[fwpdfg] [NVARCHAR](1) 
	,[fwsrvm4] [DECIMAL](38, 4) 
	,[fwlstm4] [DECIMAL](38, 4) 
	,[fwcplm4] [DECIMAL](38, 4) 
	,[fworgm4] [DECIMAL](38, 4) 
	,[fwsrvm5] [DECIMAL](38, 4) 
	,[fwlstm5] [DECIMAL](38, 4) 
	,[fwcplm5] [DECIMAL](38, 4) 
	,[fworgm5] [DECIMAL](38, 4) 
	,[fwsrvm6] [DECIMAL](38, 4) 
	,[fwlstm6] [DECIMAL](38, 4) 
	,[fwcplm6] [DECIMAL](38, 4) 
	,[fworgm6] [DECIMAL](38, 4) 
)
WITH
(
    LOCATION='processing-clean/jde_qat/f1207/init/'
    ,DATA_SOURCE = [dw-landing-fs]
    ,FILE_FORMAT = [jde_fileformat_124_127_no_header]
)
