--Create ext table for init
IF OBJECT_ID('stg_jde_qat.ext_f3111_init') IS NOT NULL
    DROP EXTERNAL TABLE stg_jde_qat.ext_f3111_init

CREATE EXTERNAL TABLE stg_jde_qat.ext_f3111_init
(
	[sys_file_name] [NVARCHAR](100) 
	,[sys_file_ln] [VARCHAR](20) 
	,[sys_integration_id] [NVARCHAR](200) 
	,[sys_extract_dt] [NVARCHAR](40) 
	,[sys_cdc_dt] [NVARCHAR](40) 
	,[sys_cdc_scn] [NVARCHAR](14) 
	,[sys_cdc_operation_type] [NVARCHAR](15) 
	,[sys_cdc_before_after] [NVARCHAR](10) 
	,[sys_line_modified_ind] [VARCHAR](20) 
	,[wmdoco] [DECIMAL](38, 4) 
	,[wmdcto] [NVARCHAR](2) 
	,[wmsfxo] [NVARCHAR](3) 
	,[wmtbm] [NVARCHAR](3) 
	,[wmforq] [NVARCHAR](1) 
	,[wmitc] [NVARCHAR](1) 
	,[wmcoby] [NVARCHAR](1) 
	,[wmcoty] [NVARCHAR](1) 
	,[wmcpnt] [DECIMAL](38, 4) 
	,[wmfrmp] [DECIMAL](38, 4) 
	,[wmthrp] [DECIMAL](38, 4) 
	,[wmfrgd] [NVARCHAR](3) 
	,[wmthgd] [NVARCHAR](3) 
	,[wmrkco] [NVARCHAR](5) 
	,[wmrorn] [NVARCHAR](8) 
	,[wmrcto] [NVARCHAR](2) 
	,[wmrlln] [DECIMAL](38, 4) 
	,[wmopsq] [DECIMAL](38, 4) 
	,[wmbseq] [DECIMAL](38, 4) 
	,[wmrscp] [DECIMAL](38, 4) 
	,[wmscrp] [DECIMAL](38, 4) 
	,[wmrewp] [DECIMAL](38, 4) 
	,[wmasip] [DECIMAL](38, 4) 
	,[wmcpyp] [DECIMAL](38, 4) 
	,[wmstpp] [DECIMAL](38, 4) 
	,[wmlovd] [DECIMAL](38, 4) 
	,[wmcpit] [DECIMAL](38, 4) 
	,[wmcpil] [NVARCHAR](25) 
	,[wmcpia] [NVARCHAR](25) 
	,[wmcmcu] [NVARCHAR](12) 
	,[wmdsc1] [NVARCHAR](30) 
	,[wmdsc2] [NVARCHAR](30) 
	,[wmlocn] [NVARCHAR](20) 
	,[wmlotn] [NVARCHAR](30) 
	,[wman8] [DECIMAL](38, 4) 
	,[wmlnty] [NVARCHAR](2) 
	,[wmsern] [NVARCHAR](30) 
	,[wmtrdj] [VARCHAR](20) 
	,[wmdrqj] [VARCHAR](20) 
	,[wmuorg] [DECIMAL](38, 4) 
	,[wmtrqt] [DECIMAL](38, 4) 
	,[wmsocn] [DECIMAL](38, 4) 
	,[wmsobk] [DECIMAL](38, 4) 
	,[wmcts1] [DECIMAL](38, 4) 
	,[wmqnta] [DECIMAL](38, 4) 
	,[wmum] [NVARCHAR](2) 
	,[wmea] [DECIMAL](38, 4) 
	,[wmrtg] [NVARCHAR](1) 
	,[wmmtst] [NVARCHAR](2) 
	,[wmdct] [NVARCHAR](2) 
	,[wmshno] [NVARCHAR](10) 
	,[wmmcu] [NVARCHAR](12) 
	,[wmomcu] [NVARCHAR](12) 
	,[wmobj] [NVARCHAR](6) 
	,[wmsub] [NVARCHAR](8) 
	,[wmcmrv] [NVARCHAR](3) 
	,[wmstrx] [VARCHAR](20) 
	,[wmpars] [NVARCHAR](8) 
	,[wmcomm] [NVARCHAR](1) 
	,[wmurcd] [NVARCHAR](2) 
	,[wmurdt] [VARCHAR](20) 
	,[wmurat] [DECIMAL](38, 4) 
	,[wmurrf] [NVARCHAR](15) 
	,[wmurab] [DECIMAL](38, 4) 
	,[wmuser] [NVARCHAR](10) 
	,[wmpid] [NVARCHAR](10) 
	,[wmjobn] [NVARCHAR](10) 
	,[wmupmj] [VARCHAR](20) 
	,[wmtday] [DECIMAL](38, 4) 
	,[wmukid] [DECIMAL](38, 4) 
	,[wmvend] [DECIMAL](38, 4) 
	,[wmpoc] [NVARCHAR](1) 
	,[wmcts4] [DECIMAL](38, 4) 
	,[wmcts7] [DECIMAL](38, 4) 
	,[wmcts8] [DECIMAL](38, 4) 
	,[wmgld] [VARCHAR](20) 
	,[wmsbfl] [NVARCHAR](1) 
	,[wmaing] [NVARCHAR](1) 
	,[wmsstq] [DECIMAL](38, 4) 
	,[wmuom2] [NVARCHAR](2) 
	,[wmapsc] [NVARCHAR](1) 
	,[wmpsn] [DECIMAL](38, 4) 
	,[wmdlej] [VARCHAR](20) 
	,[wmcost] [NVARCHAR](3) 
	,[wmchpp] [NVARCHAR](1) 
	,[wmcpnb] [DECIMAL](38, 4) 
	,[wmbseqan] [NVARCHAR](5) 
)
WITH
(
    LOCATION='processing-clean/jde_qat/f3111/init/'
    ,DATA_SOURCE = [dw-landing-fs]
    ,FILE_FORMAT = [jde_fileformat_124_127_no_header]
)
