--Create ext table for init
IF OBJECT_ID('stg_jde_qat.ext_f38010_init') IS NOT NULL
    DROP EXTERNAL TABLE stg_jde_qat.ext_f38010_init

CREATE EXTERNAL TABLE stg_jde_qat.ext_f38010_init
(
	[sys_file_name] [NVARCHAR](100) 
	,[sys_file_ln] [VARCHAR](20) 
	,[sys_integration_id] [NVARCHAR](200) 
	,[sys_extract_dt] [NVARCHAR](40) 
	,[sys_cdc_dt] [NVARCHAR](40) 
	,[sys_cdc_scn] [NVARCHAR](14) 
	,[sys_cdc_operation_type] [NVARCHAR](15) 
	,[sys_cdc_before_after] [NVARCHAR](10) 
	,[sys_line_modified_ind] [VARCHAR](20) 
	,[dndmct] [NVARCHAR](12) 
	,[dndmcs] [DECIMAL](38, 4) 
	,[dndl01] [NVARCHAR](30) 
	,[dndl02] [NVARCHAR](30) 
	,[dndl03] [NVARCHAR](30) 
	,[dnmcu] [NVARCHAR](12) 
	,[dnnwrn] [NVARCHAR](1) 
	,[dnagrs] [NVARCHAR](1) 
	,[dncman] [DECIMAL](38, 4) 
	,[dncadm] [DECIMAL](38, 4) 
	,[dnpanm] [NVARCHAR](25) 
	,[dncntd] [VARCHAR](20) 
	,[dndmtc] [NVARCHAR](1) 
	,[dndmpc] [NVARCHAR](3) 
	,[dndmsc] [NVARCHAR](1) 
	,[dneftj] [VARCHAR](20) 
	,[dnexdj] [VARCHAR](20) 
	,[dnan8] [DECIMAL](38, 4) 
	,[dnaagm] [NVARCHAR](12) 
	,[dnaags] [DECIMAL](38, 4) 
	,[dnragm] [NVARCHAR](12) 
	,[dnrags] [DECIMAL](38, 4) 
	,[dncagm] [NVARCHAR](12) 
	,[dncags] [DECIMAL](38, 4) 
	,[dnpagm] [NVARCHAR](12) 
	,[dnpags] [DECIMAL](38, 4) 
	,[dnzd01] [NVARCHAR](3) 
	,[dnzd02] [NVARCHAR](3) 
	,[dnzd03] [NVARCHAR](3) 
	,[dnzd04] [NVARCHAR](3) 
	,[dnzd05] [NVARCHAR](3) 
	,[dnzd06] [NVARCHAR](3) 
	,[dnzd07] [NVARCHAR](3) 
	,[dnzd08] [NVARCHAR](3) 
	,[dnzd09] [NVARCHAR](3) 
	,[dnzd10] [NVARCHAR](3) 
	,[dnqedt] [NVARCHAR](1) 
	,[dncand] [VARCHAR](20) 
	,[dncanr] [NVARCHAR](3) 
	,[dnupgl] [NVARCHAR](1) 
	,[dnpras] [NVARCHAR](1) 
	,[dncmoo] [NVARCHAR](1) 
	,[dncnqy] [NVARCHAR](1) 
	,[dntv01] [NVARCHAR](1) 
	,[dntv02] [NVARCHAR](1) 
	,[dntv03] [NVARCHAR](1) 
	,[dnurcd] [NVARCHAR](2) 
	,[dnurdt] [VARCHAR](20) 
	,[dnurat] [DECIMAL](38, 4) 
	,[dnurab] [DECIMAL](38, 4) 
	,[dnurrf] [NVARCHAR](15) 
	,[dnuser] [NVARCHAR](10) 
	,[dnpid] [NVARCHAR](10) 
	,[dnjobn] [NVARCHAR](10) 
	,[dnupmj] [VARCHAR](20) 
	,[dntday] [DECIMAL](38, 4) 
	,[dnrpqt] [DECIMAL](38, 4) 
	,[dnqed3] [NVARCHAR](1) 
	,[dnqed2] [NVARCHAR](1) 
)
WITH
(
    LOCATION='processing-clean/jde_qat/f38010/init/'
    ,DATA_SOURCE = [dw-landing-fs]
    ,FILE_FORMAT = [jde_fileformat_124_127_no_header]
)
