--Create ext table for init
IF OBJECT_ID('stg_jde_qat.ext_f49219_init') IS NOT NULL
    DROP EXTERNAL TABLE stg_jde_qat.ext_f49219_init

CREATE EXTERNAL TABLE stg_jde_qat.ext_f49219_init
(
	[sys_file_name] [NVARCHAR](100) 
	,[sys_file_ln] [VARCHAR](20) 
	,[sys_integration_id] [NVARCHAR](200) 
	,[sys_extract_dt] [NVARCHAR](40) 
	,[sys_cdc_dt] [NVARCHAR](40) 
	,[sys_cdc_scn] [NVARCHAR](14) 
	,[sys_cdc_operation_type] [NVARCHAR](15) 
	,[sys_cdc_before_after] [NVARCHAR](10) 
	,[sys_line_modified_ind] [VARCHAR](20) 
	,[uddoco] [DECIMAL](38, 4) 
	,[uddcto] [NVARCHAR](2) 
	,[udkcoo] [NVARCHAR](5) 
	,[udlnid] [DECIMAL](38, 4) 
	,[udvmcu] [NVARCHAR](12) 
	,[udtrp] [DECIMAL](38, 4) 
	,[udload] [VARCHAR](20) 
	,[uddsgp] [NVARCHAR](3) 
	,[udbpfg] [NVARCHAR](1) 
	,[uddstn] [DECIMAL](38, 4) 
	,[udum] [NVARCHAR](2) 
	,[uddeff] [NVARCHAR](1) 
	,[uddunc] [DECIMAL](38, 4) 
	,[udfduc] [DECIMAL](38, 4) 
	,[uddrev] [DECIMAL](38, 4) 
	,[udfdrv] [DECIMAL](38, 4) 
	,[udanum] [DECIMAL](38, 4) 
	,[udsidt] [VARCHAR](20) 
	,[udincy] [NVARCHAR](3) 
	,[udlddt] [VARCHAR](20) 
	,[udldtm] [DECIMAL](38, 4) 
	,[uddcdt] [VARCHAR](20) 
	,[udpcqy] [DECIMAL](38, 4) 
	,[uduomc] [NVARCHAR](2) 
	,[udtemp] [DECIMAL](38, 4) 
	,[udstpu] [NVARCHAR](1) 
	,[uddnty] [DECIMAL](38, 4) 
	,[uddntp] [NVARCHAR](1) 
	,[uddetp] [DECIMAL](38, 4) 
	,[uddtpu] [NVARCHAR](1) 
	,[udvcf] [DECIMAL](38, 4) 
	,[udpras] [NVARCHAR](1) 
	,[udcp01] [NVARCHAR](1) 
	,[udiqty] [DECIMAL](38, 4) 
	,[udstum] [DECIMAL](38, 4) 
	,[udbum6] [NVARCHAR](2) 
	,[udambr] [DECIMAL](38, 4) 
	,[udbum3] [NVARCHAR](2) 
	,[udwgtr] [DECIMAL](38, 4) 
	,[udbum5] [NVARCHAR](2) 
	,[udfrtv] [NVARCHAR](1) 
	,[udfrtd] [NVARCHAR](1) 
	,[udfrcc] [DECIMAL](38, 4) 
	,[udfrvc] [DECIMAL](38, 4) 
	,[udpveh] [NVARCHAR](12) 
	,[udrlno] [NVARCHAR](13) 
	,[udmcur] [NVARCHAR](12) 
	,[udfltn] [NVARCHAR](8) 
	,[uddsnn] [NVARCHAR](5) 
	,[udarct] [NVARCHAR](5) 
	,[udsorg] [NVARCHAR](15) 
	,[udeltm] [DECIMAL](38, 4) 
	,[udptnr] [DECIMAL](38, 4) 
	,[udian8] [DECIMAL](38, 4) 
	,[udptc] [NVARCHAR](3) 
	,[uddoc] [DECIMAL](38, 4) 
	,[uddct] [NVARCHAR](2) 
	,[udkco] [NVARCHAR](5) 
	,[udcrr] [DECIMAL](38, 4) 
	,[udcrcd] [NVARCHAR](3) 
	,[udtxa1] [NVARCHAR](10) 
	,[udexr1] [NVARCHAR](2) 
	,[udtv01] [NVARCHAR](1) 
	,[udtv02] [NVARCHAR](1) 
	,[udtv03] [NVARCHAR](1) 
	,[udtv04] [NVARCHAR](1) 
	,[udtv05] [NVARCHAR](1) 
	,[udtvcd] [NVARCHAR](2) 
	,[udtvqt] [DECIMAL](38, 4) 
	,[udtvdt] [VARCHAR](20) 
	,[udtvum] [NVARCHAR](2) 
	,[uduser] [NVARCHAR](10) 
	,[udpid] [NVARCHAR](10) 
	,[udjobn] [NVARCHAR](10) 
	,[udupmj] [VARCHAR](20) 
	,[udtday] [DECIMAL](38, 4) 
	,[udsbck] [NVARCHAR](1) 
	,[udedck] [NVARCHAR](1) 
	,[udcmdm] [NVARCHAR](1) 
	,[udbbck] [NVARCHAR](1) 
	,[udrqsj] [VARCHAR](20) 
	,[udpsdj] [VARCHAR](20) 
	,[udadlj] [VARCHAR](20) 
	,[udsub] [NVARCHAR](8) 
	,[udstts] [NVARCHAR](2) 
	,[udratt] [NVARCHAR](1) 
	,[udfuf1] [NVARCHAR](1) 
	,[udfrtc] [NVARCHAR](1) 
	,[udfrat] [NVARCHAR](10) 
	,[udaft] [NVARCHAR](1) 
	,[udomcu] [NVARCHAR](12) 
	,[udobj] [NVARCHAR](6) 
	,[udlt] [NVARCHAR](2) 
	,[udfapp] [NVARCHAR](1) 
	,[uddspr] [DECIMAL](38, 4) 
	,[uddsft] [NVARCHAR](1) 
	,[uddmt1] [NVARCHAR](12) 
	,[uddms1] [DECIMAL](38, 4) 
	,[udcot] [NVARCHAR](3) 
	,[udcmgl] [NVARCHAR](1) 
	,[udbalu] [NVARCHAR](1) 
	,[udapot] [DECIMAL](38, 4) 
	,[udacgd] [NVARCHAR](3) 
	,[udani] [NVARCHAR](29) 
	,[udaid] [NVARCHAR](8) 
	,[udopol] [DECIMAL](38, 4) 
	,[udopbo] [NVARCHAR](30) 
	,[udopid] [NVARCHAR](30) 
	,[udopcs] [DECIMAL](38, 4) 
	,[udopll] [NVARCHAR](1) 
	,[udopms] [NVARCHAR](1) 
	,[udopss] [NVARCHAR](1) 
	,[udopba] [NVARCHAR](1) 
	,[udfxsr] [NVARCHAR](1) 
	,[udpsjobno] [NVARCHAR](15) 
	,[udjobsq] [NVARCHAR](15) 
	,[udcardno] [NVARCHAR](4) 
	,[uddelbatch] [NVARCHAR](6) 
)
WITH
(
    LOCATION='processing-clean/jde_qat/f49219/init/'
    ,DATA_SOURCE = [dw-landing-fs]
    ,FILE_FORMAT = [jde_fileformat_124_127_no_header]
)
