--Create ext table for init
IF OBJECT_ID('stg_jde_qat.ext_f4960_init') IS NOT NULL
    DROP EXTERNAL TABLE stg_jde_qat.ext_f4960_init

CREATE EXTERNAL TABLE stg_jde_qat.ext_f4960_init
(
	[sys_file_name] [NVARCHAR](100) 
	,[sys_file_ln] [VARCHAR](20) 
	,[sys_integration_id] [NVARCHAR](200) 
	,[sys_extract_dt] [NVARCHAR](40) 
	,[sys_cdc_dt] [NVARCHAR](40) 
	,[sys_cdc_scn] [NVARCHAR](14) 
	,[sys_cdc_operation_type] [NVARCHAR](15) 
	,[sys_cdc_before_after] [NVARCHAR](10) 
	,[sys_line_modified_ind] [VARCHAR](20) 
	,[tmvmcu] [NVARCHAR](12) 
	,[tmldnm] [DECIMAL](38, 4) 
	,[tmnmcu] [NVARCHAR](12) 
	,[tmorgn] [DECIMAL](38, 4) 
	,[tmmcux] [NVARCHAR](12) 
	,[tmancc] [DECIMAL](38, 4) 
	,[tmanid] [DECIMAL](38, 4) 
	,[tmovod] [NVARCHAR](1) 
	,[tmcty1] [NVARCHAR](25) 
	,[tmadds] [NVARCHAR](3) 
	,[tmaddz] [NVARCHAR](12) 
	,[tmctr] [NVARCHAR](3) 
	,[tmzon] [NVARCHAR](3) 
	,[tmldty] [NVARCHAR](2) 
	,[tmldls] [NVARCHAR](2) 
	,[tmload] [VARCHAR](20) 
	,[tmshft] [NVARCHAR](1) 
	,[tmseq] [DECIMAL](38, 4) 
	,[tmtmls] [DECIMAL](38, 4) 
	,[tmppdj] [VARCHAR](20) 
	,[tmpmdt] [DECIMAL](38, 4) 
	,[tmaddj] [VARCHAR](20) 
	,[tmadtm] [DECIMAL](38, 4) 
	,[tmmot] [NVARCHAR](3) 
	,[tmovrm] [NVARCHAR](1) 
	,[tmvtyp] [NVARCHAR](12) 
	,[tmpveh] [NVARCHAR](12) 
	,[tmrlno] [NVARCHAR](13) 
	,[tmdumv] [NVARCHAR](1) 
	,[tmcnnv] [NVARCHAR](1) 
	,[tmcars] [DECIMAL](38, 4) 
	,[tmovrc] [NVARCHAR](1) 
	,[tmrout] [NVARCHAR](3) 
	,[tmrtn] [DECIMAL](38, 4) 
	,[tmfrsc] [NVARCHAR](8) 
	,[tmczon] [NVARCHAR](10) 
	,[tmdsgp] [NVARCHAR](3) 
	,[tmdaty] [NVARCHAR](1) 
	,[tmdscd] [NVARCHAR](1) 
	,[tmldle] [NVARCHAR](1) 
	,[tmseal] [DECIMAL](38, 4) 
	,[tmlmcu] [NVARCHAR](12) 
	,[tmltrp] [DECIMAL](38, 4) 
	,[tmdstn] [DECIMAL](38, 4) 
	,[tmumd1] [NVARCHAR](2) 
	,[tmdsrc] [NVARCHAR](1) 
	,[tmodst] [DECIMAL](38, 4) 
	,[tmeltm] [DECIMAL](38, 4) 
	,[tmum] [NVARCHAR](2) 
	,[tmcvum] [NVARCHAR](2) 
	,[tmwtum] [NVARCHAR](2) 
	,[tmvlum] [NVARCHAR](2) 
	,[tmvr01] [NVARCHAR](25) 
	,[tmnstp] [DECIMAL](38, 4) 
	,[tmrrtr] [NVARCHAR](1) 
	,[tmratr] [NVARCHAR](1) 
	,[tmfrvc] [DECIMAL](38, 4) 
	,[tmfrvf] [DECIMAL](38, 4) 
	,[tmcrcp] [NVARCHAR](3) 
	,[tmibrs] [NVARCHAR](1) 
	,[tmdkid] [NVARCHAR](20) 
	,[tmdepu] [VARCHAR](20) 
	,[tmdlpu] [VARCHAR](20) 
	,[tmtpuf] [DECIMAL](38, 4) 
	,[tmtput] [DECIMAL](38, 4) 
	,[tmlslt] [DECIMAL](38, 4) 
	,[tmlsut] [DECIMAL](38, 4) 
	,[tmlalt] [DECIMAL](38, 4) 
	,[tmlaut] [DECIMAL](38, 4) 
	,[tmurcd] [NVARCHAR](2) 
	,[tmurdt] [VARCHAR](20) 
	,[tmurat] [DECIMAL](38, 4) 
	,[tmurab] [DECIMAL](38, 4) 
	,[tmurrf] [NVARCHAR](15) 
	,[tmuser] [NVARCHAR](10) 
	,[tmpid] [NVARCHAR](10) 
	,[tmjobn] [NVARCHAR](10) 
	,[tmupmj] [VARCHAR](20) 
	,[tmtday] [DECIMAL](38, 4) 
)
WITH
(
    LOCATION='processing-clean/jde_qat/f4960/init/'
    ,DATA_SOURCE = [dw-landing-fs]
    ,FILE_FORMAT = [jde_fileformat_124_127_no_header]
)
