--Create ext table for init
IF OBJECT_ID('stg_jde_qat.ext_f554103_init') IS NOT NULL
    DROP EXTERNAL TABLE stg_jde_qat.ext_f554103_init

CREATE EXTERNAL TABLE stg_jde_qat.ext_f554103_init
(
	[sys_file_name] [NVARCHAR](100) 
	,[sys_file_ln] [VARCHAR](20) 
	,[sys_integration_id] [NVARCHAR](200) 
	,[sys_extract_dt] [NVARCHAR](40) 
	,[sys_cdc_dt] [NVARCHAR](40) 
	,[sys_cdc_scn] [NVARCHAR](14) 
	,[sys_cdc_operation_type] [NVARCHAR](15) 
	,[sys_cdc_before_after] [NVARCHAR](10) 
	,[sys_line_modified_ind] [VARCHAR](20) 
	,[alresc] [DECIMAL](38, 4) 
	,[alukid] [DECIMAL](38, 4) 
	,[altrmnum] [NVARCHAR](11) 
	,[alfrto] [NVARCHAR](1) 
	,[aledbt] [NVARCHAR](15) 
	,[aledtn] [NVARCHAR](22) 
	,[alfrsq] [NVARCHAR](10) 
	,[aly55sttsl] [NVARCHAR](2) 
	,[almcu] [NVARCHAR](12) 
	,[alddday] [VARCHAR](20) 
	,[altday] [DECIMAL](38, 4) 
	,[alvehi] [NVARCHAR](12) 
	,[aly55owid] [NVARCHAR](15) 
	,[alitm] [DECIMAL](38, 4) 
	,[allitm] [NVARCHAR](25) 
	,[alaitm] [NVARCHAR](25) 
	,[alambr] [DECIMAL](38, 4) 
	,[aluom1] [NVARCHAR](2) 
	,[album3] [NVARCHAR](2) 
	,[alyshipty] [NVARCHAR](10) 
	,[allocn] [NVARCHAR](20) 
	,[aly55aglc] [NVARCHAR](2) 
	,[aly55agto] [NVARCHAR](2) 
	,[alsid] [NVARCHAR](16) 
	,[alstok] [DECIMAL](38, 4) 
	,[aluom2] [NVARCHAR](2) 
	,[album4] [NVARCHAR](2) 
	,[alanby] [DECIMAL](38, 4) 
	,[alancc] [DECIMAL](38, 4) 
	,[alan8] [DECIMAL](38, 4) 
	,[alshan] [DECIMAL](38, 4) 
	,[aly55wbno] [NVARCHAR](20) 
	,[alldty] [NVARCHAR](2) 
	,[altkid] [NVARCHAR](8) 
	,[altemp] [DECIMAL](38, 4) 
	,[aluom3] [NVARCHAR](2) 
	,[alstpu] [NVARCHAR](1) 
	,[alvlc1] [DECIMAL](38, 4) 
	,[aldnty] [DECIMAL](38, 4) 
	,[aldend] [DECIMAL](38, 4) 
	,[aldntp] [NVARCHAR](1) 
	,[almetn] [NVARCHAR](10) 
	,[aly55cpnm] [NVARCHAR](10) 
	,[aly55crdid] [NVARCHAR](10) 
	,[aldsc1] [NVARCHAR](30) 
	,[alflag] [NVARCHAR](1) 
	,[aly55txt1] [NVARCHAR](30) 
	,[alev01] [NVARCHAR](1) 
	,[alev02] [NVARCHAR](1) 
	,[alev03] [NVARCHAR](1) 
	,[alev04] [NVARCHAR](1) 
	,[alev05] [NVARCHAR](1) 
	,[alkcoo] [NVARCHAR](5) 
	,[aldcto] [NVARCHAR](2) 
	,[aldoco] [DECIMAL](38, 4) 
	,[allnid] [DECIMAL](38, 4) 
	,[alrkco] [NVARCHAR](5) 
	,[alrcto] [NVARCHAR](2) 
	,[alrorn] [NVARCHAR](8) 
	,[alxlin] [DECIMAL](38, 4) 
	,[alkco] [NVARCHAR](5) 
	,[aldct] [NVARCHAR](2) 
	,[aldoc] [DECIMAL](38, 4) 
	,[allinn] [DECIMAL](38, 4) 
	,[alokco] [NVARCHAR](5) 
	,[alocto] [NVARCHAR](2) 
	,[aloorn] [NVARCHAR](8) 
	,[alogno] [DECIMAL](38, 4) 
	,[alskco] [NVARCHAR](5) 
	,[alsdct] [NVARCHAR](2) 
	,[alsdoc] [DECIMAL](38, 4) 
	,[alslne] [DECIMAL](38, 4) 
	,[alicu] [DECIMAL](38, 4) 
	,[altd1] [NVARCHAR](2) 
	,[aluser] [NVARCHAR](10) 
	,[alpid] [NVARCHAR](10) 
	,[aljobn] [NVARCHAR](10) 
	,[alupmj] [VARCHAR](20) 
	,[alupmt] [DECIMAL](38, 4) 
	,[als1fu] [NVARCHAR](30) 
	,[als2fu] [NVARCHAR](30) 
	,[alfuf9] [DECIMAL](38, 4) 
	,[alpstm] [DECIMAL](38, 4) 
	,[alcburst1] [NVARCHAR](5) 
	,[alcburst2] [NVARCHAR](5) 
	,[aleaurst1] [NVARCHAR](5) 
	,[aly55amnt1] [DECIMAL](38, 4) 
	,[aly55amnt2] [DECIMAL](38, 4) 
	,[aly55date1] [VARCHAR](20) 
	,[aly55date2] [VARCHAR](20) 
	,[aly55time1] [DECIMAL](38, 4) 
	,[aly55strg1] [NVARCHAR](30) 
	,[aly55strg2] [NVARCHAR](30) 
	,[aly55char1] [NVARCHAR](1) 
	,[aly55char2] [NVARCHAR](1) 
)
WITH
(
    LOCATION='processing-clean/jde_qat/f554103/init/'
    ,DATA_SOURCE = [dw-landing-fs]
    ,FILE_FORMAT = [jde_fileformat_124_127_no_header]
)
