--Create ext table for init
IF OBJECT_ID('stg_jde_qat.ext_f9210_init') IS NOT NULL
    DROP EXTERNAL TABLE stg_jde_qat.ext_f9210_init

CREATE EXTERNAL TABLE stg_jde_qat.ext_f9210_init
(
	[sys_file_name] [NVARCHAR](100) 
	,[sys_file_ln] [VARCHAR](20) 
	,[sys_integration_id] [NVARCHAR](200) 
	,[sys_extract_dt] [NVARCHAR](40) 
	,[sys_cdc_dt] [NVARCHAR](40) 
	,[sys_cdc_scn] [NVARCHAR](14) 
	,[sys_cdc_operation_type] [NVARCHAR](15) 
	,[sys_cdc_before_after] [NVARCHAR](10) 
	,[sys_line_modified_ind] [VARCHAR](20) 
	,[frdtai] [NVARCHAR](10) 
	,[frclas] [NVARCHAR](10) 
	,[frdtat] [NVARCHAR](1) 
	,[frdtas] [DECIMAL](38, 4) 
	,[frdtad] [DECIMAL](38, 4) 
	,[frpdta] [NVARCHAR](10) 
	,[frarrn] [DECIMAL](38, 4) 
	,[frdval] [NVARCHAR](40) 
	,[frlr] [NVARCHAR](1) 
	,[frcdec] [NVARCHAR](1) 
	,[frdrul] [NVARCHAR](6) 
	,[frdro1] [NVARCHAR](40) 
	,[frerul] [NVARCHAR](6) 
	,[frero1] [NVARCHAR](40) 
	,[frero2] [NVARCHAR](40) 
	,[frhlp1] [NVARCHAR](10) 
	,[frhlp2] [NVARCHAR](10) 
	,[frnnix] [DECIMAL](38, 4) 
	,[frnsy] [NVARCHAR](4) 
	,[frrls] [NVARCHAR](10) 
	,[fruser] [NVARCHAR](10) 
	,[frupmj] [VARCHAR](20) 
	,[frpid] [NVARCHAR](10) 
	,[frjobn] [NVARCHAR](10) 
	,[frupmt] [DECIMAL](38, 4) 
	,[frowdi] [NVARCHAR](40) 
	,[frowtp] [NVARCHAR](2) 
	,[frcntt] [NVARCHAR](1) 
	,[frscfg] [NVARCHAR](1) 
	,[fruper] [NVARCHAR](1) 
	,[fralbk] [NVARCHAR](1) 
	,[frower] [NVARCHAR](6) 
	,[froer1] [NVARCHAR](40) 
	,[froer2] [NVARCHAR](40) 
	,[frowdr] [NVARCHAR](6) 
	,[frodr1] [NVARCHAR](40) 
	,[frdbid] [NVARCHAR](11) 
	,[frbfdn] [NVARCHAR](32) 
	,[frebid] [NVARCHAR](11) 
	,[frbfen] [NVARCHAR](32) 
	,[frsfid] [NVARCHAR](11) 
	,[frsfmn] [NVARCHAR](10) 
	,[frbvid] [NVARCHAR](11) 
	,[frbvnm] [NVARCHAR](10) 
	,[frplfg] [NVARCHAR](1) 
	,[frddid] [NVARCHAR](11) 
	,[frauin] [NVARCHAR](1) 
)
WITH
(
    LOCATION='processing-clean/jde_qat/f9210/init/'
    ,DATA_SOURCE = [dw-landing-fs]
    ,FILE_FORMAT = [jde_fileformat_124_127_no_header]
)
