-- Apply updates from upsert table onto rep new table
UPDATE rep_jde.f3460_new
SET
	[sys_file_name] = cdc.[sys_file_name]
	,[sys_file_ln] = cdc.[sys_file_ln]
	,[sys_extract_dt] = cdc.[sys_extract_dt]
	,[sys_cdc_dt] = cdc.[sys_cdc_dt]
	,[sys_cdc_scn] = cdc.[sys_cdc_scn]
	,[sys_cdc_operation_type] = cdc.[sys_cdc_operation_type]
	,[sys_cdc_before_after] = cdc.[sys_cdc_before_after]
	,[sys_line_modified_ind] = cdc.[sys_line_modified_ind]
	,[mfitm] = cdc.[mfitm]
	,[mflitm] = cdc.[mflitm]
	,[mflitm_conv] = cdc.[mflitm_conv]
	,[mfaitm] = cdc.[mfaitm]
	,[mfaitm_conv] = cdc.[mfaitm_conv]
	,[mfmcu] = cdc.[mfmcu]
	,[mfmcu_conv] = cdc.[mfmcu_conv]
	,[mfdrqj] = cdc.[mfdrqj]
	,[mfdrqj_conv] = cdc.[mfdrqj_conv]
	,[mfan8] = cdc.[mfan8]
	,[mfuorg] = cdc.[mfuorg]
	,[mfuorg_conv] = cdc.[mfuorg_conv]
	,[mfaexp] = cdc.[mfaexp]
	,[mfaexp_conv] = cdc.[mfaexp_conv]
	,[mffam] = cdc.[mffam]
	,[mffam_conv] = cdc.[mffam_conv]
	,[mffqt] = cdc.[mffqt]
	,[mffqt_conv] = cdc.[mffqt_conv]
	,[mftypf] = cdc.[mftypf]
	,[mfdcto] = cdc.[mfdcto]
	,[mfbpfc] = cdc.[mfbpfc]
	,[mfbpfc_conv] = cdc.[mfbpfc_conv]
	,[mfrvis] = cdc.[mfrvis]
	,[mfrvis_conv] = cdc.[mfrvis_conv]
	,[mfupmj] = cdc.[mfupmj]
	,[mfupmj_conv] = cdc.[mfupmj_conv]
	,[mfuser] = cdc.[mfuser]
	,[mfuser_conv] = cdc.[mfuser_conv]
	,[mfjobn] = cdc.[mfjobn]
	,[mfjobn_conv] = cdc.[mfjobn_conv]
	,[mfpid] = cdc.[mfpid]
	,[mfpid_conv] = cdc.[mfpid_conv]
	,[mfyr] = cdc.[mfyr]
	,[mfyr_conv] = cdc.[mfyr_conv]
	,[mftday] = cdc.[mftday]
	,[mfpmpn] = cdc.[mfpmpn]
	,[mfpmpn_conv] = cdc.[mfpmpn_conv]
	,[mfpns] = cdc.[mfpns] -- exclude distribution column
FROM stg_jde.tmp_upsert_f3460_cdc cdc
WHERE
    rep_jde.f3460_new.sys_integration_id = cdc.sys_integration_id
    AND rep_jde.f3460_new.sys_cdc_scn < cdc.sys_cdc_scn 
OPTION ( LABEL = 'UPDATE_rep_jde.f3460_new AF:{{ task_instance_key_str }}' ) 
