-- Apply updates from upsert table onto rep new table
UPDATE rep_jde.f38112_new
SET
	[sys_file_name] = cdc.[sys_file_name]
	,[sys_file_ln] = cdc.[sys_file_ln]
	,[sys_extract_dt] = cdc.[sys_extract_dt]
	,[sys_cdc_dt] = cdc.[sys_cdc_dt]
	,[sys_cdc_scn] = cdc.[sys_cdc_scn]
	,[sys_cdc_operation_type] = cdc.[sys_cdc_operation_type]
	,[sys_cdc_before_after] = cdc.[sys_cdc_before_after]
	,[sys_line_modified_ind] = cdc.[sys_line_modified_ind]
	,[dxdoco] = cdc.[dxdoco]
	,[dxdcto] = cdc.[dxdcto]
	,[dxkcoo] = cdc.[dxkcoo]
	,[dxkcoo_conv] = cdc.[dxkcoo_conv]
	,[dxlnid] = cdc.[dxlnid]
	,[dxlnid_conv] = cdc.[dxlnid_conv]
	,[dxdmct] = cdc.[dxdmct]
	,[dxdmct_conv] = cdc.[dxdmct_conv]
	,[dxdmcs] = cdc.[dxdmcs]
	,[dxmcu] = cdc.[dxmcu]
	,[dxmcu_conv] = cdc.[dxmcu_conv]
	,[dxseq] = cdc.[dxseq]
	,[dxpsr] = cdc.[dxpsr]
	,[dxpsr_conv] = cdc.[dxpsr_conv]
	,[dxpsry] = cdc.[dxpsry]
	,[dxqcom] = cdc.[dxqcom]
	,[dxqcom_conv] = cdc.[dxqcom_conv]
	,[dxcnqy] = cdc.[dxcnqy]
	,[dxaa] = cdc.[dxaa]
	,[dxaa_conv] = cdc.[dxaa_conv]
	,[dxcrcd] = cdc.[dxcrcd]
	,[dxcrcd_conv] = cdc.[dxcrcd_conv]
	,[dxuom] = cdc.[dxuom]
	,[dxtrdj] = cdc.[dxtrdj]
	,[dxtrdj_conv] = cdc.[dxtrdj_conv]
	,[dxtv01] = cdc.[dxtv01]
	,[dxtv01_conv] = cdc.[dxtv01_conv]
	,[dxtv02] = cdc.[dxtv02]
	,[dxtv02_conv] = cdc.[dxtv02_conv]
	,[dxtv03] = cdc.[dxtv03]
	,[dxtv03_conv] = cdc.[dxtv03_conv]
	,[dxurcd] = cdc.[dxurcd]
	,[dxurcd_conv] = cdc.[dxurcd_conv]
	,[dxurdt] = cdc.[dxurdt]
	,[dxurdt_conv] = cdc.[dxurdt_conv]
	,[dxurab] = cdc.[dxurab]
	,[dxurab_conv] = cdc.[dxurab_conv]
	,[dxurrf] = cdc.[dxurrf]
	,[dxurrf_conv] = cdc.[dxurrf_conv]
	,[dxuser] = cdc.[dxuser]
	,[dxuser_conv] = cdc.[dxuser_conv]
	,[dxpid] = cdc.[dxpid]
	,[dxpid_conv] = cdc.[dxpid_conv]
	,[dxjobn] = cdc.[dxjobn]
	,[dxjobn_conv] = cdc.[dxjobn_conv]
	,[dxupmj] = cdc.[dxupmj]
	,[dxupmj_conv] = cdc.[dxupmj_conv]
	,[dxtday] = cdc.[dxtday] -- exclude distribution column
FROM stg_jde.tmp_upsert_f38112_cdc cdc
WHERE
    rep_jde.f38112_new.sys_integration_id = cdc.sys_integration_id
    AND rep_jde.f38112_new.sys_cdc_scn < cdc.sys_cdc_scn 
OPTION ( LABEL = 'UPDATE_rep_jde.f38112_new AF:{{ task_instance_key_str }}' ) 
