-- Apply updates from upsert table onto rep new table
UPDATE rep_jde.f41061_new
SET
	[sys_file_name] = cdc.[sys_file_name]
	,[sys_file_ln] = cdc.[sys_file_ln]
	,[sys_extract_dt] = cdc.[sys_extract_dt]
	,[sys_cdc_dt] = cdc.[sys_cdc_dt]
	,[sys_cdc_scn] = cdc.[sys_cdc_scn]
	,[sys_cdc_operation_type] = cdc.[sys_cdc_operation_type]
	,[sys_cdc_before_after] = cdc.[sys_cdc_before_after]
	,[sys_line_modified_ind] = cdc.[sys_line_modified_ind]
	,[cbmcu] = cdc.[cbmcu]
	,[cbmcu_conv] = cdc.[cbmcu_conv]
	,[cban8] = cdc.[cban8]
	,[cbitm] = cdc.[cbitm]
	,[cblitm] = cdc.[cblitm]
	,[cblitm_conv] = cdc.[cblitm_conv]
	,[cbaitm] = cdc.[cbaitm]
	,[cbaitm_conv] = cdc.[cbaitm_conv]
	,[cbcatn] = cdc.[cbcatn]
	,[cbdmct] = cdc.[cbdmct]
	,[cbdmct_conv] = cdc.[cbdmct_conv]
	,[cbdmcs] = cdc.[cbdmcs]
	,[cbkcoo] = cdc.[cbkcoo]
	,[cbkcoo_conv] = cdc.[cbkcoo_conv]
	,[cbdoco] = cdc.[cbdoco]
	,[cbdcto] = cdc.[cbdcto]
	,[cblnid] = cdc.[cblnid]
	,[cblnid_conv] = cdc.[cblnid_conv]
	,[cbcrcd] = cdc.[cbcrcd]
	,[cbcrcd_conv] = cdc.[cbcrcd_conv]
	,[cbuom] = cdc.[cbuom]
	,[cbprrc] = cdc.[cbprrc]
	,[cbprrc_conv] = cdc.[cbprrc_conv]
	,[cbuorg] = cdc.[cbuorg]
	,[cbuorg_conv] = cdc.[cbuorg_conv]
	,[cbeftj] = cdc.[cbeftj]
	,[cbeftj_conv] = cdc.[cbeftj_conv]
	,[cbexdj] = cdc.[cbexdj]
	,[cbexdj_conv] = cdc.[cbexdj_conv]
	,[cbuser] = cdc.[cbuser]
	,[cbuser_conv] = cdc.[cbuser_conv]
	,[cbpid] = cdc.[cbpid]
	,[cbpid_conv] = cdc.[cbpid_conv]
	,[cbjobn] = cdc.[cbjobn]
	,[cbjobn_conv] = cdc.[cbjobn_conv]
	,[cbupmj] = cdc.[cbupmj]
	,[cbupmj_conv] = cdc.[cbupmj_conv]
	,[cbtday] = cdc.[cbtday] -- exclude distribution column
FROM stg_jde.tmp_upsert_f41061_cdc cdc
WHERE
    rep_jde.f41061_new.sys_integration_id = cdc.sys_integration_id
    AND rep_jde.f41061_new.sys_cdc_scn < cdc.sys_cdc_scn 
OPTION ( LABEL = 'UPDATE_rep_jde.f41061_new AF:{{ task_instance_key_str }}' ) 
