-- Apply updates from upsert table onto rep new table
UPDATE rep_jde.f4209_new
SET
	[sys_file_name] = cdc.[sys_file_name]
	,[sys_file_ln] = cdc.[sys_file_ln]
	,[sys_extract_dt] = cdc.[sys_extract_dt]
	,[sys_cdc_dt] = cdc.[sys_cdc_dt]
	,[sys_cdc_scn] = cdc.[sys_cdc_scn]
	,[sys_cdc_operation_type] = cdc.[sys_cdc_operation_type]
	,[sys_cdc_before_after] = cdc.[sys_cdc_before_after]
	,[sys_line_modified_ind] = cdc.[sys_line_modified_ind]
	,[hohcod] = cdc.[hohcod]
	,[horper] = cdc.[horper]
	,[horper_conv] = cdc.[horper_conv]
	,[hoan8] = cdc.[hoan8]
	,[homcu] = cdc.[homcu]
	,[homcu_conv] = cdc.[homcu_conv]
	,[hokcoo] = cdc.[hokcoo]
	,[hokcoo_conv] = cdc.[hokcoo_conv]
	,[hodoco] = cdc.[hodoco]
	,[hodcto] = cdc.[hodcto]
	,[hosfxo] = cdc.[hosfxo]
	,[hosfxo_conv] = cdc.[hosfxo_conv]
	,[holnid] = cdc.[holnid]
	,[holnid_conv] = cdc.[holnid_conv]
	,[hoitm] = cdc.[hoitm]
	,[holitm] = cdc.[holitm]
	,[holitm_conv] = cdc.[holitm_conv]
	,[hoaitm] = cdc.[hoaitm]
	,[hoaitm_conv] = cdc.[hoaitm_conv]
	,[hotrdj] = cdc.[hotrdj]
	,[hotrdj_conv] = cdc.[hotrdj_conv]
	,[hodrqj] = cdc.[hodrqj]
	,[hodrqj_conv] = cdc.[hodrqj_conv]
	,[hopddj] = cdc.[hopddj]
	,[hopddj_conv] = cdc.[hopddj_conv]
	,[hoctyp] = cdc.[hoctyp]
	,[hordc] = cdc.[hordc]
	,[hordb] = cdc.[hordb]
	,[hordb_conv] = cdc.[hordb_conv]
	,[hordj] = cdc.[hordj]
	,[hordj_conv] = cdc.[hordj_conv]
	,[hordt] = cdc.[hordt]
	,[hoartg] = cdc.[hoartg]
	,[hoartg_conv] = cdc.[hoartg_conv]
	,[hoasts] = cdc.[hoasts]
	,[hoasts_conv] = cdc.[hoasts_conv]
	,[hoaty] = cdc.[hoaty]
	,[hoaty_conv] = cdc.[hoaty_conv]
	,[hoedei] = cdc.[hoedei]
	,[hoedei_conv] = cdc.[hoedei_conv]
	,[hodlnid] = cdc.[hodlnid]
	,[hodlnid_conv] = cdc.[hodlnid_conv]
	,[hopa8] = cdc.[hopa8]
	,[hoshan] = cdc.[hoshan] -- exclude distribution column
FROM stg_jde.tmp_upsert_f4209_cdc cdc
WHERE
    rep_jde.f4209_new.sys_integration_id = cdc.sys_integration_id
    AND rep_jde.f4209_new.sys_cdc_scn < cdc.sys_cdc_scn 
OPTION ( LABEL = 'UPDATE_rep_jde.f4209_new AF:{{ task_instance_key_str }}' ) 
