-- Apply updates from upsert table onto rep new table
UPDATE rep_jde.f554922_new
SET
	[sys_file_name] = cdc.[sys_file_name]
	,[sys_file_ln] = cdc.[sys_file_ln]
	,[sys_extract_dt] = cdc.[sys_extract_dt]
	,[sys_cdc_dt] = cdc.[sys_cdc_dt]
	,[sys_cdc_scn] = cdc.[sys_cdc_scn]
	,[sys_cdc_operation_type] = cdc.[sys_cdc_operation_type]
	,[sys_cdc_before_after] = cdc.[sys_cdc_before_after]
	,[sys_line_modified_ind] = cdc.[sys_line_modified_ind]
	,[scmcu] = cdc.[scmcu]
	,[scmcu_conv] = cdc.[scmcu_conv]
	,[scctr] = cdc.[scctr]
	,[scaddz] = cdc.[scaddz]
	,[scaddz_conv] = cdc.[scaddz_conv]
	,[sceftj] = cdc.[sceftj]
	,[sceftj_conv] = cdc.[sceftj_conv]
	,[scexdj] = cdc.[scexdj]
	,[scexdj_conv] = cdc.[scexdj_conv]
	,[scdstn] = cdc.[scdstn]
	,[scum] = cdc.[scum]
	,[scy55char1] = cdc.[scy55char1]
	,[scy55char1_conv] = cdc.[scy55char1_conv]
	,[scy55char2] = cdc.[scy55char2]
	,[scy55char2_conv] = cdc.[scy55char2_conv]
	,[scy55strg1] = cdc.[scy55strg1]
	,[scy55strg1_conv] = cdc.[scy55strg1_conv]
	,[scy55strg2] = cdc.[scy55strg2]
	,[scy55strg2_conv] = cdc.[scy55strg2_conv]
	,[scy55amnt1] = cdc.[scy55amnt1]
	,[scy55amnt1_conv] = cdc.[scy55amnt1_conv]
	,[scy55amnt2] = cdc.[scy55amnt2]
	,[scy55amnt2_conv] = cdc.[scy55amnt2_conv]
	,[scy55time1] = cdc.[scy55time1]
	,[scy55time2] = cdc.[scy55time2]
	,[scy55date1] = cdc.[scy55date1]
	,[scy55date1_conv] = cdc.[scy55date1_conv]
	,[scy55date2] = cdc.[scy55date2]
	,[scy55date2_conv] = cdc.[scy55date2_conv]
	,[scurrf] = cdc.[scurrf]
	,[scurrf_conv] = cdc.[scurrf_conv]
	,[scurdt] = cdc.[scurdt]
	,[scurdt_conv] = cdc.[scurdt_conv]
	,[scurcd] = cdc.[scurcd]
	,[scurcd_conv] = cdc.[scurcd_conv]
	,[scurab] = cdc.[scurab]
	,[scurab_conv] = cdc.[scurab_conv]
	,[scurat] = cdc.[scurat]
	,[scurat_conv] = cdc.[scurat_conv]
	,[scuser] = cdc.[scuser]
	,[scuser_conv] = cdc.[scuser_conv]
	,[scpid] = cdc.[scpid]
	,[scpid_conv] = cdc.[scpid_conv]
	,[scjobn] = cdc.[scjobn]
	,[scjobn_conv] = cdc.[scjobn_conv]
	,[scupmj] = cdc.[scupmj]
	,[scupmj_conv] = cdc.[scupmj_conv]
	,[scupmt] = cdc.[scupmt] -- exclude distribution column
FROM stg_jde.tmp_upsert_f554922_cdc cdc
WHERE
    rep_jde.f554922_new.sys_integration_id = cdc.sys_integration_id
    AND rep_jde.f554922_new.sys_cdc_scn < cdc.sys_cdc_scn 
OPTION ( LABEL = 'UPDATE_rep_jde.f554922_new AF:{{ task_instance_key_str }}' ) 
