-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f0010_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,ccco
	,ccco_conv
	,ccname
	,ccname_conv
	,ccaltc
	,ccaltc_conv
	,ccdfyj
	,ccdfyj_conv
	,ccpnc
	,ccdot1
	,ccdot1_conv
	,cccryr
	,cccryc
	,cccryc_conv
	,ccdot2
	,ccdot2_conv
	,ccmcua
	,ccmcua_conv
	,ccmcud
	,ccmcud_conv
	,ccmcuc
	,ccmcuc_conv
	,ccmcub
	,ccmcub_conv
	,ccdprc
	,ccdprc_conv
	,ccbktx
	,ccbktx_conv
	,cctxbm
	,cctxbo
	,ccnwxj
	,ccnwxj_conv
	,ccglie
	,ccabin
	,ccabin_conv
	,cccald
	,ccdtpn
	,ccpnf
	,ccdff
	,cccrcd
	,cccrcd_conv
	,ccsmi
	,ccsmi_conv
	,ccsmu
	,ccsmu_conv
	,ccsms
	,ccsms_conv
	,ccdnlt
	,ccdnlt_conv
	,ccstmt
	,ccatcs
	,ccatcs_conv
	,ccalgm
	,ccagem
	,cccrdy
	,ccagr1
	,ccagr2
	,ccagr3
	,ccagr4
	,ccagr5
	,ccagr6
	,ccagr7
	,ccfry
	,ccfrp
	,ccnnp
	,ccfp
	,ccfp_conv
	,ccage
	,ccdag
	,ccdag_conv
	,ccarpn
	,ccappn
	,ccarfj
	,ccarfj_conv
	,ccapfj
	,ccapfj_conv
	,ccan8
	,ccsgbk
	,ccsgbk_conv
	,ccptco
	,ccptco_conv
	,ccx1
	,ccx1_conv
	,ccx2
	,ccx2_conv
	,ccuser
	,ccuser_conv
	,ccpid
	,ccpid_conv
	,ccupmj
	,ccupmj_conv
	,ccjobn
	,ccjobn_conv
	,ccupmt
	,cctsid
	,cctsco
	,cctsco_conv
	,ccthco
	,ccan8c
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.ccco
	,cdc.ccco_conv
	,cdc.ccname
	,cdc.ccname_conv
	,cdc.ccaltc
	,cdc.ccaltc_conv
	,cdc.ccdfyj
	,cdc.ccdfyj_conv
	,cdc.ccpnc
	,cdc.ccdot1
	,cdc.ccdot1_conv
	,cdc.cccryr
	,cdc.cccryc
	,cdc.cccryc_conv
	,cdc.ccdot2
	,cdc.ccdot2_conv
	,cdc.ccmcua
	,cdc.ccmcua_conv
	,cdc.ccmcud
	,cdc.ccmcud_conv
	,cdc.ccmcuc
	,cdc.ccmcuc_conv
	,cdc.ccmcub
	,cdc.ccmcub_conv
	,cdc.ccdprc
	,cdc.ccdprc_conv
	,cdc.ccbktx
	,cdc.ccbktx_conv
	,cdc.cctxbm
	,cdc.cctxbo
	,cdc.ccnwxj
	,cdc.ccnwxj_conv
	,cdc.ccglie
	,cdc.ccabin
	,cdc.ccabin_conv
	,cdc.cccald
	,cdc.ccdtpn
	,cdc.ccpnf
	,cdc.ccdff
	,cdc.cccrcd
	,cdc.cccrcd_conv
	,cdc.ccsmi
	,cdc.ccsmi_conv
	,cdc.ccsmu
	,cdc.ccsmu_conv
	,cdc.ccsms
	,cdc.ccsms_conv
	,cdc.ccdnlt
	,cdc.ccdnlt_conv
	,cdc.ccstmt
	,cdc.ccatcs
	,cdc.ccatcs_conv
	,cdc.ccalgm
	,cdc.ccagem
	,cdc.cccrdy
	,cdc.ccagr1
	,cdc.ccagr2
	,cdc.ccagr3
	,cdc.ccagr4
	,cdc.ccagr5
	,cdc.ccagr6
	,cdc.ccagr7
	,cdc.ccfry
	,cdc.ccfrp
	,cdc.ccnnp
	,cdc.ccfp
	,cdc.ccfp_conv
	,cdc.ccage
	,cdc.ccdag
	,cdc.ccdag_conv
	,cdc.ccarpn
	,cdc.ccappn
	,cdc.ccarfj
	,cdc.ccarfj_conv
	,cdc.ccapfj
	,cdc.ccapfj_conv
	,cdc.ccan8
	,cdc.ccsgbk
	,cdc.ccsgbk_conv
	,cdc.ccptco
	,cdc.ccptco_conv
	,cdc.ccx1
	,cdc.ccx1_conv
	,cdc.ccx2
	,cdc.ccx2_conv
	,cdc.ccuser
	,cdc.ccuser_conv
	,cdc.ccpid
	,cdc.ccpid_conv
	,cdc.ccupmj
	,cdc.ccupmj_conv
	,cdc.ccjobn
	,cdc.ccjobn_conv
	,cdc.ccupmt
	,cdc.cctsid
	,cdc.cctsco
	,cdc.cctsco_conv
	,cdc.ccthco
	,cdc.ccan8c
FROM stg_jde_qat.tmp_upsert_f0010_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f0010_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f0010_new AF:{{ task_instance_key_str }}' ) 