-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f0111_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,wwan8
	,wwidln
	,wwidln_conv
	,wwdss5
	,wwmlnm
	,wwmlnm_conv
	,wwattl
	,wwattl_conv
	,wwrem1
	,wwrem1_conv
	,wwslnm
	,wwslnm_conv
	,wwalph
	,wwalph_conv
	,wwdc
	,wwdc_conv
	,wwgnnm
	,wwgnnm_conv
	,wwmdnm
	,wwmdnm_conv
	,wwsrnm
	,wwsrnm_conv
	,wwtyc
	,www001
	,www002
	,www003
	,www004
	,www005
	,www006
	,www007
	,www008
	,www009
	,www010
	,wwmln1
	,wwmln1_conv
	,wwalp1
	,wwalp1_conv
	,wwuser
	,wwuser_conv
	,wwpid
	,wwpid_conv
	,wwupmj
	,wwupmj_conv
	,wwjobn
	,wwjobn_conv
	,wwupmt
	,wwntyp
	,wwnick
	,wwnick_conv
	,wwgend
	,wwddate
	,wwdmon
	,wwdyr
	,wwdyr_conv
	,wwwn001
	,wwwn002
	,wwwn003
	,wwwn004
	,wwwn005
	,wwwn006
	,wwwn007
	,wwwn008
	,wwwn009
	,wwwn010
	,wwfuco
	,wwpcm
	,wwpcf
	,wwpcf_conv
	,wwactin
	,wwactin_conv
	,wwcfrguid
	,wwcfrguid_conv
	,wwsyncs
	,wwcaad
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.wwan8
	,cdc.wwidln
	,cdc.wwidln_conv
	,cdc.wwdss5
	,cdc.wwmlnm
	,cdc.wwmlnm_conv
	,cdc.wwattl
	,cdc.wwattl_conv
	,cdc.wwrem1
	,cdc.wwrem1_conv
	,cdc.wwslnm
	,cdc.wwslnm_conv
	,cdc.wwalph
	,cdc.wwalph_conv
	,cdc.wwdc
	,cdc.wwdc_conv
	,cdc.wwgnnm
	,cdc.wwgnnm_conv
	,cdc.wwmdnm
	,cdc.wwmdnm_conv
	,cdc.wwsrnm
	,cdc.wwsrnm_conv
	,cdc.wwtyc
	,cdc.www001
	,cdc.www002
	,cdc.www003
	,cdc.www004
	,cdc.www005
	,cdc.www006
	,cdc.www007
	,cdc.www008
	,cdc.www009
	,cdc.www010
	,cdc.wwmln1
	,cdc.wwmln1_conv
	,cdc.wwalp1
	,cdc.wwalp1_conv
	,cdc.wwuser
	,cdc.wwuser_conv
	,cdc.wwpid
	,cdc.wwpid_conv
	,cdc.wwupmj
	,cdc.wwupmj_conv
	,cdc.wwjobn
	,cdc.wwjobn_conv
	,cdc.wwupmt
	,cdc.wwntyp
	,cdc.wwnick
	,cdc.wwnick_conv
	,cdc.wwgend
	,cdc.wwddate
	,cdc.wwdmon
	,cdc.wwdyr
	,cdc.wwdyr_conv
	,cdc.wwwn001
	,cdc.wwwn002
	,cdc.wwwn003
	,cdc.wwwn004
	,cdc.wwwn005
	,cdc.wwwn006
	,cdc.wwwn007
	,cdc.wwwn008
	,cdc.wwwn009
	,cdc.wwwn010
	,cdc.wwfuco
	,cdc.wwpcm
	,cdc.wwpcf
	,cdc.wwpcf_conv
	,cdc.wwactin
	,cdc.wwactin_conv
	,cdc.wwcfrguid
	,cdc.wwcfrguid_conv
	,cdc.wwsyncs
	,cdc.wwcaad
FROM stg_jde_qat.tmp_upsert_f0111_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f0111_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f0111_new AF:{{ task_instance_key_str }}' ) 