-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f1217_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,wrnumb
	,wrctr
	,wrcoown
	,wrcoown_conv
	,wrmmcu
	,wrmmcu_conv
	,wrdoco
	,wrdcto
	,wrkcoo
	,wrkcoo_conv
	,wrlnid
	,wrlnid_conv
	,wrordj
	,wrordj_conv
	,wrshpj
	,wrshpj_conv
	,wraddj
	,wraddj_conv
	,wrshan
	,wrpa8
	,wrslsm
	,wranob
	,wrrorn
	,wrrorn_conv
	,wrrcto
	,wrstrx
	,wrstrx_conv
	,wrvend
	,wrvend_conv
	,wroorn
	,wroorn_conv
	,wrocto
	,wrokco
	,wrokco_conv
	,wrsfxo
	,wrsfxo_conv
	,wrogno
	,wrogno_conv
	,wrprodf
	,wrprodm
	,wrprodc
	,wrcmod
	,wrcmod_conv
	,wrsyem
	,wrsyem_conv
	,wrvinnu
	,wrvinnu_conv
	,wrrefn
	,wrrefn_conv
	,wrze01
	,wrze02
	,wrze03
	,wrze04
	,wrze05
	,wrze06
	,wrze07
	,wrze08
	,wrze09
	,wrze10
	,wrurcd
	,wrurcd_conv
	,wrurdt
	,wrurdt_conv
	,wrurat
	,wrurat_conv
	,wrurab
	,wrurab_conv
	,wrurrf
	,wrurrf_conv
	,wrcrtu
	,wrcrtu_conv
	,wruser
	,wruser_conv
	,wrpid
	,wrpid_conv
	,wrjobn
	,wrjobn_conv
	,wrupmj
	,wrupmj_conv
	,wrupmt
	,wrlotn
	,wrlotn_conv
	,wrlocn
	,wrlocn_conv
	,wrwod
	,wrbrev
	,wrbrev_conv
	,wrefff
	,wrefff_conv
	,wran8dl
	,wran8as
	,wran8as_conv
	,wrtermyn
	,wrtermyn_conv
	,wrsatyp
	,wrinsdte
	,wrinsdte_conv
	,wrmcu
	,wrmcu_conv
	,wrmrryn
	,wrmrryn_conv
	,wrregsts
	,wrvmrs31
	,wrvmrs32
	,wrvmrs34
	,wrvmrs34_conv
	,wran8dr
	,wran8dr_conv
	,wreqpn
	,wreqpn_conv
	,wrmtryn
	,wrmtryn_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.wrnumb
	,cdc.wrctr
	,cdc.wrcoown
	,cdc.wrcoown_conv
	,cdc.wrmmcu
	,cdc.wrmmcu_conv
	,cdc.wrdoco
	,cdc.wrdcto
	,cdc.wrkcoo
	,cdc.wrkcoo_conv
	,cdc.wrlnid
	,cdc.wrlnid_conv
	,cdc.wrordj
	,cdc.wrordj_conv
	,cdc.wrshpj
	,cdc.wrshpj_conv
	,cdc.wraddj
	,cdc.wraddj_conv
	,cdc.wrshan
	,cdc.wrpa8
	,cdc.wrslsm
	,cdc.wranob
	,cdc.wrrorn
	,cdc.wrrorn_conv
	,cdc.wrrcto
	,cdc.wrstrx
	,cdc.wrstrx_conv
	,cdc.wrvend
	,cdc.wrvend_conv
	,cdc.wroorn
	,cdc.wroorn_conv
	,cdc.wrocto
	,cdc.wrokco
	,cdc.wrokco_conv
	,cdc.wrsfxo
	,cdc.wrsfxo_conv
	,cdc.wrogno
	,cdc.wrogno_conv
	,cdc.wrprodf
	,cdc.wrprodm
	,cdc.wrprodc
	,cdc.wrcmod
	,cdc.wrcmod_conv
	,cdc.wrsyem
	,cdc.wrsyem_conv
	,cdc.wrvinnu
	,cdc.wrvinnu_conv
	,cdc.wrrefn
	,cdc.wrrefn_conv
	,cdc.wrze01
	,cdc.wrze02
	,cdc.wrze03
	,cdc.wrze04
	,cdc.wrze05
	,cdc.wrze06
	,cdc.wrze07
	,cdc.wrze08
	,cdc.wrze09
	,cdc.wrze10
	,cdc.wrurcd
	,cdc.wrurcd_conv
	,cdc.wrurdt
	,cdc.wrurdt_conv
	,cdc.wrurat
	,cdc.wrurat_conv
	,cdc.wrurab
	,cdc.wrurab_conv
	,cdc.wrurrf
	,cdc.wrurrf_conv
	,cdc.wrcrtu
	,cdc.wrcrtu_conv
	,cdc.wruser
	,cdc.wruser_conv
	,cdc.wrpid
	,cdc.wrpid_conv
	,cdc.wrjobn
	,cdc.wrjobn_conv
	,cdc.wrupmj
	,cdc.wrupmj_conv
	,cdc.wrupmt
	,cdc.wrlotn
	,cdc.wrlotn_conv
	,cdc.wrlocn
	,cdc.wrlocn_conv
	,cdc.wrwod
	,cdc.wrbrev
	,cdc.wrbrev_conv
	,cdc.wrefff
	,cdc.wrefff_conv
	,cdc.wran8dl
	,cdc.wran8as
	,cdc.wran8as_conv
	,cdc.wrtermyn
	,cdc.wrtermyn_conv
	,cdc.wrsatyp
	,cdc.wrinsdte
	,cdc.wrinsdte_conv
	,cdc.wrmcu
	,cdc.wrmcu_conv
	,cdc.wrmrryn
	,cdc.wrmrryn_conv
	,cdc.wrregsts
	,cdc.wrvmrs31
	,cdc.wrvmrs32
	,cdc.wrvmrs34
	,cdc.wrvmrs34_conv
	,cdc.wran8dr
	,cdc.wran8dr_conv
	,cdc.wreqpn
	,cdc.wreqpn_conv
	,cdc.wrmtryn
	,cdc.wrmtryn_conv
FROM stg_jde_qat.tmp_upsert_f1217_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f1217_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f1217_new AF:{{ task_instance_key_str }}' ) 