-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f38010_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,dndmct
	,dndmct_conv
	,dndmcs
	,dndl01
	,dndl01_conv
	,dndl02
	,dndl02_conv
	,dndl03
	,dndl03_conv
	,dnmcu
	,dnmcu_conv
	,dnnwrn
	,dnagrs
	,dnagrs_conv
	,dncman
	,dncadm
	,dnpanm
	,dnpanm_conv
	,dncntd
	,dncntd_conv
	,dndmtc
	,dndmpc
	,dndmsc
	,dneftj
	,dneftj_conv
	,dnexdj
	,dnexdj_conv
	,dnan8
	,dnaagm
	,dnaagm_conv
	,dnaags
	,dnragm
	,dnragm_conv
	,dnrags
	,dncagm
	,dncagm_conv
	,dncags
	,dnpagm
	,dnpagm_conv
	,dnpags
	,dnzd01
	,dnzd02
	,dnzd03
	,dnzd04
	,dnzd05
	,dnzd06
	,dnzd07
	,dnzd08
	,dnzd09
	,dnzd10
	,dnqedt
	,dnqedt_conv
	,dncand
	,dncand_conv
	,dncanr
	,dnupgl
	,dnupgl_conv
	,dnpras
	,dncmoo
	,dncmoo_conv
	,dncnqy
	,dntv01
	,dntv01_conv
	,dntv02
	,dntv02_conv
	,dntv03
	,dntv03_conv
	,dnurcd
	,dnurcd_conv
	,dnurdt
	,dnurdt_conv
	,dnurat
	,dnurat_conv
	,dnurab
	,dnurab_conv
	,dnurrf
	,dnurrf_conv
	,dnuser
	,dnuser_conv
	,dnpid
	,dnpid_conv
	,dnjobn
	,dnjobn_conv
	,dnupmj
	,dnupmj_conv
	,dntday
	,dnrpqt
	,dnrpqt_conv
	,dnqed3
	,dnqed3_conv
	,dnqed2
	,dnqed2_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.dndmct
	,cdc.dndmct_conv
	,cdc.dndmcs
	,cdc.dndl01
	,cdc.dndl01_conv
	,cdc.dndl02
	,cdc.dndl02_conv
	,cdc.dndl03
	,cdc.dndl03_conv
	,cdc.dnmcu
	,cdc.dnmcu_conv
	,cdc.dnnwrn
	,cdc.dnagrs
	,cdc.dnagrs_conv
	,cdc.dncman
	,cdc.dncadm
	,cdc.dnpanm
	,cdc.dnpanm_conv
	,cdc.dncntd
	,cdc.dncntd_conv
	,cdc.dndmtc
	,cdc.dndmpc
	,cdc.dndmsc
	,cdc.dneftj
	,cdc.dneftj_conv
	,cdc.dnexdj
	,cdc.dnexdj_conv
	,cdc.dnan8
	,cdc.dnaagm
	,cdc.dnaagm_conv
	,cdc.dnaags
	,cdc.dnragm
	,cdc.dnragm_conv
	,cdc.dnrags
	,cdc.dncagm
	,cdc.dncagm_conv
	,cdc.dncags
	,cdc.dnpagm
	,cdc.dnpagm_conv
	,cdc.dnpags
	,cdc.dnzd01
	,cdc.dnzd02
	,cdc.dnzd03
	,cdc.dnzd04
	,cdc.dnzd05
	,cdc.dnzd06
	,cdc.dnzd07
	,cdc.dnzd08
	,cdc.dnzd09
	,cdc.dnzd10
	,cdc.dnqedt
	,cdc.dnqedt_conv
	,cdc.dncand
	,cdc.dncand_conv
	,cdc.dncanr
	,cdc.dnupgl
	,cdc.dnupgl_conv
	,cdc.dnpras
	,cdc.dncmoo
	,cdc.dncmoo_conv
	,cdc.dncnqy
	,cdc.dntv01
	,cdc.dntv01_conv
	,cdc.dntv02
	,cdc.dntv02_conv
	,cdc.dntv03
	,cdc.dntv03_conv
	,cdc.dnurcd
	,cdc.dnurcd_conv
	,cdc.dnurdt
	,cdc.dnurdt_conv
	,cdc.dnurat
	,cdc.dnurat_conv
	,cdc.dnurab
	,cdc.dnurab_conv
	,cdc.dnurrf
	,cdc.dnurrf_conv
	,cdc.dnuser
	,cdc.dnuser_conv
	,cdc.dnpid
	,cdc.dnpid_conv
	,cdc.dnjobn
	,cdc.dnjobn_conv
	,cdc.dnupmj
	,cdc.dnupmj_conv
	,cdc.dntday
	,cdc.dnrpqt
	,cdc.dnrpqt_conv
	,cdc.dnqed3
	,cdc.dnqed3_conv
	,cdc.dnqed2
	,cdc.dnqed2_conv
FROM stg_jde_qat.tmp_upsert_f38010_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f38010_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f38010_new AF:{{ task_instance_key_str }}' ) 