-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f4071_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,atast
	,atprgr
	,atcpgp
	,atsdgr
	,atprfr
	,atlbt
	,atglc
	,atglc_conv
	,atsbif
	,atacnt
	,atlnty
	,atlnty_conv
	,atmded
	,atmded_conv
	,atabas
	,atabas_conv
	,atolvl
	,attxb
	,atpa01
	,atpa02
	,atpa02_conv
	,atpa03
	,atpa03_conv
	,atpa04
	,atpa05
	,atpa05_conv
	,aturcd
	,aturcd_conv
	,aturdt
	,aturdt_conv
	,aturat
	,aturat_conv
	,aturab
	,aturab_conv
	,aturrf
	,aturrf_conv
	,atenbm
	,atenbm_conv
	,atsrflag
	,atsrflag_conv
	,atusadj
	,atusadj_conv
	,atatier
	,atbtier
	,atbnad
	,ataprp1
	,ataprp2
	,ataprp3
	,ataprp4
	,ataprp5
	,ataprp6
	,atadjgrp
	,atmeadj
	,atmeadj_conv
	,atpdcl
	,atuser
	,atuser_conv
	,atpid
	,atpid_conv
	,atjobn
	,atjobn_conv
	,atupmj
	,atupmj_conv
	,attday
	,atdidp
	,atdidp_conv
	,atpmtn
	,atpmtn_conv
	,atphst
	,atphst_conv
	,atpa06
	,atpa06_conv
	,atpa07
	,atpa07_conv
	,atpa08
	,atpa08_conv
	,atpa09
	,atpa09_conv
	,atpa10
	,atpa10_conv
	,atefcn
	,atefcn_conv
	,ataptype
	,atmoadj
	,atmoadj_conv
	,atplgrp
	,atexcpl
	,atexcpl_conv
	,atupmx
	,atupmx_conv
	,atmnmxaj
	,atmnmxrl
	,attstrsnm
	,attstrsnm_conv
	,atadjqty
	,atadjqty_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.atast
	,cdc.atprgr
	,cdc.atcpgp
	,cdc.atsdgr
	,cdc.atprfr
	,cdc.atlbt
	,cdc.atglc
	,cdc.atglc_conv
	,cdc.atsbif
	,cdc.atacnt
	,cdc.atlnty
	,cdc.atlnty_conv
	,cdc.atmded
	,cdc.atmded_conv
	,cdc.atabas
	,cdc.atabas_conv
	,cdc.atolvl
	,cdc.attxb
	,cdc.atpa01
	,cdc.atpa02
	,cdc.atpa02_conv
	,cdc.atpa03
	,cdc.atpa03_conv
	,cdc.atpa04
	,cdc.atpa05
	,cdc.atpa05_conv
	,cdc.aturcd
	,cdc.aturcd_conv
	,cdc.aturdt
	,cdc.aturdt_conv
	,cdc.aturat
	,cdc.aturat_conv
	,cdc.aturab
	,cdc.aturab_conv
	,cdc.aturrf
	,cdc.aturrf_conv
	,cdc.atenbm
	,cdc.atenbm_conv
	,cdc.atsrflag
	,cdc.atsrflag_conv
	,cdc.atusadj
	,cdc.atusadj_conv
	,cdc.atatier
	,cdc.atbtier
	,cdc.atbnad
	,cdc.ataprp1
	,cdc.ataprp2
	,cdc.ataprp3
	,cdc.ataprp4
	,cdc.ataprp5
	,cdc.ataprp6
	,cdc.atadjgrp
	,cdc.atmeadj
	,cdc.atmeadj_conv
	,cdc.atpdcl
	,cdc.atuser
	,cdc.atuser_conv
	,cdc.atpid
	,cdc.atpid_conv
	,cdc.atjobn
	,cdc.atjobn_conv
	,cdc.atupmj
	,cdc.atupmj_conv
	,cdc.attday
	,cdc.atdidp
	,cdc.atdidp_conv
	,cdc.atpmtn
	,cdc.atpmtn_conv
	,cdc.atphst
	,cdc.atphst_conv
	,cdc.atpa06
	,cdc.atpa06_conv
	,cdc.atpa07
	,cdc.atpa07_conv
	,cdc.atpa08
	,cdc.atpa08_conv
	,cdc.atpa09
	,cdc.atpa09_conv
	,cdc.atpa10
	,cdc.atpa10_conv
	,cdc.atefcn
	,cdc.atefcn_conv
	,cdc.ataptype
	,cdc.atmoadj
	,cdc.atmoadj_conv
	,cdc.atplgrp
	,cdc.atexcpl
	,cdc.atexcpl_conv
	,cdc.atupmx
	,cdc.atupmx_conv
	,cdc.atmnmxaj
	,cdc.atmnmxrl
	,cdc.attstrsnm
	,cdc.attstrsnm_conv
	,cdc.atadjqty
	,cdc.atadjqty_conv
FROM stg_jde_qat.tmp_upsert_f4071_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f4071_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f4071_new AF:{{ task_instance_key_str }}' ) 