-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f4074_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,aldoco
	,aldcto
	,alkcoo
	,alkcoo_conv
	,alsfxo
	,alsfxo_conv
	,allnid
	,allnid_conv
	,alakid
	,alsrcfd
	,aloseq
	,aloseq_conv
	,alsubseq
	,alsubseq_conv
	,altier
	,alasn
	,alast
	,alitm
	,alan8
	,alcrcd
	,alcrcd_conv
	,aluom
	,almnq
	,almnq_conv
	,alledg
	,alfrmn
	,albscd
	,alfvtr
	,alfvtr_conv
	,alabas
	,alabas_conv
	,aluprc
	,aluprc_conv
	,alfup
	,alfup_conv
	,alglc
	,alglc_conv
	,alarsn
	,alacnt
	,alsbif
	,almded
	,almded_conv
	,alprov
	,alprov_conv
	,alatid
	,aligid
	,aligid_conv
	,alcgid
	,alcgid_conv
	,alogid
	,alogid_conv
	,alanps
	,alanps_conv
	,albsdval
	,albsdval_conv
	,alsrflag
	,alsrflag_conv
	,aladjcal
	,aladjcal_conv
	,alnbrord
	,alnbrord_conv
	,aluomvid
	,alolvl
	,aladjsts
	,aladjref
	,aladjref_conv
	,alaccan8
	,albnad
	,aladjgrp
	,almeadj
	,almeadj_conv
	,alfvum
	,alpdcl
	,alcfgid
	,alcfgid_conv
	,alcfgcid
	,alcfgcid_conv
	,alaprp1
	,alaprp2
	,alaprp3
	,alaprp4
	,alaprp5
	,alaprp6
	,alndpi
	,alndpi_conv
	,aluser
	,aluser_conv
	,alpid
	,alpid_conv
	,aljobn
	,aljobn_conv
	,alupmj
	,alupmj_conv
	,altday
	,alpmtn
	,alpmtn_conv
	,alrulename
	,alrulename_conv
	,alpa04
	,aladjqty
	,aladjqty_conv
	,alqtypy
	,alqtypy_conv
	,alstprcf
	,alstprcf_conv
	,altstrsnm
	,altstrsnm_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.aldoco
	,cdc.aldcto
	,cdc.alkcoo
	,cdc.alkcoo_conv
	,cdc.alsfxo
	,cdc.alsfxo_conv
	,cdc.allnid
	,cdc.allnid_conv
	,cdc.alakid
	,cdc.alsrcfd
	,cdc.aloseq
	,cdc.aloseq_conv
	,cdc.alsubseq
	,cdc.alsubseq_conv
	,cdc.altier
	,cdc.alasn
	,cdc.alast
	,cdc.alitm
	,cdc.alan8
	,cdc.alcrcd
	,cdc.alcrcd_conv
	,cdc.aluom
	,cdc.almnq
	,cdc.almnq_conv
	,cdc.alledg
	,cdc.alfrmn
	,cdc.albscd
	,cdc.alfvtr
	,cdc.alfvtr_conv
	,cdc.alabas
	,cdc.alabas_conv
	,cdc.aluprc
	,cdc.aluprc_conv
	,cdc.alfup
	,cdc.alfup_conv
	,cdc.alglc
	,cdc.alglc_conv
	,cdc.alarsn
	,cdc.alacnt
	,cdc.alsbif
	,cdc.almded
	,cdc.almded_conv
	,cdc.alprov
	,cdc.alprov_conv
	,cdc.alatid
	,cdc.aligid
	,cdc.aligid_conv
	,cdc.alcgid
	,cdc.alcgid_conv
	,cdc.alogid
	,cdc.alogid_conv
	,cdc.alanps
	,cdc.alanps_conv
	,cdc.albsdval
	,cdc.albsdval_conv
	,cdc.alsrflag
	,cdc.alsrflag_conv
	,cdc.aladjcal
	,cdc.aladjcal_conv
	,cdc.alnbrord
	,cdc.alnbrord_conv
	,cdc.aluomvid
	,cdc.alolvl
	,cdc.aladjsts
	,cdc.aladjref
	,cdc.aladjref_conv
	,cdc.alaccan8
	,cdc.albnad
	,cdc.aladjgrp
	,cdc.almeadj
	,cdc.almeadj_conv
	,cdc.alfvum
	,cdc.alpdcl
	,cdc.alcfgid
	,cdc.alcfgid_conv
	,cdc.alcfgcid
	,cdc.alcfgcid_conv
	,cdc.alaprp1
	,cdc.alaprp2
	,cdc.alaprp3
	,cdc.alaprp4
	,cdc.alaprp5
	,cdc.alaprp6
	,cdc.alndpi
	,cdc.alndpi_conv
	,cdc.aluser
	,cdc.aluser_conv
	,cdc.alpid
	,cdc.alpid_conv
	,cdc.aljobn
	,cdc.aljobn_conv
	,cdc.alupmj
	,cdc.alupmj_conv
	,cdc.altday
	,cdc.alpmtn
	,cdc.alpmtn_conv
	,cdc.alrulename
	,cdc.alrulename_conv
	,cdc.alpa04
	,cdc.aladjqty
	,cdc.aladjqty_conv
	,cdc.alqtypy
	,cdc.alqtypy_conv
	,cdc.alstprcf
	,cdc.alstprcf_conv
	,cdc.altstrsnm
	,cdc.altstrsnm_conv
FROM stg_jde_qat.tmp_upsert_f4074_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f4074_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f4074_new AF:{{ task_instance_key_str }}' ) 