-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f41022_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,pnmcu
	,pnmcu_conv
	,pnitm
	,pnstvl
	,pnstvl_conv
	,pnbum0
	,pnlrfg
	,pnlrfg_conv
	,pnhcor
	,pnhcor_conv
	,pnacor
	,pnacor_conv
	,pnabbl
	,pnabbl_conv
	,pnatwh
	,pnatwh_conv
	,pnrplt
	,pnbcat
	,pnfcat
	,pnrecd
	,pnrecd_conv
	,pnurcd
	,pnurcd_conv
	,pnurat
	,pnurat_conv
	,pnurab
	,pnurab_conv
	,pnurrf
	,pnurrf_conv
	,pnurdt
	,pnurdt_conv
	,pnuser
	,pnuser_conv
	,pnpid
	,pnpid_conv
	,pnjobn
	,pnjobn_conv
	,pnupmj
	,pnupmj_conv
	,pntday
	,pnrtob
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.pnmcu
	,cdc.pnmcu_conv
	,cdc.pnitm
	,cdc.pnstvl
	,cdc.pnstvl_conv
	,cdc.pnbum0
	,cdc.pnlrfg
	,cdc.pnlrfg_conv
	,cdc.pnhcor
	,cdc.pnhcor_conv
	,cdc.pnacor
	,cdc.pnacor_conv
	,cdc.pnabbl
	,cdc.pnabbl_conv
	,cdc.pnatwh
	,cdc.pnatwh_conv
	,cdc.pnrplt
	,cdc.pnbcat
	,cdc.pnfcat
	,cdc.pnrecd
	,cdc.pnrecd_conv
	,cdc.pnurcd
	,cdc.pnurcd_conv
	,cdc.pnurat
	,cdc.pnurat_conv
	,cdc.pnurab
	,cdc.pnurab_conv
	,cdc.pnurrf
	,cdc.pnurrf_conv
	,cdc.pnurdt
	,cdc.pnurdt_conv
	,cdc.pnuser
	,cdc.pnuser_conv
	,cdc.pnpid
	,cdc.pnpid_conv
	,cdc.pnjobn
	,cdc.pnjobn_conv
	,cdc.pnupmj
	,cdc.pnupmj_conv
	,cdc.pntday
	,cdc.pnrtob
FROM stg_jde_qat.tmp_upsert_f41022_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f41022_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f41022_new AF:{{ task_instance_key_str }}' ) 