-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f41061_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,cbmcu
	,cbmcu_conv
	,cban8
	,cbitm
	,cblitm
	,cblitm_conv
	,cbaitm
	,cbaitm_conv
	,cbcatn
	,cbdmct
	,cbdmct_conv
	,cbdmcs
	,cbkcoo
	,cbkcoo_conv
	,cbdoco
	,cbdcto
	,cblnid
	,cblnid_conv
	,cbcrcd
	,cbcrcd_conv
	,cbuom
	,cbprrc
	,cbprrc_conv
	,cbuorg
	,cbuorg_conv
	,cbeftj
	,cbeftj_conv
	,cbexdj
	,cbexdj_conv
	,cbuser
	,cbuser_conv
	,cbpid
	,cbpid_conv
	,cbjobn
	,cbjobn_conv
	,cbupmj
	,cbupmj_conv
	,cbtday
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.cbmcu
	,cdc.cbmcu_conv
	,cdc.cban8
	,cdc.cbitm
	,cdc.cblitm
	,cdc.cblitm_conv
	,cdc.cbaitm
	,cdc.cbaitm_conv
	,cdc.cbcatn
	,cdc.cbdmct
	,cdc.cbdmct_conv
	,cdc.cbdmcs
	,cdc.cbkcoo
	,cdc.cbkcoo_conv
	,cdc.cbdoco
	,cdc.cbdcto
	,cdc.cblnid
	,cdc.cblnid_conv
	,cdc.cbcrcd
	,cdc.cbcrcd_conv
	,cdc.cbuom
	,cdc.cbprrc
	,cdc.cbprrc_conv
	,cdc.cbuorg
	,cdc.cbuorg_conv
	,cdc.cbeftj
	,cdc.cbeftj_conv
	,cdc.cbexdj
	,cdc.cbexdj_conv
	,cdc.cbuser
	,cdc.cbuser_conv
	,cdc.cbpid
	,cdc.cbpid_conv
	,cdc.cbjobn
	,cdc.cbjobn_conv
	,cdc.cbupmj
	,cdc.cbupmj_conv
	,cdc.cbtday
FROM stg_jde_qat.tmp_upsert_f41061_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f41061_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f41061_new AF:{{ task_instance_key_str }}' ) 