-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f4104_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,ivan8
	,ivxrt
	,ivitm
	,ivexdj
	,ivexdj_conv
	,iveftj
	,iveftj_conv
	,ivmcu
	,ivmcu_conv
	,ivcitm
	,ivcitm_conv
	,ivdsc1
	,ivdsc1_conv
	,ivdsc2
	,ivdsc2_conv
	,ivaln
	,ivaln_conv
	,ivlitm
	,ivlitm_conv
	,ivaitm
	,ivaitm_conv
	,ivurcd
	,ivurcd_conv
	,ivurdt
	,ivurdt_conv
	,ivurat
	,ivurat_conv
	,ivurab
	,ivurab_conv
	,ivurrf
	,ivurrf_conv
	,ivuser
	,ivuser_conv
	,ivpid
	,ivpid_conv
	,ivjobn
	,ivjobn_conv
	,ivupmj
	,ivupmj_conv
	,ivtday
	,ivrato
	,ivrato_conv
	,ivapsp
	,ivapsp_conv
	,ividem
	,ividem_conv
	,ivapss
	,ivapss_conv
	,ivcirv
	,ivcirv_conv
	,ivadind
	,ivbpind
	,ivcardno
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.ivan8
	,cdc.ivxrt
	,cdc.ivitm
	,cdc.ivexdj
	,cdc.ivexdj_conv
	,cdc.iveftj
	,cdc.iveftj_conv
	,cdc.ivmcu
	,cdc.ivmcu_conv
	,cdc.ivcitm
	,cdc.ivcitm_conv
	,cdc.ivdsc1
	,cdc.ivdsc1_conv
	,cdc.ivdsc2
	,cdc.ivdsc2_conv
	,cdc.ivaln
	,cdc.ivaln_conv
	,cdc.ivlitm
	,cdc.ivlitm_conv
	,cdc.ivaitm
	,cdc.ivaitm_conv
	,cdc.ivurcd
	,cdc.ivurcd_conv
	,cdc.ivurdt
	,cdc.ivurdt_conv
	,cdc.ivurat
	,cdc.ivurat_conv
	,cdc.ivurab
	,cdc.ivurab_conv
	,cdc.ivurrf
	,cdc.ivurrf_conv
	,cdc.ivuser
	,cdc.ivuser_conv
	,cdc.ivpid
	,cdc.ivpid_conv
	,cdc.ivjobn
	,cdc.ivjobn_conv
	,cdc.ivupmj
	,cdc.ivupmj_conv
	,cdc.ivtday
	,cdc.ivrato
	,cdc.ivrato_conv
	,cdc.ivapsp
	,cdc.ivapsp_conv
	,cdc.ividem
	,cdc.ividem_conv
	,cdc.ivapss
	,cdc.ivapss_conv
	,cdc.ivcirv
	,cdc.ivcirv_conv
	,cdc.ivadind
	,cdc.ivbpind
	,cdc.ivcardno
FROM stg_jde_qat.tmp_upsert_f4104_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f4104_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f4104_new AF:{{ task_instance_key_str }}' ) 