-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f41112_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,indct
	,infy
	,infy_conv
	,inctry
	,initm
	,inlitm
	,inlitm_conv
	,inaitm
	,inaitm_conv
	,inmcu
	,inmcu_conv
	,inlocn
	,inlocn_conv
	,inlotn
	,inlotn_conv
	,inglpt
	,inan8
	,inshan
	,innq01
	,innq01_conv
	,innq02
	,innq02_conv
	,innq03
	,innq03_conv
	,innq04
	,innq04_conv
	,innq05
	,innq05_conv
	,innq06
	,innq06_conv
	,innq07
	,innq07_conv
	,innq08
	,innq08_conv
	,innq09
	,innq09_conv
	,innq10
	,innq10_conv
	,innq11
	,innq11_conv
	,innq12
	,innq12_conv
	,innq13
	,innq13_conv
	,innq14
	,innq14_conv
	,inan01
	,inan01_conv
	,inan02
	,inan02_conv
	,inan03
	,inan03_conv
	,inan04
	,inan04_conv
	,inan05
	,inan05_conv
	,inan06
	,inan06_conv
	,inan07
	,inan07_conv
	,inan08
	,inan08_conv
	,inan09
	,inan09_conv
	,inan10
	,inan10_conv
	,inan11
	,inan11_conv
	,inan12
	,inan12_conv
	,inan13
	,inan13_conv
	,inan14
	,inan14_conv
	,incuma
	,incuma_conv
	,incmqt
	,incmqt_conv
	,inaisl
	,inaisl_conv
	,inbin
	,inbin_conv
	,intday
	,inuser
	,inuser_conv
	,inpid
	,inpid_conv
	,inupmj
	,inupmj_conv
	,injobn
	,injobn_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.indct
	,cdc.infy
	,cdc.infy_conv
	,cdc.inctry
	,cdc.initm
	,cdc.inlitm
	,cdc.inlitm_conv
	,cdc.inaitm
	,cdc.inaitm_conv
	,cdc.inmcu
	,cdc.inmcu_conv
	,cdc.inlocn
	,cdc.inlocn_conv
	,cdc.inlotn
	,cdc.inlotn_conv
	,cdc.inglpt
	,cdc.inan8
	,cdc.inshan
	,cdc.innq01
	,cdc.innq01_conv
	,cdc.innq02
	,cdc.innq02_conv
	,cdc.innq03
	,cdc.innq03_conv
	,cdc.innq04
	,cdc.innq04_conv
	,cdc.innq05
	,cdc.innq05_conv
	,cdc.innq06
	,cdc.innq06_conv
	,cdc.innq07
	,cdc.innq07_conv
	,cdc.innq08
	,cdc.innq08_conv
	,cdc.innq09
	,cdc.innq09_conv
	,cdc.innq10
	,cdc.innq10_conv
	,cdc.innq11
	,cdc.innq11_conv
	,cdc.innq12
	,cdc.innq12_conv
	,cdc.innq13
	,cdc.innq13_conv
	,cdc.innq14
	,cdc.innq14_conv
	,cdc.inan01
	,cdc.inan01_conv
	,cdc.inan02
	,cdc.inan02_conv
	,cdc.inan03
	,cdc.inan03_conv
	,cdc.inan04
	,cdc.inan04_conv
	,cdc.inan05
	,cdc.inan05_conv
	,cdc.inan06
	,cdc.inan06_conv
	,cdc.inan07
	,cdc.inan07_conv
	,cdc.inan08
	,cdc.inan08_conv
	,cdc.inan09
	,cdc.inan09_conv
	,cdc.inan10
	,cdc.inan10_conv
	,cdc.inan11
	,cdc.inan11_conv
	,cdc.inan12
	,cdc.inan12_conv
	,cdc.inan13
	,cdc.inan13_conv
	,cdc.inan14
	,cdc.inan14_conv
	,cdc.incuma
	,cdc.incuma_conv
	,cdc.incmqt
	,cdc.incmqt_conv
	,cdc.inaisl
	,cdc.inaisl_conv
	,cdc.inbin
	,cdc.inbin_conv
	,cdc.intday
	,cdc.inuser
	,cdc.inuser_conv
	,cdc.inpid
	,cdc.inpid_conv
	,cdc.inupmj
	,cdc.inupmj_conv
	,cdc.injobn
	,cdc.injobn_conv
FROM stg_jde_qat.tmp_upsert_f41112_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f41112_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f41112_new AF:{{ task_instance_key_str }}' ) 