-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f41500_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,ppmcu
	,ppmcu_conv
	,pptkid
	,pptkid_conv
	,ppdl01
	,ppdl01_conv
	,pptklo
	,pptuse
	,pptkty
	,pptkcp
	,pptkcp_conv
	,ppbum1
	,pphttk
	,pphttk_conv
	,ppprez
	,ppprez_conv
	,ppidte
	,ppidte_conv
	,ppdtcl
	,ppdtcl_conv
	,ppstrp
	,ppdipt
	,ppgamt
	,ppfltr
	,pptexp
	,pptexp_conv
	,pptstu
	,ppcutk
	,ppcutk_conv
	,ppscom
	,pptdia
	,pptdia_conv
	,ppbum2
	,ppthgt
	,ppthgt_conv
	,ppbum3
	,ppstem
	,ppstem_conv
	,ppstpu
	,pprefh
	,pprefh_conv
	,ppbum4
	,pprwgh
	,pprwgh_conv
	,ppbum5
	,ppflht
	,ppflht_conv
	,ppbum6
	,ppunpv
	,ppunpv_conv
	,ppbum7
	,pppipv
	,pppipv_conv
	,ppbum8
	,ppdisv
	,ppdisv_conv
	,ppbum9
	,ppdihr
	,ppdihr_conv
	,ppdhru
	,ppfirh
	,ppfirh_conv
	,ppfrhu
	,pplswn
	,pplswn_conv
	,ppbum0
	,pplosc
	,pplosc_conv
	,pphisc
	,pphisc_conv
	,ppitm
	,ppitml
	,pppcsd
	,pppcsd_conv
	,pprtob
	,ppurcd
	,ppurcd_conv
	,ppurat
	,ppurat_conv
	,ppurab
	,ppurab_conv
	,ppurrf
	,ppurrf_conv
	,ppurdt
	,ppurdt_conv
	,ppuser
	,ppuser_conv
	,pppid
	,pppid_conv
	,ppjobn
	,ppjobn_conv
	,ppupmj
	,ppupmj_conv
	,pptday
	,pptnkn
	,pptnkn_conv
	,ppexpf
	,ppexpf_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.ppmcu
	,cdc.ppmcu_conv
	,cdc.pptkid
	,cdc.pptkid_conv
	,cdc.ppdl01
	,cdc.ppdl01_conv
	,cdc.pptklo
	,cdc.pptuse
	,cdc.pptkty
	,cdc.pptkcp
	,cdc.pptkcp_conv
	,cdc.ppbum1
	,cdc.pphttk
	,cdc.pphttk_conv
	,cdc.ppprez
	,cdc.ppprez_conv
	,cdc.ppidte
	,cdc.ppidte_conv
	,cdc.ppdtcl
	,cdc.ppdtcl_conv
	,cdc.ppstrp
	,cdc.ppdipt
	,cdc.ppgamt
	,cdc.ppfltr
	,cdc.pptexp
	,cdc.pptexp_conv
	,cdc.pptstu
	,cdc.ppcutk
	,cdc.ppcutk_conv
	,cdc.ppscom
	,cdc.pptdia
	,cdc.pptdia_conv
	,cdc.ppbum2
	,cdc.ppthgt
	,cdc.ppthgt_conv
	,cdc.ppbum3
	,cdc.ppstem
	,cdc.ppstem_conv
	,cdc.ppstpu
	,cdc.pprefh
	,cdc.pprefh_conv
	,cdc.ppbum4
	,cdc.pprwgh
	,cdc.pprwgh_conv
	,cdc.ppbum5
	,cdc.ppflht
	,cdc.ppflht_conv
	,cdc.ppbum6
	,cdc.ppunpv
	,cdc.ppunpv_conv
	,cdc.ppbum7
	,cdc.pppipv
	,cdc.pppipv_conv
	,cdc.ppbum8
	,cdc.ppdisv
	,cdc.ppdisv_conv
	,cdc.ppbum9
	,cdc.ppdihr
	,cdc.ppdihr_conv
	,cdc.ppdhru
	,cdc.ppfirh
	,cdc.ppfirh_conv
	,cdc.ppfrhu
	,cdc.pplswn
	,cdc.pplswn_conv
	,cdc.ppbum0
	,cdc.pplosc
	,cdc.pplosc_conv
	,cdc.pphisc
	,cdc.pphisc_conv
	,cdc.ppitm
	,cdc.ppitml
	,cdc.pppcsd
	,cdc.pppcsd_conv
	,cdc.pprtob
	,cdc.ppurcd
	,cdc.ppurcd_conv
	,cdc.ppurat
	,cdc.ppurat_conv
	,cdc.ppurab
	,cdc.ppurab_conv
	,cdc.ppurrf
	,cdc.ppurrf_conv
	,cdc.ppurdt
	,cdc.ppurdt_conv
	,cdc.ppuser
	,cdc.ppuser_conv
	,cdc.pppid
	,cdc.pppid_conv
	,cdc.ppjobn
	,cdc.ppjobn_conv
	,cdc.ppupmj
	,cdc.ppupmj_conv
	,cdc.pptday
	,cdc.pptnkn
	,cdc.pptnkn_conv
	,cdc.ppexpf
	,cdc.ppexpf_conv
FROM stg_jde_qat.tmp_upsert_f41500_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f41500_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f41500_new AF:{{ task_instance_key_str }}' ) 