-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f4215_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,xhshpn
	,xhssts
	,xhpnid
	,xhpnid_conv
	,xhhlcf
	,xhhlcf_conv
	,xhpkcd
	,xhwgq
	,xhwgts
	,xhwgts_conv
	,xhwgtu
	,xhidq1
	,xhid1
	,xhid1_conv
	,xhidq2
	,xhid2
	,xhid2_conv
	,xhmot
	,xhrote
	,xhrote_conv
	,xheqcd
	,xheqin
	,xheqin_conv
	,xheqnb
	,xheqnb_conv
	,xhasna
	,xhasnd
	,xhasnd_conv
	,xhasnt
	,xhmcu
	,xhmcu_conv
	,xhnmcu
	,xhnmcu_conv
	,xhorgn
	,xhsrco
	,xhbpfg
	,xhaexp
	,xhaexp_conv
	,xhecst
	,xhecst_conv
	,xhdrqj
	,xhdrqj_conv
	,xhdrqt
	,xhrsdj
	,xhrsdj_conv
	,xhrsdt
	,xhpdov
	,xhpdov_conv
	,xhan8
	,xhshan
	,xhcty1
	,xhcty1_conv
	,xhadds
	,xhaddz
	,xhaddz_conv
	,xhctr
	,xhzon
	,xhsct1
	,xhsct1_conv
	,xhsct2
	,xhsct2_conv
	,xhsct3
	,xhsct3_conv
	,xhcar1
	,xhcar1_conv
	,xhcar2
	,xhcar2_conv
	,xhcar3
	,xhcar3_conv
	,xhilel
	,xhilel_conv
	,xhfrth
	,xhfrsc
	,xhdllv
	,xhrslt
	,xhbfsd
	,xhbfsd_conv
	,xhdstn
	,xhumd1
	,xhnrts
	,xhuser
	,xhuser_conv
	,xhpid
	,xhpid_conv
	,xhjobn
	,xhjobn_conv
	,xhupmj
	,xhupmj_conv
	,xhtday
	,xhctyo
	,xhctyo_conv
	,xhadso
	,xhadzo
	,xhadzo_conv
	,xhctro
	,xhsc1o
	,xhsc1o_conv
	,xhsc2o
	,xhsc2o_conv
	,xhsc3o
	,xhsc3o_conv
	,xhaetc
	,xhaetc_conv
	,xhetrsc
	,xhetrc
	,xhurcd
	,xhurcd_conv
	,xhurdt
	,xhurdt_conv
	,xhurat
	,xhurat_conv
	,xhurab
	,xhurab_conv
	,xhurrf
	,xhurrf_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.xhshpn
	,cdc.xhssts
	,cdc.xhpnid
	,cdc.xhpnid_conv
	,cdc.xhhlcf
	,cdc.xhhlcf_conv
	,cdc.xhpkcd
	,cdc.xhwgq
	,cdc.xhwgts
	,cdc.xhwgts_conv
	,cdc.xhwgtu
	,cdc.xhidq1
	,cdc.xhid1
	,cdc.xhid1_conv
	,cdc.xhidq2
	,cdc.xhid2
	,cdc.xhid2_conv
	,cdc.xhmot
	,cdc.xhrote
	,cdc.xhrote_conv
	,cdc.xheqcd
	,cdc.xheqin
	,cdc.xheqin_conv
	,cdc.xheqnb
	,cdc.xheqnb_conv
	,cdc.xhasna
	,cdc.xhasnd
	,cdc.xhasnd_conv
	,cdc.xhasnt
	,cdc.xhmcu
	,cdc.xhmcu_conv
	,cdc.xhnmcu
	,cdc.xhnmcu_conv
	,cdc.xhorgn
	,cdc.xhsrco
	,cdc.xhbpfg
	,cdc.xhaexp
	,cdc.xhaexp_conv
	,cdc.xhecst
	,cdc.xhecst_conv
	,cdc.xhdrqj
	,cdc.xhdrqj_conv
	,cdc.xhdrqt
	,cdc.xhrsdj
	,cdc.xhrsdj_conv
	,cdc.xhrsdt
	,cdc.xhpdov
	,cdc.xhpdov_conv
	,cdc.xhan8
	,cdc.xhshan
	,cdc.xhcty1
	,cdc.xhcty1_conv
	,cdc.xhadds
	,cdc.xhaddz
	,cdc.xhaddz_conv
	,cdc.xhctr
	,cdc.xhzon
	,cdc.xhsct1
	,cdc.xhsct1_conv
	,cdc.xhsct2
	,cdc.xhsct2_conv
	,cdc.xhsct3
	,cdc.xhsct3_conv
	,cdc.xhcar1
	,cdc.xhcar1_conv
	,cdc.xhcar2
	,cdc.xhcar2_conv
	,cdc.xhcar3
	,cdc.xhcar3_conv
	,cdc.xhilel
	,cdc.xhilel_conv
	,cdc.xhfrth
	,cdc.xhfrsc
	,cdc.xhdllv
	,cdc.xhrslt
	,cdc.xhbfsd
	,cdc.xhbfsd_conv
	,cdc.xhdstn
	,cdc.xhumd1
	,cdc.xhnrts
	,cdc.xhuser
	,cdc.xhuser_conv
	,cdc.xhpid
	,cdc.xhpid_conv
	,cdc.xhjobn
	,cdc.xhjobn_conv
	,cdc.xhupmj
	,cdc.xhupmj_conv
	,cdc.xhtday
	,cdc.xhctyo
	,cdc.xhctyo_conv
	,cdc.xhadso
	,cdc.xhadzo
	,cdc.xhadzo_conv
	,cdc.xhctro
	,cdc.xhsc1o
	,cdc.xhsc1o_conv
	,cdc.xhsc2o
	,cdc.xhsc2o_conv
	,cdc.xhsc3o
	,cdc.xhsc3o_conv
	,cdc.xhaetc
	,cdc.xhaetc_conv
	,cdc.xhetrsc
	,cdc.xhetrc
	,cdc.xhurcd
	,cdc.xhurcd_conv
	,cdc.xhurdt
	,cdc.xhurdt_conv
	,cdc.xhurat
	,cdc.xhurat_conv
	,cdc.xhurab
	,cdc.xhurab_conv
	,cdc.xhurrf
	,cdc.xhurrf_conv
FROM stg_jde_qat.tmp_upsert_f4215_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f4215_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f4215_new AF:{{ task_instance_key_str }}' ) 