-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f4321_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,pbkcoo
	,pbkcoo_conv
	,pbdoco
	,pbdcto
	,pbsfxo
	,pbsfxo_conv
	,pblnid
	,pblnid_conv
	,pbdlan
	,pbdlan_conv
	,pbcdf1
	,pbcdf1_conv
	,pbcdf2
	,pbcdf2_conv
	,pbcdf3
	,pbcdf3_conv
	,pbcdf4
	,pbcdf4_conv
	,pbvsd
	,pbvsd_conv
	,pbvsw
	,pbvsw_conv
	,pbvsm
	,pbvsm_conv
	,pbcrec
	,pbcrec_conv
	,pbcfro
	,pbcfro_conv
	,pbcfab
	,pbcfab_conv
	,pbcraw
	,pbcraw_conv
	,pbdrqj
	,pbdrqj_conv
	,pbfrdj
	,pbfrdj_conv
	,pblrdj
	,pblrdj_conv
	,pbdoc
	,pbdct
	,pbvrn
	,pbvrn_conv
	,pbvsst
	,pbrjyn
	,pbrjyn_conv
	,pborfd
	,pborfd_conv
	,pblrcj
	,pblrcj_conv
	,pblrqt
	,pblrqt_conv
	,pbuopn
	,pbuopn_conv
	,pburec
	,pburec_conv
	,pbvssp
	,pbshlt
	,pbshlt_conv
	,pbshqt
	,pbshqt_conv
	,pbupc
	,pbupc_conv
	,pburcd
	,pburcd_conv
	,pburdt
	,pburdt_conv
	,pburat
	,pburat_conv
	,pburab
	,pburab_conv
	,pburrf
	,pburrf_conv
	,pbuser
	,pbuser_conv
	,pbpid
	,pbpid_conv
	,pbjobn
	,pbjobn_conv
	,pbupmj
	,pbupmj_conv
	,pbtday
	,pbvlot
	,pbvlot_conv
	,pbrcpd
	,pbrcpd_conv
	,pbmxqt
	,pbmxqt_conv
	,pbmwdh
	,pbltlv
	,pbltlv_conv
	,pbdcap
	,pbda08
	,pbda08_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.pbkcoo
	,cdc.pbkcoo_conv
	,cdc.pbdoco
	,cdc.pbdcto
	,cdc.pbsfxo
	,cdc.pbsfxo_conv
	,cdc.pblnid
	,cdc.pblnid_conv
	,cdc.pbdlan
	,cdc.pbdlan_conv
	,cdc.pbcdf1
	,cdc.pbcdf1_conv
	,cdc.pbcdf2
	,cdc.pbcdf2_conv
	,cdc.pbcdf3
	,cdc.pbcdf3_conv
	,cdc.pbcdf4
	,cdc.pbcdf4_conv
	,cdc.pbvsd
	,cdc.pbvsd_conv
	,cdc.pbvsw
	,cdc.pbvsw_conv
	,cdc.pbvsm
	,cdc.pbvsm_conv
	,cdc.pbcrec
	,cdc.pbcrec_conv
	,cdc.pbcfro
	,cdc.pbcfro_conv
	,cdc.pbcfab
	,cdc.pbcfab_conv
	,cdc.pbcraw
	,cdc.pbcraw_conv
	,cdc.pbdrqj
	,cdc.pbdrqj_conv
	,cdc.pbfrdj
	,cdc.pbfrdj_conv
	,cdc.pblrdj
	,cdc.pblrdj_conv
	,cdc.pbdoc
	,cdc.pbdct
	,cdc.pbvrn
	,cdc.pbvrn_conv
	,cdc.pbvsst
	,cdc.pbrjyn
	,cdc.pbrjyn_conv
	,cdc.pborfd
	,cdc.pborfd_conv
	,cdc.pblrcj
	,cdc.pblrcj_conv
	,cdc.pblrqt
	,cdc.pblrqt_conv
	,cdc.pbuopn
	,cdc.pbuopn_conv
	,cdc.pburec
	,cdc.pburec_conv
	,cdc.pbvssp
	,cdc.pbshlt
	,cdc.pbshlt_conv
	,cdc.pbshqt
	,cdc.pbshqt_conv
	,cdc.pbupc
	,cdc.pbupc_conv
	,cdc.pburcd
	,cdc.pburcd_conv
	,cdc.pburdt
	,cdc.pburdt_conv
	,cdc.pburat
	,cdc.pburat_conv
	,cdc.pburab
	,cdc.pburab_conv
	,cdc.pburrf
	,cdc.pburrf_conv
	,cdc.pbuser
	,cdc.pbuser_conv
	,cdc.pbpid
	,cdc.pbpid_conv
	,cdc.pbjobn
	,cdc.pbjobn_conv
	,cdc.pbupmj
	,cdc.pbupmj_conv
	,cdc.pbtday
	,cdc.pbvlot
	,cdc.pbvlot_conv
	,cdc.pbrcpd
	,cdc.pbrcpd_conv
	,cdc.pbmxqt
	,cdc.pbmxqt_conv
	,cdc.pbmwdh
	,cdc.pbltlv
	,cdc.pbltlv_conv
	,cdc.pbdcap
	,cdc.pbda08
	,cdc.pbda08_conv
FROM stg_jde_qat.tmp_upsert_f4321_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f4321_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f4321_new AF:{{ task_instance_key_str }}' ) 