-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f46011_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,iqmcu
	,iqmcu_conv
	,iqprp6
	,iqitm
	,iquom
	,iqgwid
	,iqgwid_conv
	,iqgdep
	,iqgdep_conv
	,iqghet
	,iqghet_conv
	,iqwium
	,iqgcub
	,iqgcub_conv
	,iqvumd
	,iqgwei
	,iqgwei_conv
	,iquwum
	,iqdmth
	,iqcrmt
	,iqequs
	,iqarot
	,iqarot_conv
	,iqabkd
	,iqabkd_conv
	,iqarol
	,iqarol_conv
	,iqslim
	,iqslim_conv
	,iqeqty
	,iqrpck
	,iqrpck_conv
	,iqpack
	,iqlipl
	,iqlipl_conv
	,iqpptg
	,iqpktg
	,iqprtg
	,iqptra
	,iqptra_conv
	,iqktra
	,iqktra_conv
	,iqrtra
	,iqrtra_conv
	,iquser
	,iquser_conv
	,iqpid
	,iqpid_conv
	,iqjobn
	,iqjobn_conv
	,iqupmj
	,iqupmj_conv
	,iqtday
	,iquccu
	,iquccu_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.iqmcu
	,cdc.iqmcu_conv
	,cdc.iqprp6
	,cdc.iqitm
	,cdc.iquom
	,cdc.iqgwid
	,cdc.iqgwid_conv
	,cdc.iqgdep
	,cdc.iqgdep_conv
	,cdc.iqghet
	,cdc.iqghet_conv
	,cdc.iqwium
	,cdc.iqgcub
	,cdc.iqgcub_conv
	,cdc.iqvumd
	,cdc.iqgwei
	,cdc.iqgwei_conv
	,cdc.iquwum
	,cdc.iqdmth
	,cdc.iqcrmt
	,cdc.iqequs
	,cdc.iqarot
	,cdc.iqarot_conv
	,cdc.iqabkd
	,cdc.iqabkd_conv
	,cdc.iqarol
	,cdc.iqarol_conv
	,cdc.iqslim
	,cdc.iqslim_conv
	,cdc.iqeqty
	,cdc.iqrpck
	,cdc.iqrpck_conv
	,cdc.iqpack
	,cdc.iqlipl
	,cdc.iqlipl_conv
	,cdc.iqpptg
	,cdc.iqpktg
	,cdc.iqprtg
	,cdc.iqptra
	,cdc.iqptra_conv
	,cdc.iqktra
	,cdc.iqktra_conv
	,cdc.iqrtra
	,cdc.iqrtra_conv
	,cdc.iquser
	,cdc.iquser_conv
	,cdc.iqpid
	,cdc.iqpid_conv
	,cdc.iqjobn
	,cdc.iqjobn_conv
	,cdc.iqupmj
	,cdc.iqupmj_conv
	,cdc.iqtday
	,cdc.iquccu
	,cdc.iquccu_conv
FROM stg_jde_qat.tmp_upsert_f46011_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f46011_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f46011_new AF:{{ task_instance_key_str }}' ) 