-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f4801t_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,wadoco
	,waline
	,waline_conv
	,wamwdh
	,wascsp
	,washft
	,wasrcn
	,waledg
	,wacts4
	,wacts4_conv
	,wacts7
	,wacts7_conv
	,wacts8
	,wacts8_conv
	,waaid
	,waaid_conv
	,waalse
	,waalse_conv
	,waasid
	,waasid_conv
	,waatst
	,waatst_conv
	,wabseq
	,wabseq_conv
	,wachpr
	,wachpr_conv
	,wacrcd
	,wacrcd_conv
	,wacrce
	,wacrce_conv
	,wacrcf
	,wacrcf_conv
	,wad5j
	,wad5j_conv
	,wad6j
	,wad6j_conv
	,wadraw
	,wadraw_conv
	,wadual
	,wadual_conv
	,wampce
	,wamprc
	,waobj
	,waobj_conv
	,waotam
	,waotam_conv
	,waprjm
	,waprjm_conv
	,waprrp
	,waprrp_conv
	,washpp
	,wasqor
	,wasqor_conv
	,wasrkf
	,wasrnk
	,wasrnk_conv
	,wassoq
	,wassoq_conv
	,watraf
	,wauom2
	,wawr11
	,wawr12
	,wawr13
	,wawr14
	,wawr15
	,wawr16
	,wawr17
	,wawr18
	,wawr19
	,wawr20
	,wajbcd
	,wavfwo
	,wavfwo_conv
	,wapmtn
	,wapmtn_conv
	,waissue
	,waissue_conv
	,waprodm
	,wawho2
	,wawho2_conv
	,waar1
	,waar1_conv
	,waphn1
	,waphn1_conv
	,watmco
	,wamthpr
	,waentck
	,waryin
	,warstm
	,warstm_conv
	,wactr
	,waregion
	,watxa1
	,watxa1_conv
	,waexr1
	,walngp
	,waglccv
	,waglcnc
	,wacovgr
	,waasn4
	,waasn2
	,wasest
	,waseet
	,wadsavname
	,wadsavname_conv
	,watimezones
	,waprodf
	,wacslprt
	,wacslprt_conv
	,wamcucsl
	,wamcucsl_conv
	,warlot
	,warlot_conv
	,wafailcd
	,wafaildt
	,wafaildt_conv
	,wafailtm
	,wafailtm_conv
	,warepdt
	,warepdt_conv
	,wareptm
	,wareptm_conv
	,wavend
	,wavend_conv
	,waan8as
	,waan8as_conv
	,waan8srm
	,waan8srm_conv
	,wasryn
	,waentcks
	,waentcks_conv
	,wacurbalm1
	,wacurbalm1_conv
	,wacurbalm2
	,wacurbalm2_conv
	,wacurbalm3
	,wacurbalm3_conv
	,wacrdc
	,wacrdc_conv
	,wacrrm
	,wacrr
	,wavmrs31
	,wavmrs32
	,waseqn
	,waplmr
	,waplmr_conv
	,wapllb
	,wapllb_conv
	,waplos
	,waplos_conv
	,wabgtc
	,wabgtc_conv
	,watoem
	,watoem_conv
	,watopl
	,watopl_conv
	,waplsa
	,waplsa_conv
	,waplsu
	,waplsu_conv
	,waessa
	,waessa_conv
	,waessu
	,waessu_conv
	,waacsa
	,waacsa_conv
	,waacsu
	,waacsu_conv
	,waoacm
	,waoacm_conv
	,waracm
	,waracm_conv
	,wahplf
	,wahplf_conv
	,wavmrs33
	,wascall
	,waisno
	,warmthd
	,warmthd_conv
	,wadoc
	,wadct
	,wakco
	,wakco_conv
	,wacoch
	,wacoch_conv
	,walnid
	,walnid_conv
	,wacrtu
	,wacrtu_conv
	,waxevt
	,waxevt_conv
	,wamcult
	,wamcult_conv
	,wawschf
	,wadfmdp
	,wadfmdp_conv
	,wapmpn
	,wapmpn_conv
	,wapns
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.wadoco
	,cdc.waline
	,cdc.waline_conv
	,cdc.wamwdh
	,cdc.wascsp
	,cdc.washft
	,cdc.wasrcn
	,cdc.waledg
	,cdc.wacts4
	,cdc.wacts4_conv
	,cdc.wacts7
	,cdc.wacts7_conv
	,cdc.wacts8
	,cdc.wacts8_conv
	,cdc.waaid
	,cdc.waaid_conv
	,cdc.waalse
	,cdc.waalse_conv
	,cdc.waasid
	,cdc.waasid_conv
	,cdc.waatst
	,cdc.waatst_conv
	,cdc.wabseq
	,cdc.wabseq_conv
	,cdc.wachpr
	,cdc.wachpr_conv
	,cdc.wacrcd
	,cdc.wacrcd_conv
	,cdc.wacrce
	,cdc.wacrce_conv
	,cdc.wacrcf
	,cdc.wacrcf_conv
	,cdc.wad5j
	,cdc.wad5j_conv
	,cdc.wad6j
	,cdc.wad6j_conv
	,cdc.wadraw
	,cdc.wadraw_conv
	,cdc.wadual
	,cdc.wadual_conv
	,cdc.wampce
	,cdc.wamprc
	,cdc.waobj
	,cdc.waobj_conv
	,cdc.waotam
	,cdc.waotam_conv
	,cdc.waprjm
	,cdc.waprjm_conv
	,cdc.waprrp
	,cdc.waprrp_conv
	,cdc.washpp
	,cdc.wasqor
	,cdc.wasqor_conv
	,cdc.wasrkf
	,cdc.wasrnk
	,cdc.wasrnk_conv
	,cdc.wassoq
	,cdc.wassoq_conv
	,cdc.watraf
	,cdc.wauom2
	,cdc.wawr11
	,cdc.wawr12
	,cdc.wawr13
	,cdc.wawr14
	,cdc.wawr15
	,cdc.wawr16
	,cdc.wawr17
	,cdc.wawr18
	,cdc.wawr19
	,cdc.wawr20
	,cdc.wajbcd
	,cdc.wavfwo
	,cdc.wavfwo_conv
	,cdc.wapmtn
	,cdc.wapmtn_conv
	,cdc.waissue
	,cdc.waissue_conv
	,cdc.waprodm
	,cdc.wawho2
	,cdc.wawho2_conv
	,cdc.waar1
	,cdc.waar1_conv
	,cdc.waphn1
	,cdc.waphn1_conv
	,cdc.watmco
	,cdc.wamthpr
	,cdc.waentck
	,cdc.waryin
	,cdc.warstm
	,cdc.warstm_conv
	,cdc.wactr
	,cdc.waregion
	,cdc.watxa1
	,cdc.watxa1_conv
	,cdc.waexr1
	,cdc.walngp
	,cdc.waglccv
	,cdc.waglcnc
	,cdc.wacovgr
	,cdc.waasn4
	,cdc.waasn2
	,cdc.wasest
	,cdc.waseet
	,cdc.wadsavname
	,cdc.wadsavname_conv
	,cdc.watimezones
	,cdc.waprodf
	,cdc.wacslprt
	,cdc.wacslprt_conv
	,cdc.wamcucsl
	,cdc.wamcucsl_conv
	,cdc.warlot
	,cdc.warlot_conv
	,cdc.wafailcd
	,cdc.wafaildt
	,cdc.wafaildt_conv
	,cdc.wafailtm
	,cdc.wafailtm_conv
	,cdc.warepdt
	,cdc.warepdt_conv
	,cdc.wareptm
	,cdc.wareptm_conv
	,cdc.wavend
	,cdc.wavend_conv
	,cdc.waan8as
	,cdc.waan8as_conv
	,cdc.waan8srm
	,cdc.waan8srm_conv
	,cdc.wasryn
	,cdc.waentcks
	,cdc.waentcks_conv
	,cdc.wacurbalm1
	,cdc.wacurbalm1_conv
	,cdc.wacurbalm2
	,cdc.wacurbalm2_conv
	,cdc.wacurbalm3
	,cdc.wacurbalm3_conv
	,cdc.wacrdc
	,cdc.wacrdc_conv
	,cdc.wacrrm
	,cdc.wacrr
	,cdc.wavmrs31
	,cdc.wavmrs32
	,cdc.waseqn
	,cdc.waplmr
	,cdc.waplmr_conv
	,cdc.wapllb
	,cdc.wapllb_conv
	,cdc.waplos
	,cdc.waplos_conv
	,cdc.wabgtc
	,cdc.wabgtc_conv
	,cdc.watoem
	,cdc.watoem_conv
	,cdc.watopl
	,cdc.watopl_conv
	,cdc.waplsa
	,cdc.waplsa_conv
	,cdc.waplsu
	,cdc.waplsu_conv
	,cdc.waessa
	,cdc.waessa_conv
	,cdc.waessu
	,cdc.waessu_conv
	,cdc.waacsa
	,cdc.waacsa_conv
	,cdc.waacsu
	,cdc.waacsu_conv
	,cdc.waoacm
	,cdc.waoacm_conv
	,cdc.waracm
	,cdc.waracm_conv
	,cdc.wahplf
	,cdc.wahplf_conv
	,cdc.wavmrs33
	,cdc.wascall
	,cdc.waisno
	,cdc.warmthd
	,cdc.warmthd_conv
	,cdc.wadoc
	,cdc.wadct
	,cdc.wakco
	,cdc.wakco_conv
	,cdc.wacoch
	,cdc.wacoch_conv
	,cdc.walnid
	,cdc.walnid_conv
	,cdc.wacrtu
	,cdc.wacrtu_conv
	,cdc.waxevt
	,cdc.waxevt_conv
	,cdc.wamcult
	,cdc.wamcult_conv
	,cdc.wawschf
	,cdc.wadfmdp
	,cdc.wadfmdp_conv
	,cdc.wapmpn
	,cdc.wapmpn_conv
	,cdc.wapns
FROM stg_jde_qat.tmp_upsert_f4801t_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f4801t_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f4801t_new AF:{{ task_instance_key_str }}' ) 