-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f4931_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,vgvtyp
	,vgvtyp_conv
	,vgdl01
	,vgdl01_conv
	,vgmcu
	,vgmcu_conv
	,vgmot
	,vgdsgp
	,vgdsgs
	,vgnce
	,vgnce_conv
	,vgwtem
	,vgwtem_conv
	,vgwtca
	,vgwtca_conv
	,vgwtum
	,vgvlcp
	,vgvlcp_conv
	,vgvlcs
	,vgvlcs_conv
	,vgvlum
	,vgcvol
	,vgcvol_conv
	,vgcvum
	,vglcnt
	,vgaxle
	,vgaxle_conv
	,vgwtax
	,vgseal
	,vgseal_conv
	,vglnle
	,vglnle_conv
	,vglnwe
	,vglnwe_conv
	,vglnhe
	,vglnhe_conv
	,vglnli
	,vglnli_conv
	,vglnwi
	,vglnwi_conv
	,vglnhr
	,vglnhr_conv
	,vglnhc
	,vglnhc_conv
	,vglnhf
	,vglnhf_conv
	,vglhrd
	,vglhrd_conv
	,vglwrd
	,vglwrd_conv
	,vglhsd
	,vglhsd_conv
	,vglwsd
	,vglwsd_conv
	,vglnvf
	,vglnvf_conv
	,vgluom
	,vgcpfg
	,vgcpfg_conv
	,vgbpfg
	,vgmlln
	,vgmlln_conv
	,vgurcd
	,vgurcd_conv
	,vgurdt
	,vgurdt_conv
	,vgurab
	,vgurab_conv
	,vgurrf
	,vgurrf_conv
	,vguser
	,vguser_conv
	,vgpid
	,vgpid_conv
	,vgjobn
	,vgjobn_conv
	,vgupmj
	,vgupmj_conv
	,vgtday
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.vgvtyp
	,cdc.vgvtyp_conv
	,cdc.vgdl01
	,cdc.vgdl01_conv
	,cdc.vgmcu
	,cdc.vgmcu_conv
	,cdc.vgmot
	,cdc.vgdsgp
	,cdc.vgdsgs
	,cdc.vgnce
	,cdc.vgnce_conv
	,cdc.vgwtem
	,cdc.vgwtem_conv
	,cdc.vgwtca
	,cdc.vgwtca_conv
	,cdc.vgwtum
	,cdc.vgvlcp
	,cdc.vgvlcp_conv
	,cdc.vgvlcs
	,cdc.vgvlcs_conv
	,cdc.vgvlum
	,cdc.vgcvol
	,cdc.vgcvol_conv
	,cdc.vgcvum
	,cdc.vglcnt
	,cdc.vgaxle
	,cdc.vgaxle_conv
	,cdc.vgwtax
	,cdc.vgseal
	,cdc.vgseal_conv
	,cdc.vglnle
	,cdc.vglnle_conv
	,cdc.vglnwe
	,cdc.vglnwe_conv
	,cdc.vglnhe
	,cdc.vglnhe_conv
	,cdc.vglnli
	,cdc.vglnli_conv
	,cdc.vglnwi
	,cdc.vglnwi_conv
	,cdc.vglnhr
	,cdc.vglnhr_conv
	,cdc.vglnhc
	,cdc.vglnhc_conv
	,cdc.vglnhf
	,cdc.vglnhf_conv
	,cdc.vglhrd
	,cdc.vglhrd_conv
	,cdc.vglwrd
	,cdc.vglwrd_conv
	,cdc.vglhsd
	,cdc.vglhsd_conv
	,cdc.vglwsd
	,cdc.vglwsd_conv
	,cdc.vglnvf
	,cdc.vglnvf_conv
	,cdc.vgluom
	,cdc.vgcpfg
	,cdc.vgcpfg_conv
	,cdc.vgbpfg
	,cdc.vgmlln
	,cdc.vgmlln_conv
	,cdc.vgurcd
	,cdc.vgurcd_conv
	,cdc.vgurdt
	,cdc.vgurdt_conv
	,cdc.vgurab
	,cdc.vgurab_conv
	,cdc.vgurrf
	,cdc.vgurrf_conv
	,cdc.vguser
	,cdc.vguser_conv
	,cdc.vgpid
	,cdc.vgpid_conv
	,cdc.vgjobn
	,cdc.vgjobn_conv
	,cdc.vgupmj
	,cdc.vgupmj_conv
	,cdc.vgtday
FROM stg_jde_qat.tmp_upsert_f4931_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f4931_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f4931_new AF:{{ task_instance_key_str }}' ) 