-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f4945_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,scshpn
	,scrssn
	,scvmcu
	,scvmcu_conv
	,scldnm
	,scdlno
	,scoseq
	,scoseq_conv
	,scrtnm
	,scsdsq
	,scsdsq_conv
	,scscsn
	,scscsn_conv
	,scnmfc
	,scdsgp
	,scfrt1
	,scfrt2
	,sccgc1
	,scag
	,scag_conv
	,scblpb
	,scblpb_conv
	,sccrdc
	,sccrdc_conv
	,scfaa
	,scfaa_conv
	,scnamf
	,scnamf_conv
	,scrtdq
	,scrtdq_conv
	,scnamt
	,scnamt_conv
	,scuom
	,scrtgb
	,sccrcd
	,sccrcd_conv
	,scdoco
	,scdcto
	,sckcoo
	,sckcoo_conv
	,sclnid
	,sclnid_conv
	,scovfg
	,scukid
	,scuk01
	,scurcd
	,scurcd_conv
	,scurdt
	,scurdt_conv
	,scurat
	,scurat_conv
	,scurab
	,scurab_conv
	,scurrf
	,scurrf_conv
	,scuser
	,scuser_conv
	,scpid
	,scpid_conv
	,scjobn
	,scjobn_conv
	,scupmj
	,scupmj_conv
	,sctday
	,scrtn
	,sclnmb
	,scprte
	,scprte_conv
	,sceftj
	,sceftj_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.scshpn
	,cdc.scrssn
	,cdc.scvmcu
	,cdc.scvmcu_conv
	,cdc.scldnm
	,cdc.scdlno
	,cdc.scoseq
	,cdc.scoseq_conv
	,cdc.scrtnm
	,cdc.scsdsq
	,cdc.scsdsq_conv
	,cdc.scscsn
	,cdc.scscsn_conv
	,cdc.scnmfc
	,cdc.scdsgp
	,cdc.scfrt1
	,cdc.scfrt2
	,cdc.sccgc1
	,cdc.scag
	,cdc.scag_conv
	,cdc.scblpb
	,cdc.scblpb_conv
	,cdc.sccrdc
	,cdc.sccrdc_conv
	,cdc.scfaa
	,cdc.scfaa_conv
	,cdc.scnamf
	,cdc.scnamf_conv
	,cdc.scrtdq
	,cdc.scrtdq_conv
	,cdc.scnamt
	,cdc.scnamt_conv
	,cdc.scuom
	,cdc.scrtgb
	,cdc.sccrcd
	,cdc.sccrcd_conv
	,cdc.scdoco
	,cdc.scdcto
	,cdc.sckcoo
	,cdc.sckcoo_conv
	,cdc.sclnid
	,cdc.sclnid_conv
	,cdc.scovfg
	,cdc.scukid
	,cdc.scuk01
	,cdc.scurcd
	,cdc.scurcd_conv
	,cdc.scurdt
	,cdc.scurdt_conv
	,cdc.scurat
	,cdc.scurat_conv
	,cdc.scurab
	,cdc.scurab_conv
	,cdc.scurrf
	,cdc.scurrf_conv
	,cdc.scuser
	,cdc.scuser_conv
	,cdc.scpid
	,cdc.scpid_conv
	,cdc.scjobn
	,cdc.scjobn_conv
	,cdc.scupmj
	,cdc.scupmj_conv
	,cdc.sctday
	,cdc.scrtn
	,cdc.sclnmb
	,cdc.scprte
	,cdc.scprte_conv
	,cdc.sceftj
	,cdc.sceftj_conv
FROM stg_jde_qat.tmp_upsert_f4945_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f4945_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f4945_new AF:{{ task_instance_key_str }}' ) 