-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f49501_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,rdprnb
	,rdlnmb
	,rdorgn
	,rdancc
	,rdcars
	,rdcars_conv
	,rdmot
	,rdfrsc
	,rdfrcg
	,rdfrcg_conv
	,rdcrcd
	,rdcrcd_conv
	,rdfrtp
	,rdrtgb
	,rdrtum
	,rddstn
	,rdumd1
	,rdrtn
	,rdcnmr
	,rdcnmr_conv
	,rdltdt
	,rdltdt_conv
	,rdeftj
	,rdeftj_conv
	,rdexdj
	,rdexdj_conv
	,rdurcd
	,rdurcd_conv
	,rdurdt
	,rdurdt_conv
	,rdurat
	,rdurat_conv
	,rdurab
	,rdurab_conv
	,rdurrf
	,rdurrf_conv
	,rduser
	,rduser_conv
	,rdpid
	,rdpid_conv
	,rdjobn
	,rdjobn_conv
	,rdupmj
	,rdupmj_conv
	,rdtday
	,rdtx
	,rdtxa1
	,rdtxa1_conv
	,rdexr1
	,rdtax1
	,rdtxa2
	,rdtxa2_conv
	,rdexr2
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.rdprnb
	,cdc.rdlnmb
	,cdc.rdorgn
	,cdc.rdancc
	,cdc.rdcars
	,cdc.rdcars_conv
	,cdc.rdmot
	,cdc.rdfrsc
	,cdc.rdfrcg
	,cdc.rdfrcg_conv
	,cdc.rdcrcd
	,cdc.rdcrcd_conv
	,cdc.rdfrtp
	,cdc.rdrtgb
	,cdc.rdrtum
	,cdc.rddstn
	,cdc.rdumd1
	,cdc.rdrtn
	,cdc.rdcnmr
	,cdc.rdcnmr_conv
	,cdc.rdltdt
	,cdc.rdltdt_conv
	,cdc.rdeftj
	,cdc.rdeftj_conv
	,cdc.rdexdj
	,cdc.rdexdj_conv
	,cdc.rdurcd
	,cdc.rdurcd_conv
	,cdc.rdurdt
	,cdc.rdurdt_conv
	,cdc.rdurat
	,cdc.rdurat_conv
	,cdc.rdurab
	,cdc.rdurab_conv
	,cdc.rdurrf
	,cdc.rdurrf_conv
	,cdc.rduser
	,cdc.rduser_conv
	,cdc.rdpid
	,cdc.rdpid_conv
	,cdc.rdjobn
	,cdc.rdjobn_conv
	,cdc.rdupmj
	,cdc.rdupmj_conv
	,cdc.rdtday
	,cdc.rdtx
	,cdc.rdtxa1
	,cdc.rdtxa1_conv
	,cdc.rdexr1
	,cdc.rdtax1
	,cdc.rdtxa2
	,cdc.rdtxa2_conv
	,cdc.rdexr2
FROM stg_jde_qat.tmp_upsert_f49501_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f49501_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f49501_new AF:{{ task_instance_key_str }}' ) 