-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f553402_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,mfy55fornu
	,mfy55fornu_conv
	,mfitm
	,mfan8
	,mfky
	,mfky_conv
	,mfalph
	,mfalph_conv
	,mfbncv
	,mfbncv_conv
	,mfc9dtpr
	,mfc9dtpr_conv
	,mfc9perfrom
	,mfc9perfrom_conv
	,mfc9perthru
	,mfc9perthru_conv
	,mfbcnt
	,mfbcnt_conv
	,mfalph2
	,mfalph2_conv
	,mfemailfrom
	,mfemailfrom_conv
	,mfalph3
	,mfalph3_conv
	,mfemal
	,mfemal_conv
	,mfmcu
	,mfmcu_conv
	,mfcnr1
	,mfcnr2
	,mfcntf
	,mfcntf_conv
	,mfrrqj
	,mfrrqj_conv
	,mfyn
	,mfyn_conv
	,mfdl01
	,mfdl01_conv
	,mfansif
	,mfansif_conv
	,mfdl02
	,mfdl02_conv
	,mfdl03
	,mfdl03_conv
	,mfdl04
	,mfdl04_conv
	,mfabcs
	,mflitm
	,mflitm_conv
	,mfdsc1
	,mfdsc1_conv
	,mfcitm
	,mfcitm_conv
	,mflnid
	,mflnid_conv
	,mfuom
	,mfy55plqty1
	,mfy55plqty1_conv
	,mfy55cmqty1
	,mfy55cmqty1_conv
	,mfy55plqty2
	,mfy55plqty2_conv
	,mfy55cmqty2
	,mfy55cmqty2_conv
	,mfy55plqty3
	,mfy55plqty3_conv
	,mfy55cmqty3
	,mfy55cmqty3_conv
	,mfy55plqty4
	,mfy55plqty4_conv
	,mfy55cmqty4
	,mfy55cmqty4_conv
	,mfy55plqty5
	,mfy55plqty5_conv
	,mfy55cmqty5
	,mfy55cmqty5_conv
	,mfy55plqty6
	,mfy55plqty6_conv
	,mfy55cmqty6
	,mfy55cmqty6_conv
	,mfy55plqty7
	,mfy55plqty7_conv
	,mfy55cmqty7
	,mfy55cmqty7_conv
	,mfy55plqty8
	,mfy55plqty8_conv
	,mfy55cmqty8
	,mfy55cmqty8_conv
	,mfy55plqty9
	,mfy55plqty9_conv
	,mfy55cmqty9
	,mfy55cmqty9_conv
	,mfy55plqty10
	,mfy55plqty10_conv
	,mfy55cmqty10
	,mfy55cmqty10_conv
	,mfy55plqty11
	,mfy55plqty11_conv
	,mfy55cmqty11
	,mfy55cmqty11_conv
	,mfy55plqty12
	,mfy55plqty12_conv
	,mfy55cmqty12
	,mfy55cmqty12_conv
	,mfplqty
	,mfplqty_conv
	,mfflag
	,mfflag_conv
	,mfnotiflg
	,mfnotiflg_conv
	,mfcomments
	,mfcomments_conv
	,mfurcd
	,mfurcd_conv
	,mfurdt
	,mfurdt_conv
	,mfurat
	,mfurat_conv
	,mfurab
	,mfurab_conv
	,mfurrf
	,mfurrf_conv
	,mfuser
	,mfuser_conv
	,mfpid
	,mfpid_conv
	,mfupmj
	,mfupmj_conv
	,mfjobn
	,mfjobn_conv
	,mfupmt
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.mfy55fornu
	,cdc.mfy55fornu_conv
	,cdc.mfitm
	,cdc.mfan8
	,cdc.mfky
	,cdc.mfky_conv
	,cdc.mfalph
	,cdc.mfalph_conv
	,cdc.mfbncv
	,cdc.mfbncv_conv
	,cdc.mfc9dtpr
	,cdc.mfc9dtpr_conv
	,cdc.mfc9perfrom
	,cdc.mfc9perfrom_conv
	,cdc.mfc9perthru
	,cdc.mfc9perthru_conv
	,cdc.mfbcnt
	,cdc.mfbcnt_conv
	,cdc.mfalph2
	,cdc.mfalph2_conv
	,cdc.mfemailfrom
	,cdc.mfemailfrom_conv
	,cdc.mfalph3
	,cdc.mfalph3_conv
	,cdc.mfemal
	,cdc.mfemal_conv
	,cdc.mfmcu
	,cdc.mfmcu_conv
	,cdc.mfcnr1
	,cdc.mfcnr2
	,cdc.mfcntf
	,cdc.mfcntf_conv
	,cdc.mfrrqj
	,cdc.mfrrqj_conv
	,cdc.mfyn
	,cdc.mfyn_conv
	,cdc.mfdl01
	,cdc.mfdl01_conv
	,cdc.mfansif
	,cdc.mfansif_conv
	,cdc.mfdl02
	,cdc.mfdl02_conv
	,cdc.mfdl03
	,cdc.mfdl03_conv
	,cdc.mfdl04
	,cdc.mfdl04_conv
	,cdc.mfabcs
	,cdc.mflitm
	,cdc.mflitm_conv
	,cdc.mfdsc1
	,cdc.mfdsc1_conv
	,cdc.mfcitm
	,cdc.mfcitm_conv
	,cdc.mflnid
	,cdc.mflnid_conv
	,cdc.mfuom
	,cdc.mfy55plqty1
	,cdc.mfy55plqty1_conv
	,cdc.mfy55cmqty1
	,cdc.mfy55cmqty1_conv
	,cdc.mfy55plqty2
	,cdc.mfy55plqty2_conv
	,cdc.mfy55cmqty2
	,cdc.mfy55cmqty2_conv
	,cdc.mfy55plqty3
	,cdc.mfy55plqty3_conv
	,cdc.mfy55cmqty3
	,cdc.mfy55cmqty3_conv
	,cdc.mfy55plqty4
	,cdc.mfy55plqty4_conv
	,cdc.mfy55cmqty4
	,cdc.mfy55cmqty4_conv
	,cdc.mfy55plqty5
	,cdc.mfy55plqty5_conv
	,cdc.mfy55cmqty5
	,cdc.mfy55cmqty5_conv
	,cdc.mfy55plqty6
	,cdc.mfy55plqty6_conv
	,cdc.mfy55cmqty6
	,cdc.mfy55cmqty6_conv
	,cdc.mfy55plqty7
	,cdc.mfy55plqty7_conv
	,cdc.mfy55cmqty7
	,cdc.mfy55cmqty7_conv
	,cdc.mfy55plqty8
	,cdc.mfy55plqty8_conv
	,cdc.mfy55cmqty8
	,cdc.mfy55cmqty8_conv
	,cdc.mfy55plqty9
	,cdc.mfy55plqty9_conv
	,cdc.mfy55cmqty9
	,cdc.mfy55cmqty9_conv
	,cdc.mfy55plqty10
	,cdc.mfy55plqty10_conv
	,cdc.mfy55cmqty10
	,cdc.mfy55cmqty10_conv
	,cdc.mfy55plqty11
	,cdc.mfy55plqty11_conv
	,cdc.mfy55cmqty11
	,cdc.mfy55cmqty11_conv
	,cdc.mfy55plqty12
	,cdc.mfy55plqty12_conv
	,cdc.mfy55cmqty12
	,cdc.mfy55cmqty12_conv
	,cdc.mfplqty
	,cdc.mfplqty_conv
	,cdc.mfflag
	,cdc.mfflag_conv
	,cdc.mfnotiflg
	,cdc.mfnotiflg_conv
	,cdc.mfcomments
	,cdc.mfcomments_conv
	,cdc.mfurcd
	,cdc.mfurcd_conv
	,cdc.mfurdt
	,cdc.mfurdt_conv
	,cdc.mfurat
	,cdc.mfurat_conv
	,cdc.mfurab
	,cdc.mfurab_conv
	,cdc.mfurrf
	,cdc.mfurrf_conv
	,cdc.mfuser
	,cdc.mfuser_conv
	,cdc.mfpid
	,cdc.mfpid_conv
	,cdc.mfupmj
	,cdc.mfupmj_conv
	,cdc.mfjobn
	,cdc.mfjobn_conv
	,cdc.mfupmt
FROM stg_jde_qat.tmp_upsert_f553402_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f553402_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f553402_new AF:{{ task_instance_key_str }}' ) 