-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f554904_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,fdvr01
	,fdvr01_conv
	,fdy55fcode
	,fdy55msgno
	,fdy55msgno_conv
	,fdy55insdj
	,fdy55insdj_conv
	,fdy55insdt
	,fdldnm
	,fdlnid
	,fdlnid_conv
	,fdy55fdst
	,fdumd1
	,fdy55fwait
	,fdfrcg
	,fdfrcg_conv
	,fdy55fwaitc
	,fdy55fwaitc_conv
	,fdedbt
	,fdedbt_conv
	,fdedtn
	,fdedtn_conv
	,fdflag
	,fdflag_conv
	,fduser
	,fduser_conv
	,fdpid
	,fdpid_conv
	,fdjobn
	,fdjobn_conv
	,fdupmj
	,fdupmj_conv
	,fdupmt
	,fdurrf
	,fdurrf_conv
	,fdurcd
	,fdurcd_conv
	,fdurab
	,fdurab_conv
	,fdurat
	,fdurat_conv
	,fdurdt
	,fdurdt_conv
	,fdrcd
	,fdy55char1
	,fdy55char1_conv
	,fdy55char2
	,fdy55char2_conv
	,fdy55date1
	,fdy55date1_conv
	,fdy55date2
	,fdy55date2_conv
	,fdy55strg1
	,fdy55strg1_conv
	,fdy55strg2
	,fdy55strg2_conv
	,fdy55strg3
	,fdy55strg3_conv
	,fdy55strg4
	,fdy55strg4_conv
	,fdy55strg5
	,fdy55strg5_conv
	,fdy55strg6
	,fdy55strg6_conv
	,fdy55strg7
	,fdy55strg7_conv
	,fdy55strg8
	,fdy55strg8_conv
	,fdy55strg9
	,fdy55strg9_conv
	,fdy55strg10
	,fdy55strg10_conv
	,fdy55flg1
	,fdy55flg1_conv
	,fdy55flg2
	,fdy55flg2_conv
	,fdy55num3
	,fdy55num3_conv
	,fdy55num4
	,fdy55num4_conv
	,fdy55time1
	,fdy55time2
	,fdy55amnt2
	,fdy55amnt2_conv
	,fdy55amnt1
	,fdy55amnt1_conv
	,fdukid
	,fdflg2
	,fdflg2_conv
	,fdflg3
	,fdflg3_conv
	,fdxpitraid
	,fdxpitraid_conv
	,fdflg01
	,fdflg01_conv
	,fdy55fwttm
	,fdy55fwttm_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.fdvr01
	,cdc.fdvr01_conv
	,cdc.fdy55fcode
	,cdc.fdy55msgno
	,cdc.fdy55msgno_conv
	,cdc.fdy55insdj
	,cdc.fdy55insdj_conv
	,cdc.fdy55insdt
	,cdc.fdldnm
	,cdc.fdlnid
	,cdc.fdlnid_conv
	,cdc.fdy55fdst
	,cdc.fdumd1
	,cdc.fdy55fwait
	,cdc.fdfrcg
	,cdc.fdfrcg_conv
	,cdc.fdy55fwaitc
	,cdc.fdy55fwaitc_conv
	,cdc.fdedbt
	,cdc.fdedbt_conv
	,cdc.fdedtn
	,cdc.fdedtn_conv
	,cdc.fdflag
	,cdc.fdflag_conv
	,cdc.fduser
	,cdc.fduser_conv
	,cdc.fdpid
	,cdc.fdpid_conv
	,cdc.fdjobn
	,cdc.fdjobn_conv
	,cdc.fdupmj
	,cdc.fdupmj_conv
	,cdc.fdupmt
	,cdc.fdurrf
	,cdc.fdurrf_conv
	,cdc.fdurcd
	,cdc.fdurcd_conv
	,cdc.fdurab
	,cdc.fdurab_conv
	,cdc.fdurat
	,cdc.fdurat_conv
	,cdc.fdurdt
	,cdc.fdurdt_conv
	,cdc.fdrcd
	,cdc.fdy55char1
	,cdc.fdy55char1_conv
	,cdc.fdy55char2
	,cdc.fdy55char2_conv
	,cdc.fdy55date1
	,cdc.fdy55date1_conv
	,cdc.fdy55date2
	,cdc.fdy55date2_conv
	,cdc.fdy55strg1
	,cdc.fdy55strg1_conv
	,cdc.fdy55strg2
	,cdc.fdy55strg2_conv
	,cdc.fdy55strg3
	,cdc.fdy55strg3_conv
	,cdc.fdy55strg4
	,cdc.fdy55strg4_conv
	,cdc.fdy55strg5
	,cdc.fdy55strg5_conv
	,cdc.fdy55strg6
	,cdc.fdy55strg6_conv
	,cdc.fdy55strg7
	,cdc.fdy55strg7_conv
	,cdc.fdy55strg8
	,cdc.fdy55strg8_conv
	,cdc.fdy55strg9
	,cdc.fdy55strg9_conv
	,cdc.fdy55strg10
	,cdc.fdy55strg10_conv
	,cdc.fdy55flg1
	,cdc.fdy55flg1_conv
	,cdc.fdy55flg2
	,cdc.fdy55flg2_conv
	,cdc.fdy55num3
	,cdc.fdy55num3_conv
	,cdc.fdy55num4
	,cdc.fdy55num4_conv
	,cdc.fdy55time1
	,cdc.fdy55time2
	,cdc.fdy55amnt2
	,cdc.fdy55amnt2_conv
	,cdc.fdy55amnt1
	,cdc.fdy55amnt1_conv
	,cdc.fdukid
	,cdc.fdflg2
	,cdc.fdflg2_conv
	,cdc.fdflg3
	,cdc.fdflg3_conv
	,cdc.fdxpitraid
	,cdc.fdxpitraid_conv
	,cdc.fdflg01
	,cdc.fdflg01_conv
	,cdc.fdy55fwttm
	,cdc.fdy55fwttm_conv
FROM stg_jde_qat.tmp_upsert_f554904_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f554904_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f554904_new AF:{{ task_instance_key_str }}' ) 