-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f554237_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,rsaddj
	,rsaddj_conv
	,rsvr01
	,rsvr01_conv
	,rsmcu
	,rsmcu_conv
	,rstpc
	,rstpc_conv
	,rstax1
	,rsback
	,rsback_conv
	,rsurrf
	,rsurrf_conv
	,rssbal
	,rssbal_conv
	,rsaa18
	,rsaa18_conv
	,rsvr02
	,rsvr02_conv
	,rsacttime
	,rsacttime_conv
	,rsobsz
	,rsaa30
	,rsaa30_conv
	,rsctr
	,rsaa20
	,rsaa20_conv
	,rssbtm
	,rsev01
	,rsev01_conv
	,rsev02
	,rsev02_conv
	,rsev03
	,rsev03_conv
	,rsev04
	,rsev04_conv
	,rsev05
	,rsev05_conv
	,rsev06
	,rsev06_conv
	,rsev07
	,rsev07_conv
	,rsev08
	,rsev08_conv
	,rsev09
	,rsev09_conv
	,rsaurst2
	,rsaurst2_conv
	,rsaurst3
	,rsaurst3_conv
	,rsy55char1
	,rsy55char1_conv
	,rsy55char2
	,rsy55char2_conv
	,rsy55strg1
	,rsy55strg1_conv
	,rsy55strg2
	,rsy55strg2_conv
	,rsy55amnt1
	,rsy55amnt1_conv
	,rsy55amnt2
	,rsy55amnt2_conv
	,rsy55time1
	,rsy55time2
	,rsy55date1
	,rsy55date1_conv
	,rsy55date2
	,rsy55date2_conv
	,rsuser
	,rsuser_conv
	,rspid
	,rspid_conv
	,rsjobn
	,rsjobn_conv
	,rsupmj
	,rsupmj_conv
	,rsupmt
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.rsaddj
	,cdc.rsaddj_conv
	,cdc.rsvr01
	,cdc.rsvr01_conv
	,cdc.rsmcu
	,cdc.rsmcu_conv
	,cdc.rstpc
	,cdc.rstpc_conv
	,cdc.rstax1
	,cdc.rsback
	,cdc.rsback_conv
	,cdc.rsurrf
	,cdc.rsurrf_conv
	,cdc.rssbal
	,cdc.rssbal_conv
	,cdc.rsaa18
	,cdc.rsaa18_conv
	,cdc.rsvr02
	,cdc.rsvr02_conv
	,cdc.rsacttime
	,cdc.rsacttime_conv
	,cdc.rsobsz
	,cdc.rsaa30
	,cdc.rsaa30_conv
	,cdc.rsctr
	,cdc.rsaa20
	,cdc.rsaa20_conv
	,cdc.rssbtm
	,cdc.rsev01
	,cdc.rsev01_conv
	,cdc.rsev02
	,cdc.rsev02_conv
	,cdc.rsev03
	,cdc.rsev03_conv
	,cdc.rsev04
	,cdc.rsev04_conv
	,cdc.rsev05
	,cdc.rsev05_conv
	,cdc.rsev06
	,cdc.rsev06_conv
	,cdc.rsev07
	,cdc.rsev07_conv
	,cdc.rsev08
	,cdc.rsev08_conv
	,cdc.rsev09
	,cdc.rsev09_conv
	,cdc.rsaurst2
	,cdc.rsaurst2_conv
	,cdc.rsaurst3
	,cdc.rsaurst3_conv
	,cdc.rsy55char1
	,cdc.rsy55char1_conv
	,cdc.rsy55char2
	,cdc.rsy55char2_conv
	,cdc.rsy55strg1
	,cdc.rsy55strg1_conv
	,cdc.rsy55strg2
	,cdc.rsy55strg2_conv
	,cdc.rsy55amnt1
	,cdc.rsy55amnt1_conv
	,cdc.rsy55amnt2
	,cdc.rsy55amnt2_conv
	,cdc.rsy55time1
	,cdc.rsy55time2
	,cdc.rsy55date1
	,cdc.rsy55date1_conv
	,cdc.rsy55date2
	,cdc.rsy55date2_conv
	,cdc.rsuser
	,cdc.rsuser_conv
	,cdc.rspid
	,cdc.rspid_conv
	,cdc.rsjobn
	,cdc.rsjobn_conv
	,cdc.rsupmj
	,cdc.rsupmj_conv
	,cdc.rsupmt
FROM stg_jde_qat.tmp_upsert_f554237_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f554237_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f554237_new AF:{{ task_instance_key_str }}' ) 