-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f554501_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,qmukid
	,qmy55qn
	,qmy55qn_conv
	,qmdsc1
	,qmdsc1_conv
	,qmy55qs
	,qmy55qt
	,qmy55jdqn
	,qmy55jdqn_conv
	,qmdsc2
	,qmdsc2_conv
	,qmcrcd
	,qmcrcd_conv
	,qmuom
	,qmdend
	,qmdend_conv
	,qmdntp
	,qmdte
	,qmdte_conv
	,qmy55avin
	,qmco
	,qmco_conv
	,qmmcu
	,qmmcu_conv
	,qmprp4
	,qmcomments
	,qmcomments_conv
	,qmflag
	,qmflag_conv
	,qmurrf
	,qmurrf_conv
	,qmurcd
	,qmurcd_conv
	,qmurab
	,qmurab_conv
	,qmurat
	,qmurat_conv
	,qmurdt
	,qmurdt_conv
	,qmuser
	,qmuser_conv
	,qmpid
	,qmpid_conv
	,qmjobn
	,qmjobn_conv
	,qmupmt
	,qmupmj
	,qmupmj_conv
	,qmev01
	,qmev01_conv
	,qmev02
	,qmev02_conv
	,qmev03
	,qmev03_conv
	,qmev04
	,qmev04_conv
	,qmy55char1
	,qmy55char1_conv
	,qmy55char2
	,qmy55char2_conv
	,qmy55date1
	,qmy55date1_conv
	,qmy55date2
	,qmy55date2_conv
	,qmy55strg1
	,qmy55strg1_conv
	,qmy55strg2
	,qmy55strg2_conv
	,qmy55time1
	,qmy55time2
	,qmy55amnt1
	,qmy55amnt1_conv
	,qmy55amnt2
	,qmy55amnt2_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.qmukid
	,cdc.qmy55qn
	,cdc.qmy55qn_conv
	,cdc.qmdsc1
	,cdc.qmdsc1_conv
	,cdc.qmy55qs
	,cdc.qmy55qt
	,cdc.qmy55jdqn
	,cdc.qmy55jdqn_conv
	,cdc.qmdsc2
	,cdc.qmdsc2_conv
	,cdc.qmcrcd
	,cdc.qmcrcd_conv
	,cdc.qmuom
	,cdc.qmdend
	,cdc.qmdend_conv
	,cdc.qmdntp
	,cdc.qmdte
	,cdc.qmdte_conv
	,cdc.qmy55avin
	,cdc.qmco
	,cdc.qmco_conv
	,cdc.qmmcu
	,cdc.qmmcu_conv
	,cdc.qmprp4
	,cdc.qmcomments
	,cdc.qmcomments_conv
	,cdc.qmflag
	,cdc.qmflag_conv
	,cdc.qmurrf
	,cdc.qmurrf_conv
	,cdc.qmurcd
	,cdc.qmurcd_conv
	,cdc.qmurab
	,cdc.qmurab_conv
	,cdc.qmurat
	,cdc.qmurat_conv
	,cdc.qmurdt
	,cdc.qmurdt_conv
	,cdc.qmuser
	,cdc.qmuser_conv
	,cdc.qmpid
	,cdc.qmpid_conv
	,cdc.qmjobn
	,cdc.qmjobn_conv
	,cdc.qmupmt
	,cdc.qmupmj
	,cdc.qmupmj_conv
	,cdc.qmev01
	,cdc.qmev01_conv
	,cdc.qmev02
	,cdc.qmev02_conv
	,cdc.qmev03
	,cdc.qmev03_conv
	,cdc.qmev04
	,cdc.qmev04_conv
	,cdc.qmy55char1
	,cdc.qmy55char1_conv
	,cdc.qmy55char2
	,cdc.qmy55char2_conv
	,cdc.qmy55date1
	,cdc.qmy55date1_conv
	,cdc.qmy55date2
	,cdc.qmy55date2_conv
	,cdc.qmy55strg1
	,cdc.qmy55strg1_conv
	,cdc.qmy55strg2
	,cdc.qmy55strg2_conv
	,cdc.qmy55time1
	,cdc.qmy55time2
	,cdc.qmy55amnt1
	,cdc.qmy55amnt1_conv
	,cdc.qmy55amnt2
	,cdc.qmy55amnt2_conv
FROM stg_jde_qat.tmp_upsert_f554501_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f554501_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f554501_new AF:{{ task_instance_key_str }}' ) 