-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f554347_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,asaddj
	,asaddj_conv
	,asan83
	,asedtg
	,asedtg_conv
	,asukid
	,asy55strg2
	,asy55strg2_conv
	,asitm
	,aslitm
	,aslitm_conv
	,asaitm
	,asaitm_conv
	,asdsc1
	,asdsc1_conv
	,asmath80
	,asmath80_conv
	,asan8
	,asaa04
	,asaa04_conv
	,asdscrp3
	,asdscrp3_conv
	,asdscrp4
	,asdscrp4_conv
	,asuncs
	,asuncs_conv
	,asuopn
	,asuopn_conv
	,asuorg
	,asuorg_conv
	,asmath02
	,asmath02_conv
	,asmath03
	,asmath03_conv
	,asaexp
	,asaexp_conv
	,asacatt1ds
	,asacatt1ds_conv
	,asacatt2ds
	,asacatt2ds_conv
	,asacpr
	,asacpr_conv
	,asfsrrc
	,asfsrrc_conv
	,asacqow
	,asacqow_conv
	,asaarc
	,asaarc_conv
	,asacrc
	,asacrc_conv
	,asacrg
	,asacrg_conv
	,asacrtb
	,asacrtb_conv
	,asaabr
	,asaabr_conv
	,asactur
	,asactur_conv
	,asacvl
	,asacvl_conv
	,asphrase
	,asphrase_conv
	,asmcdtl
	,asmcdtl_conv
	,assubtxt
	,assubtxt_conv
	,asdes1
	,asdes1_conv
	,asdes3
	,asdes3_conv
	,asprna1
	,asprna1_conv
	,asdes2
	,asdes2_conv
	,asan82
	,asgflag2
	,asgflag2_conv
	,asafe
	,asafe_conv
	,aslnty
	,aslnty_conv
	,asaa12
	,asaa12_conv
	,asvr01
	,asvr01_conv
	,asgfl8
	,asgfl8_conv
	,asmath10
	,asmath10_conv
	,asuprc
	,asuprc_conv
	,asfrrc
	,asfrrc_conv
	,asamrate
	,asamrate_conv
	,asxcpr
	,asxcpr_conv
	,asacrd
	,asacrd_conv
	,asfup
	,asfup_conv
	,asofup
	,asofup_conv
	,asachg
	,asachg_conv
	,assbl
	,assbl_conv
	,asaa02
	,asaa02_conv
	,asmath07
	,asmath07_conv
	,asmath06
	,asmath06_conv
	,asanby
	,asctime
	,asctime_conv
	,asbgtime
	,asapptime
	,asacttime
	,asacttime_conv
	,asdkj
	,asdkj_conv
	,asgpf1
	,asgpf1_conv
	,asecst
	,asecst_conv
	,asaopn
	,asaopn_conv
	,asdkc
	,asdkc_conv
	,asaa
	,asaa_conv
	,aspn
	,asdsc2
	,asdsc2_conv
	,asaa09
	,asaa09_conv
	,asu
	,asu_conv
	,asaa2
	,asaa2_conv
	,asaa3
	,asaa3_conv
	,aspost
	,aspost_conv
	,asam
	,assblt
	,asre
	,ascrrm
	,asprgf
	,asprgf_conv
	,astx
	,asdgj
	,asdgj_conv
	,asdicj
	,asdicj_conv
	,asdsyj
	,asdsyj_conv
	,ascmtb
	,ascmtb_conv
	,asdate01
	,asdate01_conv
	,asdate02
	,asdate02_conv
	,asdate03
	,asdate03_conv
	,asdate04
	,asdate04_conv
	,asdrqj
	,asdrqj_conv
	,asdsvj
	,asdsvj_conv
	,asdoc
	,asjeln
	,asicu
	,asticu
	,asabo1
	,asctry
	,asfy
	,asfy_conv
	,asodoc
	,astxitm
	,astxitm_conv
	,asacr
	,asacr_conv
	,asdlnid
	,asdlnid_conv
	,asancr
	,asrsht
	,asrsht_conv
	,astday
	,asbct
	,asbct_conv
	,asurab
	,asurab_conv
	,asaa1
	,asaa1_conv
	,asfea
	,asfea_conv
	,asfec
	,asfec_conv
	,asfrec
	,asfrec_conv
	,askco
	,askco_conv
	,asdct
	,asextl
	,asextl_conv
	,asicut
	,asco
	,asco_conv
	,asani
	,asani_conv
	,asaid
	,asaid_conv
	,asmcu
	,asmcu_conv
	,asobj
	,asobj_conv
	,assub
	,assub_conv
	,aslt
	,ascrcd
	,ascrcd_conv
	,asum
	,asptc
	,asptc_conv
	,asglc
	,asglc_conv
	,asexa
	,asexa_conv
	,asexr
	,asexr_conv
	,asr1
	,asr1_conv
	,asr2
	,asr2_conv
	,asr3
	,asr3_conv
	,asodct
	,asosfx
	,asosfx_conv
	,aspkco
	,aspkco_conv
	,asokco
	,asokco_conv
	,aspdct
	,astorg
	,astorg_conv
	,asuser
	,asuser_conv
	,aspid
	,aspid_conv
	,asupmt
	,asjobn
	,asjobn_conv
	,asupmj
	,asupmj_conv
	,asbcrc
	,asbcrc_conv
	,astxa1
	,astxa1_conv
	,asexr1
	,asacatt3ds
	,asacatt3ds_conv
	,asacatt4ds
	,asacatt4ds_conv
	,asacatt5ds
	,asacatt5ds_conv
	,asvr02
	,asvr02_conv
	,asemcu
	,asemcu_conv
	,asahbu
	,asahbu_conv
	,asomcu
	,asomcu_conv
	,asctr
	,asurcd
	,asurcd_conv
	,asaad
	,asaad_conv
	,ascord
	,asgflag1
	,asgflag1_conv
	,asflag
	,asflag_conv
	,asev01
	,asev01_conv
	,asev02
	,asev02_conv
	,asev03
	,asev03_conv
	,asev04
	,asev04_conv
	,asev05
	,asev05_conv
	,asev06
	,asev06_conv
	,asev07
	,asev07_conv
	,asev08
	,asev08_conv
	,asev09
	,asev09_conv
	,asev10
	,asev10_conv
	,asaa03
	,asaa03_conv
	,asaa05
	,asaa05_conv
	,asaa06
	,asaa06_conv
	,asaa07
	,asaa07_conv
	,asaa08
	,asaa08_conv
	,asaa10
	,asaa10_conv
	,asada1
	,asada1_conv
	,asada2
	,asada2_conv
	,asada3
	,asada3_conv
	,asdate05
	,asdate05_conv
	,asdate1
	,asdate1_conv
	,asdate2
	,asdate2_conv
	,asdate3
	,asdate3_conv
	,asmath01
	,asmath01_conv
	,asmath04
	,asmath04_conv
	,asmath05
	,asmath05_conv
	,asmath08
	,asmath08_conv
	,asmath09
	,asmath09_conv
	,asy55strg1
	,asy55strg1_conv
	,asy55strg3
	,asy55strg3_conv
	,asy55strg4
	,asy55strg4_conv
	,asy55strg5
	,asy55strg5_conv
	,asy55strg6
	,asy55strg6_conv
	,asy55strg7
	,asy55strg7_conv
	,asy55strg8
	,asy55strg8_conv
	,asy55strg9
	,asy55strg9_conv
	,asy55date1
	,asy55date1_conv
	,asy55date2
	,asy55date2_conv
	,asy55time1
	,asy55time2
	,asy55char1
	,asy55char1_conv
	,asy55char2
	,asy55char2_conv
	,asy55amnt1
	,asy55amnt1_conv
	,asy55amnt2
	,asy55amnt2_conv
	,asy55amnt3
	,asy55amnt3_conv
	,asy55amnt4
	,asy55amnt4_conv
	,asunap
	,asunap_conv
	,asuntprcsr
	,asuntprcsr_conv
	,asgrwt
	,asgrwt_conv
	,ascrec
	,ascrec_conv
	,asamc3
	,asamc3_conv
	,asurlv
	,asurlv_conv
	,asuchg
	,asuchg_conv
	,asprrc
	,asprrc_conv
	,asdoco
	,asdcto
	,askcoo
	,askcoo_conv
	,aslnid
	,aslnid_conv
	,asatcdname
	,asatcdname_conv
	,asy55uncs
	,asy55uncs_conv
	,asy55uncs3
	,asy55uncs3_conv
	,asy55uncs4
	,asy55uncs4_conv
	,asy55uncs5
	,asy55uncs5_conv
	,asy55uncs6
	,asy55uncs6_conv
	,asy55uncs7
	,asy55uncs7_conv
	,asy55uncs8
	,asy55uncs8_conv
	,asy55uncs9
	,asy55uncs9_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.asaddj
	,cdc.asaddj_conv
	,cdc.asan83
	,cdc.asedtg
	,cdc.asedtg_conv
	,cdc.asukid
	,cdc.asy55strg2
	,cdc.asy55strg2_conv
	,cdc.asitm
	,cdc.aslitm
	,cdc.aslitm_conv
	,cdc.asaitm
	,cdc.asaitm_conv
	,cdc.asdsc1
	,cdc.asdsc1_conv
	,cdc.asmath80
	,cdc.asmath80_conv
	,cdc.asan8
	,cdc.asaa04
	,cdc.asaa04_conv
	,cdc.asdscrp3
	,cdc.asdscrp3_conv
	,cdc.asdscrp4
	,cdc.asdscrp4_conv
	,cdc.asuncs
	,cdc.asuncs_conv
	,cdc.asuopn
	,cdc.asuopn_conv
	,cdc.asuorg
	,cdc.asuorg_conv
	,cdc.asmath02
	,cdc.asmath02_conv
	,cdc.asmath03
	,cdc.asmath03_conv
	,cdc.asaexp
	,cdc.asaexp_conv
	,cdc.asacatt1ds
	,cdc.asacatt1ds_conv
	,cdc.asacatt2ds
	,cdc.asacatt2ds_conv
	,cdc.asacpr
	,cdc.asacpr_conv
	,cdc.asfsrrc
	,cdc.asfsrrc_conv
	,cdc.asacqow
	,cdc.asacqow_conv
	,cdc.asaarc
	,cdc.asaarc_conv
	,cdc.asacrc
	,cdc.asacrc_conv
	,cdc.asacrg
	,cdc.asacrg_conv
	,cdc.asacrtb
	,cdc.asacrtb_conv
	,cdc.asaabr
	,cdc.asaabr_conv
	,cdc.asactur
	,cdc.asactur_conv
	,cdc.asacvl
	,cdc.asacvl_conv
	,cdc.asphrase
	,cdc.asphrase_conv
	,cdc.asmcdtl
	,cdc.asmcdtl_conv
	,cdc.assubtxt
	,cdc.assubtxt_conv
	,cdc.asdes1
	,cdc.asdes1_conv
	,cdc.asdes3
	,cdc.asdes3_conv
	,cdc.asprna1
	,cdc.asprna1_conv
	,cdc.asdes2
	,cdc.asdes2_conv
	,cdc.asan82
	,cdc.asgflag2
	,cdc.asgflag2_conv
	,cdc.asafe
	,cdc.asafe_conv
	,cdc.aslnty
	,cdc.aslnty_conv
	,cdc.asaa12
	,cdc.asaa12_conv
	,cdc.asvr01
	,cdc.asvr01_conv
	,cdc.asgfl8
	,cdc.asgfl8_conv
	,cdc.asmath10
	,cdc.asmath10_conv
	,cdc.asuprc
	,cdc.asuprc_conv
	,cdc.asfrrc
	,cdc.asfrrc_conv
	,cdc.asamrate
	,cdc.asamrate_conv
	,cdc.asxcpr
	,cdc.asxcpr_conv
	,cdc.asacrd
	,cdc.asacrd_conv
	,cdc.asfup
	,cdc.asfup_conv
	,cdc.asofup
	,cdc.asofup_conv
	,cdc.asachg
	,cdc.asachg_conv
	,cdc.assbl
	,cdc.assbl_conv
	,cdc.asaa02
	,cdc.asaa02_conv
	,cdc.asmath07
	,cdc.asmath07_conv
	,cdc.asmath06
	,cdc.asmath06_conv
	,cdc.asanby
	,cdc.asctime
	,cdc.asctime_conv
	,cdc.asbgtime
	,cdc.asapptime
	,cdc.asacttime
	,cdc.asacttime_conv
	,cdc.asdkj
	,cdc.asdkj_conv
	,cdc.asgpf1
	,cdc.asgpf1_conv
	,cdc.asecst
	,cdc.asecst_conv
	,cdc.asaopn
	,cdc.asaopn_conv
	,cdc.asdkc
	,cdc.asdkc_conv
	,cdc.asaa
	,cdc.asaa_conv
	,cdc.aspn
	,cdc.asdsc2
	,cdc.asdsc2_conv
	,cdc.asaa09
	,cdc.asaa09_conv
	,cdc.asu
	,cdc.asu_conv
	,cdc.asaa2
	,cdc.asaa2_conv
	,cdc.asaa3
	,cdc.asaa3_conv
	,cdc.aspost
	,cdc.aspost_conv
	,cdc.asam
	,cdc.assblt
	,cdc.asre
	,cdc.ascrrm
	,cdc.asprgf
	,cdc.asprgf_conv
	,cdc.astx
	,cdc.asdgj
	,cdc.asdgj_conv
	,cdc.asdicj
	,cdc.asdicj_conv
	,cdc.asdsyj
	,cdc.asdsyj_conv
	,cdc.ascmtb
	,cdc.ascmtb_conv
	,cdc.asdate01
	,cdc.asdate01_conv
	,cdc.asdate02
	,cdc.asdate02_conv
	,cdc.asdate03
	,cdc.asdate03_conv
	,cdc.asdate04
	,cdc.asdate04_conv
	,cdc.asdrqj
	,cdc.asdrqj_conv
	,cdc.asdsvj
	,cdc.asdsvj_conv
	,cdc.asdoc
	,cdc.asjeln
	,cdc.asicu
	,cdc.asticu
	,cdc.asabo1
	,cdc.asctry
	,cdc.asfy
	,cdc.asfy_conv
	,cdc.asodoc
	,cdc.astxitm
	,cdc.astxitm_conv
	,cdc.asacr
	,cdc.asacr_conv
	,cdc.asdlnid
	,cdc.asdlnid_conv
	,cdc.asancr
	,cdc.asrsht
	,cdc.asrsht_conv
	,cdc.astday
	,cdc.asbct
	,cdc.asbct_conv
	,cdc.asurab
	,cdc.asurab_conv
	,cdc.asaa1
	,cdc.asaa1_conv
	,cdc.asfea
	,cdc.asfea_conv
	,cdc.asfec
	,cdc.asfec_conv
	,cdc.asfrec
	,cdc.asfrec_conv
	,cdc.askco
	,cdc.askco_conv
	,cdc.asdct
	,cdc.asextl
	,cdc.asextl_conv
	,cdc.asicut
	,cdc.asco
	,cdc.asco_conv
	,cdc.asani
	,cdc.asani_conv
	,cdc.asaid
	,cdc.asaid_conv
	,cdc.asmcu
	,cdc.asmcu_conv
	,cdc.asobj
	,cdc.asobj_conv
	,cdc.assub
	,cdc.assub_conv
	,cdc.aslt
	,cdc.ascrcd
	,cdc.ascrcd_conv
	,cdc.asum
	,cdc.asptc
	,cdc.asptc_conv
	,cdc.asglc
	,cdc.asglc_conv
	,cdc.asexa
	,cdc.asexa_conv
	,cdc.asexr
	,cdc.asexr_conv
	,cdc.asr1
	,cdc.asr1_conv
	,cdc.asr2
	,cdc.asr2_conv
	,cdc.asr3
	,cdc.asr3_conv
	,cdc.asodct
	,cdc.asosfx
	,cdc.asosfx_conv
	,cdc.aspkco
	,cdc.aspkco_conv
	,cdc.asokco
	,cdc.asokco_conv
	,cdc.aspdct
	,cdc.astorg
	,cdc.astorg_conv
	,cdc.asuser
	,cdc.asuser_conv
	,cdc.aspid
	,cdc.aspid_conv
	,cdc.asupmt
	,cdc.asjobn
	,cdc.asjobn_conv
	,cdc.asupmj
	,cdc.asupmj_conv
	,cdc.asbcrc
	,cdc.asbcrc_conv
	,cdc.astxa1
	,cdc.astxa1_conv
	,cdc.asexr1
	,cdc.asacatt3ds
	,cdc.asacatt3ds_conv
	,cdc.asacatt4ds
	,cdc.asacatt4ds_conv
	,cdc.asacatt5ds
	,cdc.asacatt5ds_conv
	,cdc.asvr02
	,cdc.asvr02_conv
	,cdc.asemcu
	,cdc.asemcu_conv
	,cdc.asahbu
	,cdc.asahbu_conv
	,cdc.asomcu
	,cdc.asomcu_conv
	,cdc.asctr
	,cdc.asurcd
	,cdc.asurcd_conv
	,cdc.asaad
	,cdc.asaad_conv
	,cdc.ascord
	,cdc.asgflag1
	,cdc.asgflag1_conv
	,cdc.asflag
	,cdc.asflag_conv
	,cdc.asev01
	,cdc.asev01_conv
	,cdc.asev02
	,cdc.asev02_conv
	,cdc.asev03
	,cdc.asev03_conv
	,cdc.asev04
	,cdc.asev04_conv
	,cdc.asev05
	,cdc.asev05_conv
	,cdc.asev06
	,cdc.asev06_conv
	,cdc.asev07
	,cdc.asev07_conv
	,cdc.asev08
	,cdc.asev08_conv
	,cdc.asev09
	,cdc.asev09_conv
	,cdc.asev10
	,cdc.asev10_conv
	,cdc.asaa03
	,cdc.asaa03_conv
	,cdc.asaa05
	,cdc.asaa05_conv
	,cdc.asaa06
	,cdc.asaa06_conv
	,cdc.asaa07
	,cdc.asaa07_conv
	,cdc.asaa08
	,cdc.asaa08_conv
	,cdc.asaa10
	,cdc.asaa10_conv
	,cdc.asada1
	,cdc.asada1_conv
	,cdc.asada2
	,cdc.asada2_conv
	,cdc.asada3
	,cdc.asada3_conv
	,cdc.asdate05
	,cdc.asdate05_conv
	,cdc.asdate1
	,cdc.asdate1_conv
	,cdc.asdate2
	,cdc.asdate2_conv
	,cdc.asdate3
	,cdc.asdate3_conv
	,cdc.asmath01
	,cdc.asmath01_conv
	,cdc.asmath04
	,cdc.asmath04_conv
	,cdc.asmath05
	,cdc.asmath05_conv
	,cdc.asmath08
	,cdc.asmath08_conv
	,cdc.asmath09
	,cdc.asmath09_conv
	,cdc.asy55strg1
	,cdc.asy55strg1_conv
	,cdc.asy55strg3
	,cdc.asy55strg3_conv
	,cdc.asy55strg4
	,cdc.asy55strg4_conv
	,cdc.asy55strg5
	,cdc.asy55strg5_conv
	,cdc.asy55strg6
	,cdc.asy55strg6_conv
	,cdc.asy55strg7
	,cdc.asy55strg7_conv
	,cdc.asy55strg8
	,cdc.asy55strg8_conv
	,cdc.asy55strg9
	,cdc.asy55strg9_conv
	,cdc.asy55date1
	,cdc.asy55date1_conv
	,cdc.asy55date2
	,cdc.asy55date2_conv
	,cdc.asy55time1
	,cdc.asy55time2
	,cdc.asy55char1
	,cdc.asy55char1_conv
	,cdc.asy55char2
	,cdc.asy55char2_conv
	,cdc.asy55amnt1
	,cdc.asy55amnt1_conv
	,cdc.asy55amnt2
	,cdc.asy55amnt2_conv
	,cdc.asy55amnt3
	,cdc.asy55amnt3_conv
	,cdc.asy55amnt4
	,cdc.asy55amnt4_conv
	,cdc.asunap
	,cdc.asunap_conv
	,cdc.asuntprcsr
	,cdc.asuntprcsr_conv
	,cdc.asgrwt
	,cdc.asgrwt_conv
	,cdc.ascrec
	,cdc.ascrec_conv
	,cdc.asamc3
	,cdc.asamc3_conv
	,cdc.asurlv
	,cdc.asurlv_conv
	,cdc.asuchg
	,cdc.asuchg_conv
	,cdc.asprrc
	,cdc.asprrc_conv
	,cdc.asdoco
	,cdc.asdcto
	,cdc.askcoo
	,cdc.askcoo_conv
	,cdc.aslnid
	,cdc.aslnid_conv
	,cdc.asatcdname
	,cdc.asatcdname_conv
	,cdc.asy55uncs
	,cdc.asy55uncs_conv
	,cdc.asy55uncs3
	,cdc.asy55uncs3_conv
	,cdc.asy55uncs4
	,cdc.asy55uncs4_conv
	,cdc.asy55uncs5
	,cdc.asy55uncs5_conv
	,cdc.asy55uncs6
	,cdc.asy55uncs6_conv
	,cdc.asy55uncs7
	,cdc.asy55uncs7_conv
	,cdc.asy55uncs8
	,cdc.asy55uncs8_conv
	,cdc.asy55uncs9
	,cdc.asy55uncs9_conv
FROM stg_jde_qat.tmp_upsert_f554347_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f554347_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f554347_new AF:{{ task_instance_key_str }}' ) 