-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f554922_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,scmcu
	,scmcu_conv
	,scctr
	,scaddz
	,scaddz_conv
	,sceftj
	,sceftj_conv
	,scexdj
	,scexdj_conv
	,scdstn
	,scum
	,scy55char1
	,scy55char1_conv
	,scy55char2
	,scy55char2_conv
	,scy55strg1
	,scy55strg1_conv
	,scy55strg2
	,scy55strg2_conv
	,scy55amnt1
	,scy55amnt1_conv
	,scy55amnt2
	,scy55amnt2_conv
	,scy55time1
	,scy55time2
	,scy55date1
	,scy55date1_conv
	,scy55date2
	,scy55date2_conv
	,scurrf
	,scurrf_conv
	,scurdt
	,scurdt_conv
	,scurcd
	,scurcd_conv
	,scurab
	,scurab_conv
	,scurat
	,scurat_conv
	,scuser
	,scuser_conv
	,scpid
	,scpid_conv
	,scjobn
	,scjobn_conv
	,scupmj
	,scupmj_conv
	,scupmt
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.scmcu
	,cdc.scmcu_conv
	,cdc.scctr
	,cdc.scaddz
	,cdc.scaddz_conv
	,cdc.sceftj
	,cdc.sceftj_conv
	,cdc.scexdj
	,cdc.scexdj_conv
	,cdc.scdstn
	,cdc.scum
	,cdc.scy55char1
	,cdc.scy55char1_conv
	,cdc.scy55char2
	,cdc.scy55char2_conv
	,cdc.scy55strg1
	,cdc.scy55strg1_conv
	,cdc.scy55strg2
	,cdc.scy55strg2_conv
	,cdc.scy55amnt1
	,cdc.scy55amnt1_conv
	,cdc.scy55amnt2
	,cdc.scy55amnt2_conv
	,cdc.scy55time1
	,cdc.scy55time2
	,cdc.scy55date1
	,cdc.scy55date1_conv
	,cdc.scy55date2
	,cdc.scy55date2_conv
	,cdc.scurrf
	,cdc.scurrf_conv
	,cdc.scurdt
	,cdc.scurdt_conv
	,cdc.scurcd
	,cdc.scurcd_conv
	,cdc.scurab
	,cdc.scurab_conv
	,cdc.scurat
	,cdc.scurat_conv
	,cdc.scuser
	,cdc.scuser_conv
	,cdc.scpid
	,cdc.scpid_conv
	,cdc.scjobn
	,cdc.scjobn_conv
	,cdc.scupmj
	,cdc.scupmj_conv
	,cdc.scupmt
FROM stg_jde_qat.tmp_upsert_f554922_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f554922_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f554922_new AF:{{ task_instance_key_str }}' ) 