-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde_qat.f9210_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,frdtai
	,frdtai_conv
	,frclas
	,frclas_conv
	,frdtat
	,frdtas
	,frdtad
	,frpdta
	,frpdta_conv
	,frarrn
	,frdval
	,frdval_conv
	,frlr
	,frcdec
	,frcdec_conv
	,frdrul
	,frdro1
	,frdro1_conv
	,frerul
	,frero1
	,frero1_conv
	,frero2
	,frero2_conv
	,frhlp1
	,frhlp1_conv
	,frhlp2
	,frhlp2_conv
	,frnnix
	,frnsy
	,frrls
	,fruser
	,fruser_conv
	,frupmj
	,frupmj_conv
	,frpid
	,frpid_conv
	,frjobn
	,frjobn_conv
	,frupmt
	,frowdi
	,frowdi_conv
	,frowtp
	,frcntt
	,frcntt_conv
	,frscfg
	,frscfg_conv
	,fruper
	,fruper_conv
	,fralbk
	,fralbk_conv
	,frower
	,froer1
	,froer1_conv
	,froer2
	,froer2_conv
	,frowdr
	,frodr1
	,frodr1_conv
	,frdbid
	,frdbid_conv
	,frbfdn
	,frbfdn_conv
	,frebid
	,frebid_conv
	,frbfen
	,frbfen_conv
	,frsfid
	,frsfid_conv
	,frsfmn
	,frsfmn_conv
	,frbvid
	,frbvid_conv
	,frbvnm
	,frbvnm_conv
	,frplfg
	,frplfg_conv
	,frddid
	,frddid_conv
	,frauin
	,frauin_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.frdtai
	,cdc.frdtai_conv
	,cdc.frclas
	,cdc.frclas_conv
	,cdc.frdtat
	,cdc.frdtas
	,cdc.frdtad
	,cdc.frpdta
	,cdc.frpdta_conv
	,cdc.frarrn
	,cdc.frdval
	,cdc.frdval_conv
	,cdc.frlr
	,cdc.frcdec
	,cdc.frcdec_conv
	,cdc.frdrul
	,cdc.frdro1
	,cdc.frdro1_conv
	,cdc.frerul
	,cdc.frero1
	,cdc.frero1_conv
	,cdc.frero2
	,cdc.frero2_conv
	,cdc.frhlp1
	,cdc.frhlp1_conv
	,cdc.frhlp2
	,cdc.frhlp2_conv
	,cdc.frnnix
	,cdc.frnsy
	,cdc.frrls
	,cdc.fruser
	,cdc.fruser_conv
	,cdc.frupmj
	,cdc.frupmj_conv
	,cdc.frpid
	,cdc.frpid_conv
	,cdc.frjobn
	,cdc.frjobn_conv
	,cdc.frupmt
	,cdc.frowdi
	,cdc.frowdi_conv
	,cdc.frowtp
	,cdc.frcntt
	,cdc.frcntt_conv
	,cdc.frscfg
	,cdc.frscfg_conv
	,cdc.fruper
	,cdc.fruper_conv
	,cdc.fralbk
	,cdc.fralbk_conv
	,cdc.frower
	,cdc.froer1
	,cdc.froer1_conv
	,cdc.froer2
	,cdc.froer2_conv
	,cdc.frowdr
	,cdc.frodr1
	,cdc.frodr1_conv
	,cdc.frdbid
	,cdc.frdbid_conv
	,cdc.frbfdn
	,cdc.frbfdn_conv
	,cdc.frebid
	,cdc.frebid_conv
	,cdc.frbfen
	,cdc.frbfen_conv
	,cdc.frsfid
	,cdc.frsfid_conv
	,cdc.frsfmn
	,cdc.frsfmn_conv
	,cdc.frbvid
	,cdc.frbvid_conv
	,cdc.frbvnm
	,cdc.frbvnm_conv
	,cdc.frplfg
	,cdc.frplfg_conv
	,cdc.frddid
	,cdc.frddid_conv
	,cdc.frauin
	,cdc.frauin_conv
FROM stg_jde_qat.tmp_upsert_f9210_cdc cdc
LEFT OUTER JOIN rep_jde_qat.f9210_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde_qat.f9210_new AF:{{ task_instance_key_str }}' ) 