-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde.f0092_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,uluser
	,uluser_conv
	,ulmni
	,ulmni_conv
	,uloutq
	,uloutq_conv
	,uljobq
	,uljobq_conv
	,uljsp
	,uljsp_conv
	,uloutp
	,uloutp_conv
	,ulllvl
	,ullsev
	,ullsev_conv
	,ullmsg
	,ulprtl
	,ulprtl_conv
	,ulul01
	,ulul02
	,ulul03
	,ulul03_conv
	,ulul04
	,ulul04_conv
	,ulul05
	,ulul05_conv
	,ulul06
	,ulul06_conv
	,ulul07
	,ulul07_conv
	,ulul08
	,ulul08_conv
	,ulul09
	,ulul09_conv
	,ulul10
	,ulul10_conv
	,ulul11
	,ulul11_conv
	,ulul12
	,ulul12_conv
	,ulul13
	,ulul13_conv
	,ulul14
	,ulul14_conv
	,ulul15
	,ulul15_conv
	,ulul16
	,ulul16_conv
	,ulul17
	,ulul17_conv
	,ulul18
	,ulul18_conv
	,ulul19
	,ulul19_conv
	,ulul20
	,ulul20_conv
	,ulul21
	,ulul21_conv
	,ulul22
	,ulul22_conv
	,ulul23
	,ulul23_conv
	,ulul24
	,ulul24_conv
	,ulul25
	,ulul25_conv
	,ulmska
	,ulmska_conv
	,ulmskj
	,ulmskj_conv
	,ulmskk
	,ulmskk_conv
	,ulmskd
	,ulmskd_conv
	,ulmskf
	,ulan8
	,ulutyp
	,ulutyp_conv
	,ulpid
	,ulpid_conv
	,ulmtvl
	,ulmtvl_conv
	,ulcmde
	,ulcmde_conv
	,ulclib
	,ulclib_conv
	,ulugrp
	,ulugrp_conv
	,ulipgm
	,ulipgm_conv
	,ullod
	,ulfstp
	,ulfstp_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.uluser
	,cdc.uluser_conv
	,cdc.ulmni
	,cdc.ulmni_conv
	,cdc.uloutq
	,cdc.uloutq_conv
	,cdc.uljobq
	,cdc.uljobq_conv
	,cdc.uljsp
	,cdc.uljsp_conv
	,cdc.uloutp
	,cdc.uloutp_conv
	,cdc.ulllvl
	,cdc.ullsev
	,cdc.ullsev_conv
	,cdc.ullmsg
	,cdc.ulprtl
	,cdc.ulprtl_conv
	,cdc.ulul01
	,cdc.ulul02
	,cdc.ulul03
	,cdc.ulul03_conv
	,cdc.ulul04
	,cdc.ulul04_conv
	,cdc.ulul05
	,cdc.ulul05_conv
	,cdc.ulul06
	,cdc.ulul06_conv
	,cdc.ulul07
	,cdc.ulul07_conv
	,cdc.ulul08
	,cdc.ulul08_conv
	,cdc.ulul09
	,cdc.ulul09_conv
	,cdc.ulul10
	,cdc.ulul10_conv
	,cdc.ulul11
	,cdc.ulul11_conv
	,cdc.ulul12
	,cdc.ulul12_conv
	,cdc.ulul13
	,cdc.ulul13_conv
	,cdc.ulul14
	,cdc.ulul14_conv
	,cdc.ulul15
	,cdc.ulul15_conv
	,cdc.ulul16
	,cdc.ulul16_conv
	,cdc.ulul17
	,cdc.ulul17_conv
	,cdc.ulul18
	,cdc.ulul18_conv
	,cdc.ulul19
	,cdc.ulul19_conv
	,cdc.ulul20
	,cdc.ulul20_conv
	,cdc.ulul21
	,cdc.ulul21_conv
	,cdc.ulul22
	,cdc.ulul22_conv
	,cdc.ulul23
	,cdc.ulul23_conv
	,cdc.ulul24
	,cdc.ulul24_conv
	,cdc.ulul25
	,cdc.ulul25_conv
	,cdc.ulmska
	,cdc.ulmska_conv
	,cdc.ulmskj
	,cdc.ulmskj_conv
	,cdc.ulmskk
	,cdc.ulmskk_conv
	,cdc.ulmskd
	,cdc.ulmskd_conv
	,cdc.ulmskf
	,cdc.ulan8
	,cdc.ulutyp
	,cdc.ulutyp_conv
	,cdc.ulpid
	,cdc.ulpid_conv
	,cdc.ulmtvl
	,cdc.ulmtvl_conv
	,cdc.ulcmde
	,cdc.ulcmde_conv
	,cdc.ulclib
	,cdc.ulclib_conv
	,cdc.ulugrp
	,cdc.ulugrp_conv
	,cdc.ulipgm
	,cdc.ulipgm_conv
	,cdc.ullod
	,cdc.ulfstp
	,cdc.ulfstp_conv
FROM stg_jde.tmp_upsert_f0092_cdc cdc
LEFT OUTER JOIN rep_jde.f0092_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde.f0092_new AF:{{ task_instance_key_str }}' ) 