-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde.f0413_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,rmpyid
	,rmdctm
	,rmdocm
	,rmpye
	,rmglba
	,rmglba_conv
	,rmdmtj
	,rmdmtj_conv
	,rmvdgj
	,rmvdgj_conv
	,rmicu
	,rmicut
	,rmdicj
	,rmdicj_conv
	,rmpaap
	,rmpaap_conv
	,rmcrcd
	,rmcrcd_conv
	,rmcrrm
	,rmam
	,rmvldt
	,rmvldt_conv
	,rmpyin
	,rmistp
	,rmistp_conv
	,rmcbnk
	,rmcbnk_conv
	,rmbktr
	,rmbktr_conv
	,rmtorg
	,rmtorg_conv
	,rmuser
	,rmuser_conv
	,rmpid
	,rmpid_conv
	,rmupmj
	,rmupmj_conv
	,rmupmt
	,rmjobn
	,rmjobn_conv
	,rmmip
	,rmmip_conv
	,rmlrfl
	,rmlrfl_conv
	,rmprgf
	,rmprgf_conv
	,rmgfl7
	,rmgfl7_conv
	,rmgfl8
	,rmgfl8_conv
	,rmgam3
	,rmgam3_conv
	,rmgam4
	,rmgam4_conv
	,rmgen6
	,rmgen6_conv
	,rmgen7
	,rmgen7_conv
	,rmnettcid
	,rmnettcid_conv
	,rmnetdoc
	,rmnetdoc_conv
	,rmrcnd
	,rmr3
	,rmr3_conv
	,rmcntrtid
	,rmcntrtid_conv
	,rmcntrtcd
	,rmcntrtcd_conv
	,rmwvid
	,rmwvid_conv
	,rmblscd2
	,rmblscd2_conv
	,rmharper
	,rmharper_conv
	,rmharsfx
	,rmharsfx_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.rmpyid
	,cdc.rmdctm
	,cdc.rmdocm
	,cdc.rmpye
	,cdc.rmglba
	,cdc.rmglba_conv
	,cdc.rmdmtj
	,cdc.rmdmtj_conv
	,cdc.rmvdgj
	,cdc.rmvdgj_conv
	,cdc.rmicu
	,cdc.rmicut
	,cdc.rmdicj
	,cdc.rmdicj_conv
	,cdc.rmpaap
	,cdc.rmpaap_conv
	,cdc.rmcrcd
	,cdc.rmcrcd_conv
	,cdc.rmcrrm
	,cdc.rmam
	,cdc.rmvldt
	,cdc.rmvldt_conv
	,cdc.rmpyin
	,cdc.rmistp
	,cdc.rmistp_conv
	,cdc.rmcbnk
	,cdc.rmcbnk_conv
	,cdc.rmbktr
	,cdc.rmbktr_conv
	,cdc.rmtorg
	,cdc.rmtorg_conv
	,cdc.rmuser
	,cdc.rmuser_conv
	,cdc.rmpid
	,cdc.rmpid_conv
	,cdc.rmupmj
	,cdc.rmupmj_conv
	,cdc.rmupmt
	,cdc.rmjobn
	,cdc.rmjobn_conv
	,cdc.rmmip
	,cdc.rmmip_conv
	,cdc.rmlrfl
	,cdc.rmlrfl_conv
	,cdc.rmprgf
	,cdc.rmprgf_conv
	,cdc.rmgfl7
	,cdc.rmgfl7_conv
	,cdc.rmgfl8
	,cdc.rmgfl8_conv
	,cdc.rmgam3
	,cdc.rmgam3_conv
	,cdc.rmgam4
	,cdc.rmgam4_conv
	,cdc.rmgen6
	,cdc.rmgen6_conv
	,cdc.rmgen7
	,cdc.rmgen7_conv
	,cdc.rmnettcid
	,cdc.rmnettcid_conv
	,cdc.rmnetdoc
	,cdc.rmnetdoc_conv
	,cdc.rmrcnd
	,cdc.rmr3
	,cdc.rmr3_conv
	,cdc.rmcntrtid
	,cdc.rmcntrtid_conv
	,cdc.rmcntrtcd
	,cdc.rmcntrtcd_conv
	,cdc.rmwvid
	,cdc.rmwvid_conv
	,cdc.rmblscd2
	,cdc.rmblscd2_conv
	,cdc.rmharper
	,cdc.rmharper_conv
	,cdc.rmharsfx
	,cdc.rmharsfx_conv
FROM stg_jde.tmp_upsert_f0413_cdc cdc
LEFT OUTER JOIN rep_jde.f0413_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde.f0413_new AF:{{ task_instance_key_str }}' ) 