-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde.f1207_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,fwnumb
	,fwapid
	,fwapid_conv
	,fwasid
	,fwasid_conv
	,fwsrvt
	,fwmsts
	,fwmpri
	,fwky
	,fwky_conv
	,fwanp
	,fwrmk
	,fwrmk_conv
	,fwsrvd
	,fwsrvd_conv
	,fwsrvm
	,fwsrvm_conv
	,fwsrvh
	,fwsrvh_conv
	,fwtdt
	,fwtdt_conv
	,fwcplm
	,fwcplm_conv
	,fwcplh
	,fwcplh_conv
	,fwcpld
	,fwcpld_conv
	,fwlstm
	,fwlstm_conv
	,fwlsth
	,fwlsth_conv
	,fwlcpd
	,fwlcpd_conv
	,fwuser
	,fwuser_conv
	,fwpid
	,fwpid_conv
	,fwupmj
	,fwupmj_conv
	,fwjobn
	,fwjobn_conv
	,fwdoco
	,fwwona
	,fwmpc
	,fwsrvf
	,fwsrvf_conv
	,fwcplf
	,fwcplf_conv
	,fwlstf
	,fwlstf_conv
	,fwmltw
	,fworgm
	,fworgm_conv
	,fworgh
	,fworgh_conv
	,fworgf
	,fworgf_conv
	,fwoccu
	,fwoccu_conv
	,fwfrin
	,fwupmt
	,fwmcu
	,fwmcu_conv
	,fwaaid
	,fwcrtl
	,fwcrtl_conv
	,fwpnst
	,fwpnst_conv
	,fwpmc1
	,fwpmc2
	,fwdnhr
	,fwdnhr_conv
	,fwpdfl
	,fwukid
	,fwtolu
	,fwtolu_conv
	,fwtoll
	,fwtoll_conv
	,fwhldd
	,fwhldd_conv
	,fwsphr
	,fwsphr_conv
	,fwspwk
	,fwspwk_conv
	,fwspmn
	,fwspmn_conv
	,fwwk
	,fwwk_conv
	,fwspdw
	,fwspdw_conv
	,fwpdfg
	,fwsrvm4
	,fwsrvm4_conv
	,fwlstm4
	,fwlstm4_conv
	,fwcplm4
	,fwcplm4_conv
	,fworgm4
	,fworgm4_conv
	,fwsrvm5
	,fwsrvm5_conv
	,fwlstm5
	,fwlstm5_conv
	,fwcplm5
	,fwcplm5_conv
	,fworgm5
	,fworgm5_conv
	,fwsrvm6
	,fwsrvm6_conv
	,fwlstm6
	,fwlstm6_conv
	,fwcplm6
	,fwcplm6_conv
	,fworgm6
	,fworgm6_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.fwnumb
	,cdc.fwapid
	,cdc.fwapid_conv
	,cdc.fwasid
	,cdc.fwasid_conv
	,cdc.fwsrvt
	,cdc.fwmsts
	,cdc.fwmpri
	,cdc.fwky
	,cdc.fwky_conv
	,cdc.fwanp
	,cdc.fwrmk
	,cdc.fwrmk_conv
	,cdc.fwsrvd
	,cdc.fwsrvd_conv
	,cdc.fwsrvm
	,cdc.fwsrvm_conv
	,cdc.fwsrvh
	,cdc.fwsrvh_conv
	,cdc.fwtdt
	,cdc.fwtdt_conv
	,cdc.fwcplm
	,cdc.fwcplm_conv
	,cdc.fwcplh
	,cdc.fwcplh_conv
	,cdc.fwcpld
	,cdc.fwcpld_conv
	,cdc.fwlstm
	,cdc.fwlstm_conv
	,cdc.fwlsth
	,cdc.fwlsth_conv
	,cdc.fwlcpd
	,cdc.fwlcpd_conv
	,cdc.fwuser
	,cdc.fwuser_conv
	,cdc.fwpid
	,cdc.fwpid_conv
	,cdc.fwupmj
	,cdc.fwupmj_conv
	,cdc.fwjobn
	,cdc.fwjobn_conv
	,cdc.fwdoco
	,cdc.fwwona
	,cdc.fwmpc
	,cdc.fwsrvf
	,cdc.fwsrvf_conv
	,cdc.fwcplf
	,cdc.fwcplf_conv
	,cdc.fwlstf
	,cdc.fwlstf_conv
	,cdc.fwmltw
	,cdc.fworgm
	,cdc.fworgm_conv
	,cdc.fworgh
	,cdc.fworgh_conv
	,cdc.fworgf
	,cdc.fworgf_conv
	,cdc.fwoccu
	,cdc.fwoccu_conv
	,cdc.fwfrin
	,cdc.fwupmt
	,cdc.fwmcu
	,cdc.fwmcu_conv
	,cdc.fwaaid
	,cdc.fwcrtl
	,cdc.fwcrtl_conv
	,cdc.fwpnst
	,cdc.fwpnst_conv
	,cdc.fwpmc1
	,cdc.fwpmc2
	,cdc.fwdnhr
	,cdc.fwdnhr_conv
	,cdc.fwpdfl
	,cdc.fwukid
	,cdc.fwtolu
	,cdc.fwtolu_conv
	,cdc.fwtoll
	,cdc.fwtoll_conv
	,cdc.fwhldd
	,cdc.fwhldd_conv
	,cdc.fwsphr
	,cdc.fwsphr_conv
	,cdc.fwspwk
	,cdc.fwspwk_conv
	,cdc.fwspmn
	,cdc.fwspmn_conv
	,cdc.fwwk
	,cdc.fwwk_conv
	,cdc.fwspdw
	,cdc.fwspdw_conv
	,cdc.fwpdfg
	,cdc.fwsrvm4
	,cdc.fwsrvm4_conv
	,cdc.fwlstm4
	,cdc.fwlstm4_conv
	,cdc.fwcplm4
	,cdc.fwcplm4_conv
	,cdc.fworgm4
	,cdc.fworgm4_conv
	,cdc.fwsrvm5
	,cdc.fwsrvm5_conv
	,cdc.fwlstm5
	,cdc.fwlstm5_conv
	,cdc.fwcplm5
	,cdc.fwcplm5_conv
	,cdc.fworgm5
	,cdc.fworgm5_conv
	,cdc.fwsrvm6
	,cdc.fwsrvm6_conv
	,cdc.fwlstm6
	,cdc.fwlstm6_conv
	,cdc.fwcplm6
	,cdc.fwcplm6_conv
	,cdc.fworgm6
	,cdc.fworgm6_conv
FROM stg_jde.tmp_upsert_f1207_cdc cdc
LEFT OUTER JOIN rep_jde.f1207_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde.f1207_new AF:{{ task_instance_key_str }}' ) 