-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde.f3002_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,ixtbm
	,ixkit
	,ixkitl
	,ixkitl_conv
	,ixkita
	,ixkita_conv
	,ixmmcu
	,ixmmcu_conv
	,ixitm
	,ixlitm
	,ixlitm_conv
	,ixaitm
	,ixaitm_conv
	,ixcmcu
	,ixcmcu_conv
	,ixcpnt
	,ixsbnt
	,ixsbnt_conv
	,ixprta
	,ixprta_conv
	,ixqnty
	,ixqnty_conv
	,ixum
	,ixbqty
	,ixbqty_conv
	,ixuom
	,ixfvbt
	,ixfvbt_conv
	,ixefff
	,ixefff_conv
	,ixefft
	,ixefft_conv
	,ixfser
	,ixfser_conv
	,ixtser
	,ixtser_conv
	,ixitc
	,ixftrc
	,ixftrc_conv
	,ixoptk
	,ixforv
	,ixforv_conv
	,ixcstm
	,ixcsmp
	,ixcsmp_conv
	,ixordw
	,ixordw_conv
	,ixforq
	,ixcoby
	,ixcoty
	,ixfrmp
	,ixfrmp_conv
	,ixthrp
	,ixthrp_conv
	,ixfrgd
	,ixthgd
	,ixopsq
	,ixopsq_conv
	,ixbseq
	,ixbseq_conv
	,ixftrp
	,ixftrp_conv
	,ixf_2rp
	,ixf_2rp_conv
	,ixrscp
	,ixrscp_conv
	,ixscrp
	,ixscrp_conv
	,ixrewp
	,ixrewp_conv
	,ixasip
	,ixasip_conv
	,ixcpyp
	,ixcpyp_conv
	,ixstpp
	,ixstpp_conv
	,ixlovd
	,ixlovd_conv
	,ixeco
	,ixeco_conv
	,ixecty
	,ixecod
	,ixecod_conv
	,ixdsc1
	,ixdsc1_conv
	,ixlnty
	,ixlnty_conv
	,ixpric
	,ixpric_conv
	,ixuncs
	,ixuncs_conv
	,ixpctk
	,ixpctk_conv
	,ixshno
	,ixshno_conv
	,ixomcu
	,ixomcu_conv
	,ixobj
	,ixobj_conv
	,ixsub
	,ixsub_conv
	,ixbrev
	,ixbrev_conv
	,ixcmrv
	,ixcmrv_conv
	,ixrvno
	,ixrvno_conv
	,ixuupg
	,ixurcd
	,ixurcd_conv
	,ixurdt
	,ixurdt_conv
	,ixurat
	,ixurat_conv
	,ixurrf
	,ixurrf_conv
	,ixurab
	,ixurab_conv
	,ixuser
	,ixuser_conv
	,ixpid
	,ixpid_conv
	,ixjobn
	,ixjobn_conv
	,ixupmj
	,ixupmj_conv
	,ixtday
	,ixaing
	,ixaing_conv
	,ixsuco
	,ixsuco_conv
	,ixstrc
	,ixstrc_conv
	,ixendc
	,ixendc_conv
	,ixapsc
	,ixcpnb
	,ixcpnb_conv
	,ixbseqan
	,ixbseqan_conv
	,ixbchar
	,ixbchar_conv
	,ixbostr
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.ixtbm
	,cdc.ixkit
	,cdc.ixkitl
	,cdc.ixkitl_conv
	,cdc.ixkita
	,cdc.ixkita_conv
	,cdc.ixmmcu
	,cdc.ixmmcu_conv
	,cdc.ixitm
	,cdc.ixlitm
	,cdc.ixlitm_conv
	,cdc.ixaitm
	,cdc.ixaitm_conv
	,cdc.ixcmcu
	,cdc.ixcmcu_conv
	,cdc.ixcpnt
	,cdc.ixsbnt
	,cdc.ixsbnt_conv
	,cdc.ixprta
	,cdc.ixprta_conv
	,cdc.ixqnty
	,cdc.ixqnty_conv
	,cdc.ixum
	,cdc.ixbqty
	,cdc.ixbqty_conv
	,cdc.ixuom
	,cdc.ixfvbt
	,cdc.ixfvbt_conv
	,cdc.ixefff
	,cdc.ixefff_conv
	,cdc.ixefft
	,cdc.ixefft_conv
	,cdc.ixfser
	,cdc.ixfser_conv
	,cdc.ixtser
	,cdc.ixtser_conv
	,cdc.ixitc
	,cdc.ixftrc
	,cdc.ixftrc_conv
	,cdc.ixoptk
	,cdc.ixforv
	,cdc.ixforv_conv
	,cdc.ixcstm
	,cdc.ixcsmp
	,cdc.ixcsmp_conv
	,cdc.ixordw
	,cdc.ixordw_conv
	,cdc.ixforq
	,cdc.ixcoby
	,cdc.ixcoty
	,cdc.ixfrmp
	,cdc.ixfrmp_conv
	,cdc.ixthrp
	,cdc.ixthrp_conv
	,cdc.ixfrgd
	,cdc.ixthgd
	,cdc.ixopsq
	,cdc.ixopsq_conv
	,cdc.ixbseq
	,cdc.ixbseq_conv
	,cdc.ixftrp
	,cdc.ixftrp_conv
	,cdc.ixf_2rp
	,cdc.ixf_2rp_conv
	,cdc.ixrscp
	,cdc.ixrscp_conv
	,cdc.ixscrp
	,cdc.ixscrp_conv
	,cdc.ixrewp
	,cdc.ixrewp_conv
	,cdc.ixasip
	,cdc.ixasip_conv
	,cdc.ixcpyp
	,cdc.ixcpyp_conv
	,cdc.ixstpp
	,cdc.ixstpp_conv
	,cdc.ixlovd
	,cdc.ixlovd_conv
	,cdc.ixeco
	,cdc.ixeco_conv
	,cdc.ixecty
	,cdc.ixecod
	,cdc.ixecod_conv
	,cdc.ixdsc1
	,cdc.ixdsc1_conv
	,cdc.ixlnty
	,cdc.ixlnty_conv
	,cdc.ixpric
	,cdc.ixpric_conv
	,cdc.ixuncs
	,cdc.ixuncs_conv
	,cdc.ixpctk
	,cdc.ixpctk_conv
	,cdc.ixshno
	,cdc.ixshno_conv
	,cdc.ixomcu
	,cdc.ixomcu_conv
	,cdc.ixobj
	,cdc.ixobj_conv
	,cdc.ixsub
	,cdc.ixsub_conv
	,cdc.ixbrev
	,cdc.ixbrev_conv
	,cdc.ixcmrv
	,cdc.ixcmrv_conv
	,cdc.ixrvno
	,cdc.ixrvno_conv
	,cdc.ixuupg
	,cdc.ixurcd
	,cdc.ixurcd_conv
	,cdc.ixurdt
	,cdc.ixurdt_conv
	,cdc.ixurat
	,cdc.ixurat_conv
	,cdc.ixurrf
	,cdc.ixurrf_conv
	,cdc.ixurab
	,cdc.ixurab_conv
	,cdc.ixuser
	,cdc.ixuser_conv
	,cdc.ixpid
	,cdc.ixpid_conv
	,cdc.ixjobn
	,cdc.ixjobn_conv
	,cdc.ixupmj
	,cdc.ixupmj_conv
	,cdc.ixtday
	,cdc.ixaing
	,cdc.ixaing_conv
	,cdc.ixsuco
	,cdc.ixsuco_conv
	,cdc.ixstrc
	,cdc.ixstrc_conv
	,cdc.ixendc
	,cdc.ixendc_conv
	,cdc.ixapsc
	,cdc.ixcpnb
	,cdc.ixcpnb_conv
	,cdc.ixbseqan
	,cdc.ixbseqan_conv
	,cdc.ixbchar
	,cdc.ixbchar_conv
	,cdc.ixbostr
FROM stg_jde.tmp_upsert_f3002_cdc cdc
LEFT OUTER JOIN rep_jde.f3002_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde.f3002_new AF:{{ task_instance_key_str }}' ) 