-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde.f30026_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,ieitm
	,ielitm
	,ielitm_conv
	,ieaitm
	,ieaitm_conv
	,iemmcu
	,iemmcu_conv
	,ielocn
	,ielocn_conv
	,ielotn
	,ielotn_conv
	,ieledg
	,iecost
	,ielotg
	,iestdc
	,iestdc_conv
	,iexsmc
	,iexsmc_conv
	,iecsl
	,iecsl_conv
	,iexscr
	,iexscr_conv
	,iesctc
	,iesctc_conv
	,iexsfc
	,iexsfc_conv
	,iestfc
	,iestfc_conv
	,iexsf
	,iexsf_conv
	,ierats
	,ierats_conv
	,iexsrc
	,iexsrc_conv
	,iertsd
	,iertsd_conv
	,iexsr
	,iexsr_conv
	,iepflg
	,ieuser
	,ieuser_conv
	,iepid
	,iepid_conv
	,iejobn
	,iejobn_conv
	,ieupmj
	,ieupmj_conv
	,ietday
	,ieopsq
	,ieopsq_conv
	,iemcul
	,iemcul_conv
	,iewmcu
	,iewmcu_conv
	,ielda
	,ielda_conv
	,ietbm
	,ieacq
	,ieacq_conv
	,ief
	,ief_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.ieitm
	,cdc.ielitm
	,cdc.ielitm_conv
	,cdc.ieaitm
	,cdc.ieaitm_conv
	,cdc.iemmcu
	,cdc.iemmcu_conv
	,cdc.ielocn
	,cdc.ielocn_conv
	,cdc.ielotn
	,cdc.ielotn_conv
	,cdc.ieledg
	,cdc.iecost
	,cdc.ielotg
	,cdc.iestdc
	,cdc.iestdc_conv
	,cdc.iexsmc
	,cdc.iexsmc_conv
	,cdc.iecsl
	,cdc.iecsl_conv
	,cdc.iexscr
	,cdc.iexscr_conv
	,cdc.iesctc
	,cdc.iesctc_conv
	,cdc.iexsfc
	,cdc.iexsfc_conv
	,cdc.iestfc
	,cdc.iestfc_conv
	,cdc.iexsf
	,cdc.iexsf_conv
	,cdc.ierats
	,cdc.ierats_conv
	,cdc.iexsrc
	,cdc.iexsrc_conv
	,cdc.iertsd
	,cdc.iertsd_conv
	,cdc.iexsr
	,cdc.iexsr_conv
	,cdc.iepflg
	,cdc.ieuser
	,cdc.ieuser_conv
	,cdc.iepid
	,cdc.iepid_conv
	,cdc.iejobn
	,cdc.iejobn_conv
	,cdc.ieupmj
	,cdc.ieupmj_conv
	,cdc.ietday
	,cdc.ieopsq
	,cdc.ieopsq_conv
	,cdc.iemcul
	,cdc.iemcul_conv
	,cdc.iewmcu
	,cdc.iewmcu_conv
	,cdc.ielda
	,cdc.ielda_conv
	,cdc.ietbm
	,cdc.ieacq
	,cdc.ieacq_conv
	,cdc.ief
	,cdc.ief_conv
FROM stg_jde.tmp_upsert_f30026_cdc cdc
LEFT OUTER JOIN rep_jde.f30026_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde.f30026_new AF:{{ task_instance_key_str }}' ) 