-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde.f3111_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,wmdoco
	,wmdcto
	,wmsfxo
	,wmsfxo_conv
	,wmtbm
	,wmforq
	,wmitc
	,wmcoby
	,wmcoty
	,wmcpnt
	,wmfrmp
	,wmfrmp_conv
	,wmthrp
	,wmthrp_conv
	,wmfrgd
	,wmthgd
	,wmrkco
	,wmrkco_conv
	,wmrorn
	,wmrorn_conv
	,wmrcto
	,wmrlln
	,wmrlln_conv
	,wmopsq
	,wmopsq_conv
	,wmbseq
	,wmbseq_conv
	,wmrscp
	,wmrscp_conv
	,wmscrp
	,wmscrp_conv
	,wmrewp
	,wmrewp_conv
	,wmasip
	,wmasip_conv
	,wmcpyp
	,wmcpyp_conv
	,wmstpp
	,wmstpp_conv
	,wmlovd
	,wmlovd_conv
	,wmcpit
	,wmcpil
	,wmcpil_conv
	,wmcpia
	,wmcpia_conv
	,wmcmcu
	,wmcmcu_conv
	,wmdsc1
	,wmdsc1_conv
	,wmdsc2
	,wmdsc2_conv
	,wmlocn
	,wmlocn_conv
	,wmlotn
	,wmlotn_conv
	,wman8
	,wmlnty
	,wmlnty_conv
	,wmsern
	,wmsern_conv
	,wmtrdj
	,wmtrdj_conv
	,wmdrqj
	,wmdrqj_conv
	,wmuorg
	,wmuorg_conv
	,wmtrqt
	,wmtrqt_conv
	,wmsocn
	,wmsocn_conv
	,wmsobk
	,wmsobk_conv
	,wmcts1
	,wmcts1_conv
	,wmqnta
	,wmqnta_conv
	,wmum
	,wmea
	,wmea_conv
	,wmrtg
	,wmrtg_conv
	,wmmtst
	,wmdct
	,wmshno
	,wmshno_conv
	,wmmcu
	,wmmcu_conv
	,wmomcu
	,wmomcu_conv
	,wmobj
	,wmobj_conv
	,wmsub
	,wmsub_conv
	,wmcmrv
	,wmcmrv_conv
	,wmstrx
	,wmstrx_conv
	,wmpars
	,wmpars_conv
	,wmcomm
	,wmurcd
	,wmurcd_conv
	,wmurdt
	,wmurdt_conv
	,wmurat
	,wmurat_conv
	,wmurrf
	,wmurrf_conv
	,wmurab
	,wmurab_conv
	,wmuser
	,wmuser_conv
	,wmpid
	,wmpid_conv
	,wmjobn
	,wmjobn_conv
	,wmupmj
	,wmupmj_conv
	,wmtday
	,wmukid
	,wmvend
	,wmvend_conv
	,wmpoc
	,wmcts4
	,wmcts4_conv
	,wmcts7
	,wmcts7_conv
	,wmcts8
	,wmcts8_conv
	,wmgld
	,wmgld_conv
	,wmsbfl
	,wmsbfl_conv
	,wmaing
	,wmaing_conv
	,wmsstq
	,wmsstq_conv
	,wmuom2
	,wmapsc
	,wmpsn
	,wmdlej
	,wmdlej_conv
	,wmcost
	,wmchpp
	,wmchpp_conv
	,wmcpnb
	,wmcpnb_conv
	,wmbseqan
	,wmbseqan_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.wmdoco
	,cdc.wmdcto
	,cdc.wmsfxo
	,cdc.wmsfxo_conv
	,cdc.wmtbm
	,cdc.wmforq
	,cdc.wmitc
	,cdc.wmcoby
	,cdc.wmcoty
	,cdc.wmcpnt
	,cdc.wmfrmp
	,cdc.wmfrmp_conv
	,cdc.wmthrp
	,cdc.wmthrp_conv
	,cdc.wmfrgd
	,cdc.wmthgd
	,cdc.wmrkco
	,cdc.wmrkco_conv
	,cdc.wmrorn
	,cdc.wmrorn_conv
	,cdc.wmrcto
	,cdc.wmrlln
	,cdc.wmrlln_conv
	,cdc.wmopsq
	,cdc.wmopsq_conv
	,cdc.wmbseq
	,cdc.wmbseq_conv
	,cdc.wmrscp
	,cdc.wmrscp_conv
	,cdc.wmscrp
	,cdc.wmscrp_conv
	,cdc.wmrewp
	,cdc.wmrewp_conv
	,cdc.wmasip
	,cdc.wmasip_conv
	,cdc.wmcpyp
	,cdc.wmcpyp_conv
	,cdc.wmstpp
	,cdc.wmstpp_conv
	,cdc.wmlovd
	,cdc.wmlovd_conv
	,cdc.wmcpit
	,cdc.wmcpil
	,cdc.wmcpil_conv
	,cdc.wmcpia
	,cdc.wmcpia_conv
	,cdc.wmcmcu
	,cdc.wmcmcu_conv
	,cdc.wmdsc1
	,cdc.wmdsc1_conv
	,cdc.wmdsc2
	,cdc.wmdsc2_conv
	,cdc.wmlocn
	,cdc.wmlocn_conv
	,cdc.wmlotn
	,cdc.wmlotn_conv
	,cdc.wman8
	,cdc.wmlnty
	,cdc.wmlnty_conv
	,cdc.wmsern
	,cdc.wmsern_conv
	,cdc.wmtrdj
	,cdc.wmtrdj_conv
	,cdc.wmdrqj
	,cdc.wmdrqj_conv
	,cdc.wmuorg
	,cdc.wmuorg_conv
	,cdc.wmtrqt
	,cdc.wmtrqt_conv
	,cdc.wmsocn
	,cdc.wmsocn_conv
	,cdc.wmsobk
	,cdc.wmsobk_conv
	,cdc.wmcts1
	,cdc.wmcts1_conv
	,cdc.wmqnta
	,cdc.wmqnta_conv
	,cdc.wmum
	,cdc.wmea
	,cdc.wmea_conv
	,cdc.wmrtg
	,cdc.wmrtg_conv
	,cdc.wmmtst
	,cdc.wmdct
	,cdc.wmshno
	,cdc.wmshno_conv
	,cdc.wmmcu
	,cdc.wmmcu_conv
	,cdc.wmomcu
	,cdc.wmomcu_conv
	,cdc.wmobj
	,cdc.wmobj_conv
	,cdc.wmsub
	,cdc.wmsub_conv
	,cdc.wmcmrv
	,cdc.wmcmrv_conv
	,cdc.wmstrx
	,cdc.wmstrx_conv
	,cdc.wmpars
	,cdc.wmpars_conv
	,cdc.wmcomm
	,cdc.wmurcd
	,cdc.wmurcd_conv
	,cdc.wmurdt
	,cdc.wmurdt_conv
	,cdc.wmurat
	,cdc.wmurat_conv
	,cdc.wmurrf
	,cdc.wmurrf_conv
	,cdc.wmurab
	,cdc.wmurab_conv
	,cdc.wmuser
	,cdc.wmuser_conv
	,cdc.wmpid
	,cdc.wmpid_conv
	,cdc.wmjobn
	,cdc.wmjobn_conv
	,cdc.wmupmj
	,cdc.wmupmj_conv
	,cdc.wmtday
	,cdc.wmukid
	,cdc.wmvend
	,cdc.wmvend_conv
	,cdc.wmpoc
	,cdc.wmcts4
	,cdc.wmcts4_conv
	,cdc.wmcts7
	,cdc.wmcts7_conv
	,cdc.wmcts8
	,cdc.wmcts8_conv
	,cdc.wmgld
	,cdc.wmgld_conv
	,cdc.wmsbfl
	,cdc.wmsbfl_conv
	,cdc.wmaing
	,cdc.wmaing_conv
	,cdc.wmsstq
	,cdc.wmsstq_conv
	,cdc.wmuom2
	,cdc.wmapsc
	,cdc.wmpsn
	,cdc.wmdlej
	,cdc.wmdlej_conv
	,cdc.wmcost
	,cdc.wmchpp
	,cdc.wmchpp_conv
	,cdc.wmcpnb
	,cdc.wmcpnb_conv
	,cdc.wmbseqan
	,cdc.wmbseqan_conv
FROM stg_jde.tmp_upsert_f3111_cdc cdc
LEFT OUTER JOIN rep_jde.f3111_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde.f3111_new AF:{{ task_instance_key_str }}' ) 