-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde.f3411_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,mmukid
	,mmitm
	,mmmcu
	,mmmcu_conv
	,mmmmcu
	,mmmmcu_conv
	,mmmsgt
	,mmmsga
	,mmhcld
	,mmkcoo
	,mmkcoo_conv
	,mmdoco
	,mmdcto
	,mmlnid
	,mmlnid_conv
	,mmsfxo
	,mmsfxo_conv
	,mmdsc1
	,mmdsc1_conv
	,mmtrqt
	,mmtrqt_conv
	,mmvend
	,mmvend_conv
	,mmdrqj
	,mmdrqj_conv
	,mmstrt
	,mmstrt_conv
	,mmrstj
	,mmrstj_conv
	,mmrrqj
	,mmrrqj_conv
	,mmupmj
	,mmupmj_conv
	,mmtday
	,mmuser
	,mmuser_conv
	,mmjobn
	,mmjobn_conv
	,mmpid
	,mmpid_conv
	,mmredj
	,mmredj_conv
	,mmoedj
	,mmoedj_conv
	,mmline
	,mmline_conv
	,mmprjm
	,mmprjm_conv
	,mmsrdm
	,mmsrdm_conv
	,mmostt
	,mmostt_conv
	,mmlotn
	,mmlotn_conv
	,mmpns
	,mmpmpn
	,mmpmpn_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.mmukid
	,cdc.mmitm
	,cdc.mmmcu
	,cdc.mmmcu_conv
	,cdc.mmmmcu
	,cdc.mmmmcu_conv
	,cdc.mmmsgt
	,cdc.mmmsga
	,cdc.mmhcld
	,cdc.mmkcoo
	,cdc.mmkcoo_conv
	,cdc.mmdoco
	,cdc.mmdcto
	,cdc.mmlnid
	,cdc.mmlnid_conv
	,cdc.mmsfxo
	,cdc.mmsfxo_conv
	,cdc.mmdsc1
	,cdc.mmdsc1_conv
	,cdc.mmtrqt
	,cdc.mmtrqt_conv
	,cdc.mmvend
	,cdc.mmvend_conv
	,cdc.mmdrqj
	,cdc.mmdrqj_conv
	,cdc.mmstrt
	,cdc.mmstrt_conv
	,cdc.mmrstj
	,cdc.mmrstj_conv
	,cdc.mmrrqj
	,cdc.mmrrqj_conv
	,cdc.mmupmj
	,cdc.mmupmj_conv
	,cdc.mmtday
	,cdc.mmuser
	,cdc.mmuser_conv
	,cdc.mmjobn
	,cdc.mmjobn_conv
	,cdc.mmpid
	,cdc.mmpid_conv
	,cdc.mmredj
	,cdc.mmredj_conv
	,cdc.mmoedj
	,cdc.mmoedj_conv
	,cdc.mmline
	,cdc.mmline_conv
	,cdc.mmprjm
	,cdc.mmprjm_conv
	,cdc.mmsrdm
	,cdc.mmsrdm_conv
	,cdc.mmostt
	,cdc.mmostt_conv
	,cdc.mmlotn
	,cdc.mmlotn_conv
	,cdc.mmpns
	,cdc.mmpmpn
	,cdc.mmpmpn_conv
FROM stg_jde.tmp_upsert_f3411_cdc cdc
LEFT OUTER JOIN rep_jde.f3411_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde.f3411_new AF:{{ task_instance_key_str }}' ) 