-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde.f40205_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,lflnty
	,lflnty_conv
	,lflnds
	,lflnds_conv
	,lflnd2
	,lflnd2_conv
	,lfgli
	,lfgli_conv
	,lfivi
	,lfari
	,lfari_conv
	,lfapi
	,lfapi_conv
	,lfrsgn
	,lfrsgn_conv
	,lftxyn
	,lftxyn_conv
	,lfprft
	,lfprft_conv
	,lfcdsc
	,lfcdsc_conv
	,lftx01
	,lftx02
	,lfglc
	,lfglc_conv
	,lfpdc1
	,lfpdc1_conv
	,lfpdc2
	,lfpdc2_conv
	,lfpdc3
	,lfpdc3_conv
	,lfpdc4
	,lfpdc4_conv
	,lfidc1
	,lfidc1_conv
	,lfidc2
	,lfidc3
	,lfidc3_conv
	,lfidc4
	,lfidc4_conv
	,lfcsj
	,lfdcto
	,lfart
	,lfart_conv
	,lfaft
	,lfaft_conv
	,lfgwo
	,lfgwo_conv
	,lfexvr
	,lfexvr_conv
	,lfcmi
	,lfcmi_conv
	,lfprrq
	,lfprrq_conv
	,lfev01
	,lfev01_conv
	,lfev02
	,lfev02_conv
	,lfev03
	,lfev03_conv
	,lfev04
	,lfev04_conv
	,lfev05
	,lfev05_conv
	,lfnewr
	,lfsruf
	,lfsruf_conv
	,lfnbru
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.lflnty
	,cdc.lflnty_conv
	,cdc.lflnds
	,cdc.lflnds_conv
	,cdc.lflnd2
	,cdc.lflnd2_conv
	,cdc.lfgli
	,cdc.lfgli_conv
	,cdc.lfivi
	,cdc.lfari
	,cdc.lfari_conv
	,cdc.lfapi
	,cdc.lfapi_conv
	,cdc.lfrsgn
	,cdc.lfrsgn_conv
	,cdc.lftxyn
	,cdc.lftxyn_conv
	,cdc.lfprft
	,cdc.lfprft_conv
	,cdc.lfcdsc
	,cdc.lfcdsc_conv
	,cdc.lftx01
	,cdc.lftx02
	,cdc.lfglc
	,cdc.lfglc_conv
	,cdc.lfpdc1
	,cdc.lfpdc1_conv
	,cdc.lfpdc2
	,cdc.lfpdc2_conv
	,cdc.lfpdc3
	,cdc.lfpdc3_conv
	,cdc.lfpdc4
	,cdc.lfpdc4_conv
	,cdc.lfidc1
	,cdc.lfidc1_conv
	,cdc.lfidc2
	,cdc.lfidc3
	,cdc.lfidc3_conv
	,cdc.lfidc4
	,cdc.lfidc4_conv
	,cdc.lfcsj
	,cdc.lfdcto
	,cdc.lfart
	,cdc.lfart_conv
	,cdc.lfaft
	,cdc.lfaft_conv
	,cdc.lfgwo
	,cdc.lfgwo_conv
	,cdc.lfexvr
	,cdc.lfexvr_conv
	,cdc.lfcmi
	,cdc.lfcmi_conv
	,cdc.lfprrq
	,cdc.lfprrq_conv
	,cdc.lfev01
	,cdc.lfev01_conv
	,cdc.lfev02
	,cdc.lfev02_conv
	,cdc.lfev03
	,cdc.lfev03_conv
	,cdc.lfev04
	,cdc.lfev04_conv
	,cdc.lfev05
	,cdc.lfev05_conv
	,cdc.lfnewr
	,cdc.lfsruf
	,cdc.lfsruf_conv
	,cdc.lfnbru
FROM stg_jde.tmp_upsert_f40205_cdc cdc
LEFT OUTER JOIN rep_jde.f40205_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde.f40205_new AF:{{ task_instance_key_str }}' ) 