-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde.f4072_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,adast
	,aditm
	,adlitm
	,adlitm_conv
	,adaitm
	,adaitm_conv
	,adan8
	,adigid
	,adigid_conv
	,adcgid
	,adcgid_conv
	,adogid
	,adogid_conv
	,adcrcd
	,adcrcd_conv
	,aduom
	,admnq
	,admnq_conv
	,adeftj
	,adeftj_conv
	,adexdj
	,adexdj_conv
	,adbscd
	,adledg
	,adfrmn
	,adfvtr
	,adfvtr_conv
	,adfgy
	,adfgy_conv
	,adatid
	,adurcd
	,adurcd_conv
	,adurdt
	,adurdt_conv
	,adurat
	,adurat_conv
	,adurab
	,adurab_conv
	,adurrf
	,adurrf_conv
	,adnbrord
	,adnbrord_conv
	,aduomvid
	,adfvum
	,adpartfg
	,adpartfg_conv
	,adaprs
	,aduser
	,aduser_conv
	,adpid
	,adpid_conv
	,adjobn
	,adjobn_conv
	,adupmj
	,adupmj_conv
	,adtday
	,adbktpid
	,adbktpid_conv
	,adcrcdvid
	,adcrcdvid_conv
	,adrulename
	,adrulename_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.adast
	,cdc.aditm
	,cdc.adlitm
	,cdc.adlitm_conv
	,cdc.adaitm
	,cdc.adaitm_conv
	,cdc.adan8
	,cdc.adigid
	,cdc.adigid_conv
	,cdc.adcgid
	,cdc.adcgid_conv
	,cdc.adogid
	,cdc.adogid_conv
	,cdc.adcrcd
	,cdc.adcrcd_conv
	,cdc.aduom
	,cdc.admnq
	,cdc.admnq_conv
	,cdc.adeftj
	,cdc.adeftj_conv
	,cdc.adexdj
	,cdc.adexdj_conv
	,cdc.adbscd
	,cdc.adledg
	,cdc.adfrmn
	,cdc.adfvtr
	,cdc.adfvtr_conv
	,cdc.adfgy
	,cdc.adfgy_conv
	,cdc.adatid
	,cdc.adurcd
	,cdc.adurcd_conv
	,cdc.adurdt
	,cdc.adurdt_conv
	,cdc.adurat
	,cdc.adurat_conv
	,cdc.adurab
	,cdc.adurab_conv
	,cdc.adurrf
	,cdc.adurrf_conv
	,cdc.adnbrord
	,cdc.adnbrord_conv
	,cdc.aduomvid
	,cdc.adfvum
	,cdc.adpartfg
	,cdc.adpartfg_conv
	,cdc.adaprs
	,cdc.aduser
	,cdc.aduser_conv
	,cdc.adpid
	,cdc.adpid_conv
	,cdc.adjobn
	,cdc.adjobn_conv
	,cdc.adupmj
	,cdc.adupmj_conv
	,cdc.adtday
	,cdc.adbktpid
	,cdc.adbktpid_conv
	,cdc.adcrcdvid
	,cdc.adcrcdvid_conv
	,cdc.adrulename
	,cdc.adrulename_conv
FROM stg_jde.tmp_upsert_f4072_cdc cdc
LEFT OUTER JOIN rep_jde.f4072_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde.f4072_new AF:{{ task_instance_key_str }}' ) 