-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde.f41011_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,pkitm
	,pkpdgr
	,pkdsgp
	,pkdntb
	,pkstcn
	,pkrptm
	,pkrqtc
	,pkrqtc_conv
	,pklpgp
	,pklpgp_conv
	,pkcavp
	,pkcavp_conv
	,pkdnty
	,pkdnty_conv
	,pkdntp
	,pkdetp
	,pkdetp_conv
	,pkdtpu
	,pkcoex
	,pkcoex_conv
	,pktmmn
	,pktmmn_conv
	,pktpum
	,pktmmx
	,pktmmx_conv
	,pktpux
	,pkdsmn
	,pkdsmn_conv
	,pkdntm
	,pkdnmx
	,pkdnmx_conv
	,pkdntx
	,pklpgv
	,pklpgv_conv
	,pktpu1
	,pkmnvc
	,pkmnvc_conv
	,pkmxvc
	,pkmxvc_conv
	,pkurcd
	,pkurcd_conv
	,pkurat
	,pkurat_conv
	,pkurab
	,pkurab_conv
	,pkurrf
	,pkurrf_conv
	,pkurdt
	,pkurdt_conv
	,pkuser
	,pkuser_conv
	,pkpid
	,pkpid_conv
	,pkjobn
	,pkjobn_conv
	,pkupmj
	,pkupmj_conv
	,pktday
	,pkrtob
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.pkitm
	,cdc.pkpdgr
	,cdc.pkdsgp
	,cdc.pkdntb
	,cdc.pkstcn
	,cdc.pkrptm
	,cdc.pkrqtc
	,cdc.pkrqtc_conv
	,cdc.pklpgp
	,cdc.pklpgp_conv
	,cdc.pkcavp
	,cdc.pkcavp_conv
	,cdc.pkdnty
	,cdc.pkdnty_conv
	,cdc.pkdntp
	,cdc.pkdetp
	,cdc.pkdetp_conv
	,cdc.pkdtpu
	,cdc.pkcoex
	,cdc.pkcoex_conv
	,cdc.pktmmn
	,cdc.pktmmn_conv
	,cdc.pktpum
	,cdc.pktmmx
	,cdc.pktmmx_conv
	,cdc.pktpux
	,cdc.pkdsmn
	,cdc.pkdsmn_conv
	,cdc.pkdntm
	,cdc.pkdnmx
	,cdc.pkdnmx_conv
	,cdc.pkdntx
	,cdc.pklpgv
	,cdc.pklpgv_conv
	,cdc.pktpu1
	,cdc.pkmnvc
	,cdc.pkmnvc_conv
	,cdc.pkmxvc
	,cdc.pkmxvc_conv
	,cdc.pkurcd
	,cdc.pkurcd_conv
	,cdc.pkurat
	,cdc.pkurat_conv
	,cdc.pkurab
	,cdc.pkurab_conv
	,cdc.pkurrf
	,cdc.pkurrf_conv
	,cdc.pkurdt
	,cdc.pkurdt_conv
	,cdc.pkuser
	,cdc.pkuser_conv
	,cdc.pkpid
	,cdc.pkpid_conv
	,cdc.pkjobn
	,cdc.pkjobn_conv
	,cdc.pkupmj
	,cdc.pkupmj_conv
	,cdc.pktday
	,cdc.pkrtob
FROM stg_jde.tmp_upsert_f41011_cdc cdc
LEFT OUTER JOIN rep_jde.f41011_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde.f41011_new AF:{{ task_instance_key_str }}' ) 