-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde.f4105_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,coitm
	,colitm
	,colitm_conv
	,coaitm
	,coaitm_conv
	,comcu
	,comcu_conv
	,colocn
	,colocn_conv
	,colotn
	,colotn_conv
	,colotg
	,coledg
	,councs
	,councs_conv
	,cocspo
	,cocsin
	,courcd
	,courcd_conv
	,courdt
	,courdt_conv
	,courat
	,courat_conv
	,courab
	,courab_conv
	,courrf
	,courrf_conv
	,couser
	,couser_conv
	,copid
	,copid_conv
	,cojobn
	,cojobn_conv
	,coupmj
	,coupmj_conv
	,cotday
	,coccfl
	,coccfl_conv
	,cocrcs
	,cocrcs_conv
	,coostc
	,coostc_conv
	,costoc
	,costoc_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.coitm
	,cdc.colitm
	,cdc.colitm_conv
	,cdc.coaitm
	,cdc.coaitm_conv
	,cdc.comcu
	,cdc.comcu_conv
	,cdc.colocn
	,cdc.colocn_conv
	,cdc.colotn
	,cdc.colotn_conv
	,cdc.colotg
	,cdc.coledg
	,cdc.councs
	,cdc.councs_conv
	,cdc.cocspo
	,cdc.cocsin
	,cdc.courcd
	,cdc.courcd_conv
	,cdc.courdt
	,cdc.courdt_conv
	,cdc.courat
	,cdc.courat_conv
	,cdc.courab
	,cdc.courab_conv
	,cdc.courrf
	,cdc.courrf_conv
	,cdc.couser
	,cdc.couser_conv
	,cdc.copid
	,cdc.copid_conv
	,cdc.cojobn
	,cdc.cojobn_conv
	,cdc.coupmj
	,cdc.coupmj_conv
	,cdc.cotday
	,cdc.coccfl
	,cdc.coccfl_conv
	,cdc.cocrcs
	,cdc.cocrcs_conv
	,cdc.coostc
	,cdc.coostc_conv
	,cdc.costoc
	,cdc.costoc_conv
FROM stg_jde.tmp_upsert_f4105_cdc cdc
LEFT OUTER JOIN rep_jde.f4105_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde.f4105_new AF:{{ task_instance_key_str }}' ) 