-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde.f4111_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,ilnlin
	,ilitm
	,illitm
	,illitm_conv
	,ilaitm
	,ilaitm_conv
	,ilmcu
	,ilmcu_conv
	,illocn
	,illocn_conv
	,illotn
	,illotn_conv
	,ilplot
	,ilplot_conv
	,ilstun
	,illdsq
	,iltrno
	,ilfrto
	,ilfrto_conv
	,illmcx
	,illmcx_conv
	,illots
	,illotp
	,illotp_conv
	,illotg
	,ilkit
	,ilmmcu
	,ilmmcu_conv
	,ildmct
	,ildmct_conv
	,ildmcs
	,ilkco
	,ilkco_conv
	,ildoc
	,ildct
	,ilsfx
	,ilsfx_conv
	,iljeln
	,ilicu
	,ildgl
	,ildgl_conv
	,ilglpt
	,ildcto
	,ildoco
	,ilkcoo
	,ilkcoo_conv
	,illnid
	,illnid_conv
	,ilipcd
	,iltrdj
	,iltrdj_conv
	,iltrum
	,ilan8
	,iltrex
	,iltrex_conv
	,iltref
	,iltref_conv
	,ilrcd
	,iltrqt
	,iltrqt_conv
	,iluncs
	,iluncs_conv
	,ilpaid
	,ilpaid_conv
	,ilterm
	,ilterm_conv
	,ilukid
	,iltday
	,iluser
	,iluser_conv
	,ilpid
	,ilpid_conv
	,ilcrdj
	,ilcrdj_conv
	,ilaid
	,ilaid_conv
	,ilasid
	,ilasid_conv
	,ilmcuz
	,ilmcuz_conv
	,ilobj
	,ilobj_conv
	,ilsbl
	,ilsbl_conv
	,ilsub
	,ilsub_conv
	,iluom2
	,ilcmoo
	,ilcmoo_conv
	,ilre
	,ilsblt
	,ilsqor
	,ilsqor_conv
	,ilvpej
	,ilvpej_conv
	,ilhdgj
	,ilhdgj_conv
	,ilshan
	,ilopsq
	,ilopsq_conv
	,ilrfln
	,ilrfln_conv
	,iltgn
	,iltgn_conv
	,illotc
	,illotc_conv
	,ilsvdt
	,ilsvdt_conv
	,illrcd
	,ilrlot
	,ilrlot_conv
	,illpnu
	,illpnu_conv
	,ilpmpn
	,ilpmpn_conv
	,ilpns
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.ilnlin
	,cdc.ilitm
	,cdc.illitm
	,cdc.illitm_conv
	,cdc.ilaitm
	,cdc.ilaitm_conv
	,cdc.ilmcu
	,cdc.ilmcu_conv
	,cdc.illocn
	,cdc.illocn_conv
	,cdc.illotn
	,cdc.illotn_conv
	,cdc.ilplot
	,cdc.ilplot_conv
	,cdc.ilstun
	,cdc.illdsq
	,cdc.iltrno
	,cdc.ilfrto
	,cdc.ilfrto_conv
	,cdc.illmcx
	,cdc.illmcx_conv
	,cdc.illots
	,cdc.illotp
	,cdc.illotp_conv
	,cdc.illotg
	,cdc.ilkit
	,cdc.ilmmcu
	,cdc.ilmmcu_conv
	,cdc.ildmct
	,cdc.ildmct_conv
	,cdc.ildmcs
	,cdc.ilkco
	,cdc.ilkco_conv
	,cdc.ildoc
	,cdc.ildct
	,cdc.ilsfx
	,cdc.ilsfx_conv
	,cdc.iljeln
	,cdc.ilicu
	,cdc.ildgl
	,cdc.ildgl_conv
	,cdc.ilglpt
	,cdc.ildcto
	,cdc.ildoco
	,cdc.ilkcoo
	,cdc.ilkcoo_conv
	,cdc.illnid
	,cdc.illnid_conv
	,cdc.ilipcd
	,cdc.iltrdj
	,cdc.iltrdj_conv
	,cdc.iltrum
	,cdc.ilan8
	,cdc.iltrex
	,cdc.iltrex_conv
	,cdc.iltref
	,cdc.iltref_conv
	,cdc.ilrcd
	,cdc.iltrqt
	,cdc.iltrqt_conv
	,cdc.iluncs
	,cdc.iluncs_conv
	,cdc.ilpaid
	,cdc.ilpaid_conv
	,cdc.ilterm
	,cdc.ilterm_conv
	,cdc.ilukid
	,cdc.iltday
	,cdc.iluser
	,cdc.iluser_conv
	,cdc.ilpid
	,cdc.ilpid_conv
	,cdc.ilcrdj
	,cdc.ilcrdj_conv
	,cdc.ilaid
	,cdc.ilaid_conv
	,cdc.ilasid
	,cdc.ilasid_conv
	,cdc.ilmcuz
	,cdc.ilmcuz_conv
	,cdc.ilobj
	,cdc.ilobj_conv
	,cdc.ilsbl
	,cdc.ilsbl_conv
	,cdc.ilsub
	,cdc.ilsub_conv
	,cdc.iluom2
	,cdc.ilcmoo
	,cdc.ilcmoo_conv
	,cdc.ilre
	,cdc.ilsblt
	,cdc.ilsqor
	,cdc.ilsqor_conv
	,cdc.ilvpej
	,cdc.ilvpej_conv
	,cdc.ilhdgj
	,cdc.ilhdgj_conv
	,cdc.ilshan
	,cdc.ilopsq
	,cdc.ilopsq_conv
	,cdc.ilrfln
	,cdc.ilrfln_conv
	,cdc.iltgn
	,cdc.iltgn_conv
	,cdc.illotc
	,cdc.illotc_conv
	,cdc.ilsvdt
	,cdc.ilsvdt_conv
	,cdc.illrcd
	,cdc.ilrlot
	,cdc.ilrlot_conv
	,cdc.illpnu
	,cdc.illpnu_conv
	,cdc.ilpmpn
	,cdc.ilpmpn_conv
	,cdc.ilpns
FROM stg_jde.tmp_upsert_f4111_cdc cdc
LEFT OUTER JOIN rep_jde.f4111_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde.f4111_new AF:{{ task_instance_key_str }}' ) 