-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde.f41291_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,igprp5
	,igitm
	,iglitm
	,iglitm_conv
	,igaitm
	,igaitm_conv
	,igmcu
	,igmcu_conv
	,iglocn
	,iglocn_conv
	,iglotn
	,iglotn_conv
	,iglvla
	,iglvlb
	,igpcst
	,igpcst_conv
	,igpamt
	,igpamt_conv
	,igratf
	,igratf_conv
	,igratv
	,igratv_conv
	,igan8
	,igglc
	,igglc_conv
	,igglpt
	,igefff
	,igefff_conv
	,igefft
	,igefft_conv
	,igtx
	,iginyn
	,iginyn_conv
	,igrcyn
	,igrcyn_conv
	,igaisl
	,igaisl_conv
	,igbin
	,igbin_conv
	,iguser
	,iguser_conv
	,igjobn
	,igjobn_conv
	,igpid
	,igpid_conv
	,igupmj
	,igupmj_conv
	,igtday
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.igprp5
	,cdc.igitm
	,cdc.iglitm
	,cdc.iglitm_conv
	,cdc.igaitm
	,cdc.igaitm_conv
	,cdc.igmcu
	,cdc.igmcu_conv
	,cdc.iglocn
	,cdc.iglocn_conv
	,cdc.iglotn
	,cdc.iglotn_conv
	,cdc.iglvla
	,cdc.iglvlb
	,cdc.igpcst
	,cdc.igpcst_conv
	,cdc.igpamt
	,cdc.igpamt_conv
	,cdc.igratf
	,cdc.igratf_conv
	,cdc.igratv
	,cdc.igratv_conv
	,cdc.igan8
	,cdc.igglc
	,cdc.igglc_conv
	,cdc.igglpt
	,cdc.igefff
	,cdc.igefff_conv
	,cdc.igefft
	,cdc.igefft_conv
	,cdc.igtx
	,cdc.iginyn
	,cdc.iginyn_conv
	,cdc.igrcyn
	,cdc.igrcyn_conv
	,cdc.igaisl
	,cdc.igaisl_conv
	,cdc.igbin
	,cdc.igbin_conv
	,cdc.iguser
	,cdc.iguser_conv
	,cdc.igjobn
	,cdc.igjobn_conv
	,cdc.igpid
	,cdc.igpid_conv
	,cdc.igupmj
	,cdc.igupmj_conv
	,cdc.igtday
FROM stg_jde.tmp_upsert_f41291_cdc cdc
LEFT OUTER JOIN rep_jde.f41291_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde.f41291_new AF:{{ task_instance_key_str }}' ) 