-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde.f4229_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,ssdcto
	,sslnty
	,sslnty_conv
	,ssan8
	,ssitm
	,sslitm
	,sslitm_conv
	,ssaitm
	,ssaitm_conv
	,ssmcu
	,ssmcu_conv
	,sssrp1
	,sssrp2
	,sssrp3
	,sssrp4
	,sssrp5
	,ssctry
	,ssfy
	,ssfy_conv
	,ssfq
	,sscms
	,sscms_conv
	,sscmc
	,sscmc_conv
	,sscys
	,sscys_conv
	,sscyc
	,sscyc_conv
	,sspyes
	,sspyes_conv
	,sspyec
	,sspyec_conv
	,ssqs01
	,ssqs01_conv
	,ssqs02
	,ssqs02_conv
	,ssqs03
	,ssqs03_conv
	,ssqs04
	,ssqs04_conv
	,ssqs05
	,ssqs05_conv
	,ssqs06
	,ssqs06_conv
	,ssqs07
	,ssqs07_conv
	,ssqs08
	,ssqs08_conv
	,ssqs09
	,ssqs09_conv
	,ssqs10
	,ssqs10_conv
	,ssqs11
	,ssqs11_conv
	,ssqs12
	,ssqs12_conv
	,ssqs13
	,ssqs13_conv
	,ssqs14
	,ssqs14_conv
	,ssci01
	,ssci01_conv
	,ssci02
	,ssci02_conv
	,ssci03
	,ssci03_conv
	,ssci04
	,ssci04_conv
	,ssci05
	,ssci05_conv
	,ssci06
	,ssci06_conv
	,ssci07
	,ssci07_conv
	,ssci08
	,ssci08_conv
	,ssci09
	,ssci09_conv
	,ssci10
	,ssci10_conv
	,ssci11
	,ssci11_conv
	,ssci12
	,ssci12_conv
	,ssci13
	,ssci13_conv
	,ssci14
	,ssci14_conv
	,ssas01
	,ssas01_conv
	,ssas02
	,ssas02_conv
	,ssas03
	,ssas03_conv
	,ssas04
	,ssas04_conv
	,ssas05
	,ssas05_conv
	,ssas06
	,ssas06_conv
	,ssas07
	,ssas07_conv
	,ssas08
	,ssas08_conv
	,ssas09
	,ssas09_conv
	,ssas10
	,ssas10_conv
	,ssas11
	,ssas11_conv
	,ssas12
	,ssas12_conv
	,ssas13
	,ssas13_conv
	,ssas14
	,ssas14_conv
	,ssdlij
	,ssdlij_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.ssdcto
	,cdc.sslnty
	,cdc.sslnty_conv
	,cdc.ssan8
	,cdc.ssitm
	,cdc.sslitm
	,cdc.sslitm_conv
	,cdc.ssaitm
	,cdc.ssaitm_conv
	,cdc.ssmcu
	,cdc.ssmcu_conv
	,cdc.sssrp1
	,cdc.sssrp2
	,cdc.sssrp3
	,cdc.sssrp4
	,cdc.sssrp5
	,cdc.ssctry
	,cdc.ssfy
	,cdc.ssfy_conv
	,cdc.ssfq
	,cdc.sscms
	,cdc.sscms_conv
	,cdc.sscmc
	,cdc.sscmc_conv
	,cdc.sscys
	,cdc.sscys_conv
	,cdc.sscyc
	,cdc.sscyc_conv
	,cdc.sspyes
	,cdc.sspyes_conv
	,cdc.sspyec
	,cdc.sspyec_conv
	,cdc.ssqs01
	,cdc.ssqs01_conv
	,cdc.ssqs02
	,cdc.ssqs02_conv
	,cdc.ssqs03
	,cdc.ssqs03_conv
	,cdc.ssqs04
	,cdc.ssqs04_conv
	,cdc.ssqs05
	,cdc.ssqs05_conv
	,cdc.ssqs06
	,cdc.ssqs06_conv
	,cdc.ssqs07
	,cdc.ssqs07_conv
	,cdc.ssqs08
	,cdc.ssqs08_conv
	,cdc.ssqs09
	,cdc.ssqs09_conv
	,cdc.ssqs10
	,cdc.ssqs10_conv
	,cdc.ssqs11
	,cdc.ssqs11_conv
	,cdc.ssqs12
	,cdc.ssqs12_conv
	,cdc.ssqs13
	,cdc.ssqs13_conv
	,cdc.ssqs14
	,cdc.ssqs14_conv
	,cdc.ssci01
	,cdc.ssci01_conv
	,cdc.ssci02
	,cdc.ssci02_conv
	,cdc.ssci03
	,cdc.ssci03_conv
	,cdc.ssci04
	,cdc.ssci04_conv
	,cdc.ssci05
	,cdc.ssci05_conv
	,cdc.ssci06
	,cdc.ssci06_conv
	,cdc.ssci07
	,cdc.ssci07_conv
	,cdc.ssci08
	,cdc.ssci08_conv
	,cdc.ssci09
	,cdc.ssci09_conv
	,cdc.ssci10
	,cdc.ssci10_conv
	,cdc.ssci11
	,cdc.ssci11_conv
	,cdc.ssci12
	,cdc.ssci12_conv
	,cdc.ssci13
	,cdc.ssci13_conv
	,cdc.ssci14
	,cdc.ssci14_conv
	,cdc.ssas01
	,cdc.ssas01_conv
	,cdc.ssas02
	,cdc.ssas02_conv
	,cdc.ssas03
	,cdc.ssas03_conv
	,cdc.ssas04
	,cdc.ssas04_conv
	,cdc.ssas05
	,cdc.ssas05_conv
	,cdc.ssas06
	,cdc.ssas06_conv
	,cdc.ssas07
	,cdc.ssas07_conv
	,cdc.ssas08
	,cdc.ssas08_conv
	,cdc.ssas09
	,cdc.ssas09_conv
	,cdc.ssas10
	,cdc.ssas10_conv
	,cdc.ssas11
	,cdc.ssas11_conv
	,cdc.ssas12
	,cdc.ssas12_conv
	,cdc.ssas13
	,cdc.ssas13_conv
	,cdc.ssas14
	,cdc.ssas14_conv
	,cdc.ssdlij
	,cdc.ssdlij_conv
FROM stg_jde.tmp_upsert_f4229_cdc cdc
LEFT OUTER JOIN rep_jde.f4229_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde.f4229_new AF:{{ task_instance_key_str }}' ) 