-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde.f4930_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,vmvehi
	,vmvehi_conv
	,vmvehs
	,vmvehs_conv
	,vmdl01
	,vmdl01_conv
	,vmlrfg
	,vmlrfg_conv
	,vmmcu
	,vmmcu_conv
	,vmvtyp
	,vmvtyp_conv
	,vmdumv
	,vmdumv_conv
	,vmvown
	,vmnce
	,vmnce_conv
	,vmwtem
	,vmwtem_conv
	,vmwtca
	,vmwtca_conv
	,vmwtum
	,vmvlcp
	,vmvlcp_conv
	,vmvlcs
	,vmvlcs_conv
	,vmvlum
	,vmcvol
	,vmcvol_conv
	,vmcvum
	,vmlcnt
	,vmmxml
	,vmumd1
	,vminmg
	,vmmest
	,vmvehn
	,vmvehn_conv
	,vmurcd
	,vmurcd_conv
	,vmurdt
	,vmurdt_conv
	,vmurat
	,vmurat_conv
	,vmurab
	,vmurab_conv
	,vmurrf
	,vmurrf_conv
	,vmuser
	,vmuser_conv
	,vmpid
	,vmpid_conv
	,vmjobn
	,vmjobn_conv
	,vmupmj
	,vmupmj_conv
	,vmtday
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.vmvehi
	,cdc.vmvehi_conv
	,cdc.vmvehs
	,cdc.vmvehs_conv
	,cdc.vmdl01
	,cdc.vmdl01_conv
	,cdc.vmlrfg
	,cdc.vmlrfg_conv
	,cdc.vmmcu
	,cdc.vmmcu_conv
	,cdc.vmvtyp
	,cdc.vmvtyp_conv
	,cdc.vmdumv
	,cdc.vmdumv_conv
	,cdc.vmvown
	,cdc.vmnce
	,cdc.vmnce_conv
	,cdc.vmwtem
	,cdc.vmwtem_conv
	,cdc.vmwtca
	,cdc.vmwtca_conv
	,cdc.vmwtum
	,cdc.vmvlcp
	,cdc.vmvlcp_conv
	,cdc.vmvlcs
	,cdc.vmvlcs_conv
	,cdc.vmvlum
	,cdc.vmcvol
	,cdc.vmcvol_conv
	,cdc.vmcvum
	,cdc.vmlcnt
	,cdc.vmmxml
	,cdc.vmumd1
	,cdc.vminmg
	,cdc.vmmest
	,cdc.vmvehn
	,cdc.vmvehn_conv
	,cdc.vmurcd
	,cdc.vmurcd_conv
	,cdc.vmurdt
	,cdc.vmurdt_conv
	,cdc.vmurat
	,cdc.vmurat_conv
	,cdc.vmurab
	,cdc.vmurab_conv
	,cdc.vmurrf
	,cdc.vmurrf_conv
	,cdc.vmuser
	,cdc.vmuser_conv
	,cdc.vmpid
	,cdc.vmpid_conv
	,cdc.vmjobn
	,cdc.vmjobn_conv
	,cdc.vmupmj
	,cdc.vmupmj_conv
	,cdc.vmtday
FROM stg_jde.tmp_upsert_f4930_cdc cdc
LEFT OUTER JOIN rep_jde.f4930_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde.f4930_new AF:{{ task_instance_key_str }}' ) 