-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde.f4942_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,isshpn
	,isrssn
	,isdoco
	,isdcto
	,iskcoo
	,iskcoo_conv
	,islnid
	,islnid_conv
	,iswgts
	,iswgts_conv
	,iswtum
	,isscvl
	,isscvl_conv
	,isvlum
	,isitm
	,issoqs
	,issoqs_conv
	,isuom
	,isprp1
	,isnmfc
	,isdsgp
	,ishzdc
	,isfrt1
	,isfrt2
	,isaexp
	,isaexp_conv
	,isfea
	,isfea_conv
	,iscrcd
	,iscrcd_conv
	,isecst
	,isecst_conv
	,isurcd
	,isurcd_conv
	,isurdt
	,isurdt_conv
	,isurat
	,isurat_conv
	,isurab
	,isurab_conv
	,isurrf
	,isurrf_conv
	,isuser
	,isuser_conv
	,ispid
	,ispid_conv
	,isjobn
	,isjobn_conv
	,isupmj
	,isupmj_conv
	,istday
	,iscums
	,iscums_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.isshpn
	,cdc.isrssn
	,cdc.isdoco
	,cdc.isdcto
	,cdc.iskcoo
	,cdc.iskcoo_conv
	,cdc.islnid
	,cdc.islnid_conv
	,cdc.iswgts
	,cdc.iswgts_conv
	,cdc.iswtum
	,cdc.isscvl
	,cdc.isscvl_conv
	,cdc.isvlum
	,cdc.isitm
	,cdc.issoqs
	,cdc.issoqs_conv
	,cdc.isuom
	,cdc.isprp1
	,cdc.isnmfc
	,cdc.isdsgp
	,cdc.ishzdc
	,cdc.isfrt1
	,cdc.isfrt2
	,cdc.isaexp
	,cdc.isaexp_conv
	,cdc.isfea
	,cdc.isfea_conv
	,cdc.iscrcd
	,cdc.iscrcd_conv
	,cdc.isecst
	,cdc.isecst_conv
	,cdc.isurcd
	,cdc.isurcd_conv
	,cdc.isurdt
	,cdc.isurdt_conv
	,cdc.isurat
	,cdc.isurat_conv
	,cdc.isurab
	,cdc.isurab_conv
	,cdc.isurrf
	,cdc.isurrf_conv
	,cdc.isuser
	,cdc.isuser_conv
	,cdc.ispid
	,cdc.ispid_conv
	,cdc.isjobn
	,cdc.isjobn_conv
	,cdc.isupmj
	,cdc.isupmj_conv
	,cdc.istday
	,cdc.iscums
	,cdc.iscums_conv
FROM stg_jde.tmp_upsert_f4942_cdc cdc
LEFT OUTER JOIN rep_jde.f4942_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde.f4942_new AF:{{ task_instance_key_str }}' ) 