-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde.f550312_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,sglrsegt
	,sgctr
	,sgac04
	,sgdsc1
	,sgdsc1_conv
	,sgac05
	,sgdsc2
	,sgdsc2_conv
	,sgac01
	,sgclass03
	,sgsrp1
	,sgy55char1
	,sgy55char1_conv
	,sgy55char2
	,sgy55char2_conv
	,sgy55strg1
	,sgy55strg1_conv
	,sgy55strg2
	,sgy55strg2_conv
	,sgy55amnt1
	,sgy55amnt1_conv
	,sgy55amnt2
	,sgy55amnt2_conv
	,sgy55time1
	,sgy55time2
	,sgy55date1
	,sgy55date1_conv
	,sgy55date2
	,sgy55date2_conv
	,sguser
	,sguser_conv
	,sgpid
	,sgpid_conv
	,sgjobn
	,sgjobn_conv
	,sgupmj
	,sgupmj_conv
	,sgupmt
	,sgdesc
	,sgdesc_conv
	,sgan8
	,sgalph
	,sgalph_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.sglrsegt
	,cdc.sgctr
	,cdc.sgac04
	,cdc.sgdsc1
	,cdc.sgdsc1_conv
	,cdc.sgac05
	,cdc.sgdsc2
	,cdc.sgdsc2_conv
	,cdc.sgac01
	,cdc.sgclass03
	,cdc.sgsrp1
	,cdc.sgy55char1
	,cdc.sgy55char1_conv
	,cdc.sgy55char2
	,cdc.sgy55char2_conv
	,cdc.sgy55strg1
	,cdc.sgy55strg1_conv
	,cdc.sgy55strg2
	,cdc.sgy55strg2_conv
	,cdc.sgy55amnt1
	,cdc.sgy55amnt1_conv
	,cdc.sgy55amnt2
	,cdc.sgy55amnt2_conv
	,cdc.sgy55time1
	,cdc.sgy55time2
	,cdc.sgy55date1
	,cdc.sgy55date1_conv
	,cdc.sgy55date2
	,cdc.sgy55date2_conv
	,cdc.sguser
	,cdc.sguser_conv
	,cdc.sgpid
	,cdc.sgpid_conv
	,cdc.sgjobn
	,cdc.sgjobn_conv
	,cdc.sgupmj
	,cdc.sgupmj_conv
	,cdc.sgupmt
	,cdc.sgdesc
	,cdc.sgdesc_conv
	,cdc.sgan8
	,cdc.sgalph
	,cdc.sgalph_conv
FROM stg_jde.tmp_upsert_f550312_cdc cdc
LEFT OUTER JOIN rep_jde.f550312_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde.f550312_new AF:{{ task_instance_key_str }}' ) 