-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde.f550006_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,pmy55prmcd
	,pmprnumb
	,pmy55prmty
	,pmy55cmpcd
	,pmcmpid
	,pmcmpid_conv
	,pmdl01
	,pmdl01_conv
	,pmlngp1
	,pmstrt
	,pmstrt_conv
	,pmwwast
	,pmwwast_conv
	,pmwwaet
	,pmwwaet_conv
	,pmenddj
	,pmenddj_conv
	,pmctr
	,pmcrcd
	,pmcrcd_conv
	,pmtxky
	,pmtxky_conv
	,pmy55dur
	,pmy55hrs
	,pmy55prity
	,pmy55plcmt
	,pmy55sldts
	,pmy55sldts_conv
	,pmy55sldte
	,pmy55sldte_conv
	,pmy55prdts
	,pmy55prdts_conv
	,pmy55prdte
	,pmy55prdte_conv
	,pmy55cpflg
	,pmy55cpflg_conv
	,pmy55cptyp
	,pmy55srst
	,pmy55ntst
	,pmy55psusd
	,pmy55psusd_conv
	,pmy55pcand
	,pmy55pcand_conv
	,pmurab
	,pmurab_conv
	,pmurrf
	,pmurrf_conv
	,pmurdt
	,pmurdt_conv
	,pmurat
	,pmurat_conv
	,pmurcd
	,pmurcd_conv
	,pmcrtu
	,pmcrtu_conv
	,pmcrdj
	,pmcrdj_conv
	,pmc9crp
	,pmc9crp_conv
	,pmupmj
	,pmupmj_conv
	,pmupmt
	,pmjobn
	,pmjobn_conv
	,pmpid
	,pmpid_conv
	,pmuser
	,pmuser_conv
	,pmy55alapr
	,pmy55alapr_conv
	,pmy55strg1
	,pmy55strg1_conv
	,pmy55char1
	,pmy55char1_conv
	,pmy55char2
	,pmy55char2_conv
	,pmy55strg2
	,pmy55strg2_conv
	,pmy55amnt1
	,pmy55amnt1_conv
	,pmy55amnt2
	,pmy55amnt2_conv
	,pmy55time1
	,pmy55time2
	,pmy55date1
	,pmy55date1_conv
	,pmy55date2
	,pmy55date2_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.pmy55prmcd
	,cdc.pmprnumb
	,cdc.pmy55prmty
	,cdc.pmy55cmpcd
	,cdc.pmcmpid
	,cdc.pmcmpid_conv
	,cdc.pmdl01
	,cdc.pmdl01_conv
	,cdc.pmlngp1
	,cdc.pmstrt
	,cdc.pmstrt_conv
	,cdc.pmwwast
	,cdc.pmwwast_conv
	,cdc.pmwwaet
	,cdc.pmwwaet_conv
	,cdc.pmenddj
	,cdc.pmenddj_conv
	,cdc.pmctr
	,cdc.pmcrcd
	,cdc.pmcrcd_conv
	,cdc.pmtxky
	,cdc.pmtxky_conv
	,cdc.pmy55dur
	,cdc.pmy55hrs
	,cdc.pmy55prity
	,cdc.pmy55plcmt
	,cdc.pmy55sldts
	,cdc.pmy55sldts_conv
	,cdc.pmy55sldte
	,cdc.pmy55sldte_conv
	,cdc.pmy55prdts
	,cdc.pmy55prdts_conv
	,cdc.pmy55prdte
	,cdc.pmy55prdte_conv
	,cdc.pmy55cpflg
	,cdc.pmy55cpflg_conv
	,cdc.pmy55cptyp
	,cdc.pmy55srst
	,cdc.pmy55ntst
	,cdc.pmy55psusd
	,cdc.pmy55psusd_conv
	,cdc.pmy55pcand
	,cdc.pmy55pcand_conv
	,cdc.pmurab
	,cdc.pmurab_conv
	,cdc.pmurrf
	,cdc.pmurrf_conv
	,cdc.pmurdt
	,cdc.pmurdt_conv
	,cdc.pmurat
	,cdc.pmurat_conv
	,cdc.pmurcd
	,cdc.pmurcd_conv
	,cdc.pmcrtu
	,cdc.pmcrtu_conv
	,cdc.pmcrdj
	,cdc.pmcrdj_conv
	,cdc.pmc9crp
	,cdc.pmc9crp_conv
	,cdc.pmupmj
	,cdc.pmupmj_conv
	,cdc.pmupmt
	,cdc.pmjobn
	,cdc.pmjobn_conv
	,cdc.pmpid
	,cdc.pmpid_conv
	,cdc.pmuser
	,cdc.pmuser_conv
	,cdc.pmy55alapr
	,cdc.pmy55alapr_conv
	,cdc.pmy55strg1
	,cdc.pmy55strg1_conv
	,cdc.pmy55char1
	,cdc.pmy55char1_conv
	,cdc.pmy55char2
	,cdc.pmy55char2_conv
	,cdc.pmy55strg2
	,cdc.pmy55strg2_conv
	,cdc.pmy55amnt1
	,cdc.pmy55amnt1_conv
	,cdc.pmy55amnt2
	,cdc.pmy55amnt2_conv
	,cdc.pmy55time1
	,cdc.pmy55time2
	,cdc.pmy55date1
	,cdc.pmy55date1_conv
	,cdc.pmy55date2
	,cdc.pmy55date2_conv
FROM stg_jde.tmp_upsert_f550006_cdc cdc
LEFT OUTER JOIN rep_jde.f550006_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde.f550006_new AF:{{ task_instance_key_str }}' ) 