-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde.f554103_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,alresc
	,alresc_conv
	,alukid
	,altrmnum
	,altrmnum_conv
	,alfrto
	,alfrto_conv
	,aledbt
	,aledbt_conv
	,aledtn
	,aledtn_conv
	,alfrsq
	,alfrsq_conv
	,aly55sttsl
	,almcu
	,almcu_conv
	,alddday
	,alddday_conv
	,altday
	,alvehi
	,alvehi_conv
	,aly55owid
	,aly55owid_conv
	,alitm
	,allitm
	,allitm_conv
	,alaitm
	,alaitm_conv
	,alambr
	,alambr_conv
	,aluom1
	,album3
	,alyshipty
	,alyshipty_conv
	,allocn
	,allocn_conv
	,aly55aglc
	,aly55agto
	,alsid
	,alsid_conv
	,alstok
	,alstok_conv
	,aluom2
	,album4
	,alanby
	,alancc
	,alan8
	,alshan
	,aly55wbno
	,aly55wbno_conv
	,alldty
	,altkid
	,altkid_conv
	,altemp
	,altemp_conv
	,aluom3
	,alstpu
	,alvlc1
	,alvlc1_conv
	,aldnty
	,aldnty_conv
	,aldend
	,aldend_conv
	,aldntp
	,almetn
	,almetn_conv
	,aly55cpnm
	,aly55crdid
	,aldsc1
	,aldsc1_conv
	,alflag
	,alflag_conv
	,aly55txt1
	,aly55txt1_conv
	,alev01
	,alev01_conv
	,alev02
	,alev02_conv
	,alev03
	,alev03_conv
	,alev04
	,alev04_conv
	,alev05
	,alev05_conv
	,alkcoo
	,alkcoo_conv
	,aldcto
	,aldoco
	,allnid
	,allnid_conv
	,alrkco
	,alrkco_conv
	,alrcto
	,alrorn
	,alrorn_conv
	,alxlin
	,alxlin_conv
	,alkco
	,alkco_conv
	,aldct
	,aldoc
	,allinn
	,allinn_conv
	,alokco
	,alokco_conv
	,alocto
	,aloorn
	,aloorn_conv
	,alogno
	,alogno_conv
	,alskco
	,alskco_conv
	,alsdct
	,alsdoc
	,alslne
	,alslne_conv
	,alicu
	,altd1
	,altd1_conv
	,aluser
	,aluser_conv
	,alpid
	,alpid_conv
	,aljobn
	,aljobn_conv
	,alupmj
	,alupmj_conv
	,alupmt
	,als1fu
	,als1fu_conv
	,als2fu
	,als2fu_conv
	,alfuf9
	,alfuf9_conv
	,alpstm
	,alcburst1
	,alcburst1_conv
	,alcburst2
	,alcburst2_conv
	,aleaurst1
	,aleaurst1_conv
	,aly55amnt1
	,aly55amnt1_conv
	,aly55amnt2
	,aly55amnt2_conv
	,aly55date1
	,aly55date1_conv
	,aly55date2
	,aly55date2_conv
	,aly55time1
	,aly55strg1
	,aly55strg1_conv
	,aly55strg2
	,aly55strg2_conv
	,aly55char1
	,aly55char1_conv
	,aly55char2
	,aly55char2_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.alresc
	,cdc.alresc_conv
	,cdc.alukid
	,cdc.altrmnum
	,cdc.altrmnum_conv
	,cdc.alfrto
	,cdc.alfrto_conv
	,cdc.aledbt
	,cdc.aledbt_conv
	,cdc.aledtn
	,cdc.aledtn_conv
	,cdc.alfrsq
	,cdc.alfrsq_conv
	,cdc.aly55sttsl
	,cdc.almcu
	,cdc.almcu_conv
	,cdc.alddday
	,cdc.alddday_conv
	,cdc.altday
	,cdc.alvehi
	,cdc.alvehi_conv
	,cdc.aly55owid
	,cdc.aly55owid_conv
	,cdc.alitm
	,cdc.allitm
	,cdc.allitm_conv
	,cdc.alaitm
	,cdc.alaitm_conv
	,cdc.alambr
	,cdc.alambr_conv
	,cdc.aluom1
	,cdc.album3
	,cdc.alyshipty
	,cdc.alyshipty_conv
	,cdc.allocn
	,cdc.allocn_conv
	,cdc.aly55aglc
	,cdc.aly55agto
	,cdc.alsid
	,cdc.alsid_conv
	,cdc.alstok
	,cdc.alstok_conv
	,cdc.aluom2
	,cdc.album4
	,cdc.alanby
	,cdc.alancc
	,cdc.alan8
	,cdc.alshan
	,cdc.aly55wbno
	,cdc.aly55wbno_conv
	,cdc.alldty
	,cdc.altkid
	,cdc.altkid_conv
	,cdc.altemp
	,cdc.altemp_conv
	,cdc.aluom3
	,cdc.alstpu
	,cdc.alvlc1
	,cdc.alvlc1_conv
	,cdc.aldnty
	,cdc.aldnty_conv
	,cdc.aldend
	,cdc.aldend_conv
	,cdc.aldntp
	,cdc.almetn
	,cdc.almetn_conv
	,cdc.aly55cpnm
	,cdc.aly55crdid
	,cdc.aldsc1
	,cdc.aldsc1_conv
	,cdc.alflag
	,cdc.alflag_conv
	,cdc.aly55txt1
	,cdc.aly55txt1_conv
	,cdc.alev01
	,cdc.alev01_conv
	,cdc.alev02
	,cdc.alev02_conv
	,cdc.alev03
	,cdc.alev03_conv
	,cdc.alev04
	,cdc.alev04_conv
	,cdc.alev05
	,cdc.alev05_conv
	,cdc.alkcoo
	,cdc.alkcoo_conv
	,cdc.aldcto
	,cdc.aldoco
	,cdc.allnid
	,cdc.allnid_conv
	,cdc.alrkco
	,cdc.alrkco_conv
	,cdc.alrcto
	,cdc.alrorn
	,cdc.alrorn_conv
	,cdc.alxlin
	,cdc.alxlin_conv
	,cdc.alkco
	,cdc.alkco_conv
	,cdc.aldct
	,cdc.aldoc
	,cdc.allinn
	,cdc.allinn_conv
	,cdc.alokco
	,cdc.alokco_conv
	,cdc.alocto
	,cdc.aloorn
	,cdc.aloorn_conv
	,cdc.alogno
	,cdc.alogno_conv
	,cdc.alskco
	,cdc.alskco_conv
	,cdc.alsdct
	,cdc.alsdoc
	,cdc.alslne
	,cdc.alslne_conv
	,cdc.alicu
	,cdc.altd1
	,cdc.altd1_conv
	,cdc.aluser
	,cdc.aluser_conv
	,cdc.alpid
	,cdc.alpid_conv
	,cdc.aljobn
	,cdc.aljobn_conv
	,cdc.alupmj
	,cdc.alupmj_conv
	,cdc.alupmt
	,cdc.als1fu
	,cdc.als1fu_conv
	,cdc.als2fu
	,cdc.als2fu_conv
	,cdc.alfuf9
	,cdc.alfuf9_conv
	,cdc.alpstm
	,cdc.alcburst1
	,cdc.alcburst1_conv
	,cdc.alcburst2
	,cdc.alcburst2_conv
	,cdc.aleaurst1
	,cdc.aleaurst1_conv
	,cdc.aly55amnt1
	,cdc.aly55amnt1_conv
	,cdc.aly55amnt2
	,cdc.aly55amnt2_conv
	,cdc.aly55date1
	,cdc.aly55date1_conv
	,cdc.aly55date2
	,cdc.aly55date2_conv
	,cdc.aly55time1
	,cdc.aly55strg1
	,cdc.aly55strg1_conv
	,cdc.aly55strg2
	,cdc.aly55strg2_conv
	,cdc.aly55char1
	,cdc.aly55char1_conv
	,cdc.aly55char2
	,cdc.aly55char2_conv
FROM stg_jde.tmp_upsert_f554103_cdc cdc
LEFT OUTER JOIN rep_jde.f554103_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde.f554103_new AF:{{ task_instance_key_str }}' ) 