-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde.f554231h_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,szan83
	,szdoc
	,szaddj
	,szaddj_conv
	,szcmtb
	,szcmtb_conv
	,szptmb
	,szcmte
	,szcmte_conv
	,szptme
	,sztx1
	,sztx1_conv
	,szlnid
	,szlnid_conv
	,szaexp
	,szaexp_conv
	,szuprc
	,szuprc_conv
	,szecst
	,szecst_conv
	,szlprc
	,szlprc_conv
	,sztcst
	,sztcst_conv
	,szaopn
	,szaopn_conv
	,szdl02
	,szdl02_conv
	,szdods
	,szdods_conv
	,szcrcd
	,szcrcd_conv
	,sztdty
	,sztdty_conv
	,sztx2
	,sztx2_conv
	,szan81
	,szan82
	,szafit
	,szafit_conv
	,szgfl3
	,szgfl3_conv
	,szlitm
	,szlitm_conv
	,szcsht
	,szcsht_conv
	,sztkid
	,sztkid_conv
	,szuorg
	,szuorg_conv
	,szukid
	,szctr
	,szaccd21
	,szaccd21_conv
	,szshan
	,szan8
	,szcitm
	,szcitm_conv
	,szvend
	,szvend_conv
	,szemcu
	,szemcu_conv
	,szmcu
	,szmcu_conv
	,sza801
	,sza801_conv
	,szlocn
	,szlocn_conv
	,szttem
	,szttem_conv
	,szstpu
	,szdend
	,szdend_conv
	,szdntp
	,szlnty
	,szlnty_conv
	,szgfl5
	,szgfl5_conv
	,szgfl4
	,szgfl4_conv
	,szgfl6
	,szgfl6_conv
	,szekco
	,szekco_conv
	,szedct
	,szedct_conv
	,szedoc
	,szedln
	,szedln_conv
	,szedsp
	,szedsp_conv
	,szokco
	,szokco_conv
	,szoorn
	,szoorn_conv
	,szocto
	,szogno
	,szogno_conv
	,szgfl7
	,szgfl7_conv
	,szkcoo
	,szkcoo_conv
	,szdoco
	,szdcto
	,szlnic
	,szlnic_conv
	,szgfl8
	,szgfl8_conv
	,szrkco
	,szrkco_conv
	,szrorn
	,szrorn_conv
	,szrcto
	,szrlln
	,szrlln_conv
	,szgfl2
	,szgfl2_conv
	,szgflag1
	,szgflag1_conv
	,szgflag2
	,szgflag2_conv
	,szgflg
	,szgflg_conv
	,szdtbs
	,szbbdj
	,szbbdj_conv
	,szecod
	,szecod_conv
	,szedck
	,szedck_conv
	,szurat
	,szurat_conv
	,szurab
	,szurab_conv
	,szurnum12
	,szurnum12_conv
	,szurnum13
	,szurnum13_conv
	,szaa
	,szaa_conv
	,szaa1
	,szaa1_conv
	,szaa2
	,szaa2_conv
	,szaa3
	,szaa3_conv
	,szdsc
	,szdsc_conv
	,szdsc1
	,szdsc1_conv
	,szdsc2
	,szdsc2_conv
	,szdsc3
	,szdsc3_conv
	,szdsc4
	,szdsc4_conv
	,szdate01
	,szdate01_conv
	,szdate02
	,szdate02_conv
	,szdate03
	,szdate03_conv
	,szdate04
	,szdate04_conv
	,szcm01
	,szcm01_conv
	,szcm02
	,szcm02_conv
	,szcm03
	,szcm03_conv
	,szcm04
	,szcm04_conv
	,szcm05
	,szcm05_conv
	,szedtn
	,szedtn_conv
	,szeffutime
	,szeffutime_conv
	,szeetm
	,szeetm_conv
	,szedbt
	,szedbt_conv
	,szgfl1
	,szgfl1_conv
	,szaitm
	,szaitm_conv
	,szy55char1
	,szy55char1_conv
	,szy55char2
	,szy55char2_conv
	,szy55strg1
	,szy55strg1_conv
	,szy55strg2
	,szy55strg2_conv
	,szy55strg3
	,szy55strg3_conv
	,szy55strg4
	,szy55strg4_conv
	,szy55strg5
	,szy55strg5_conv
	,szy55amnt1
	,szy55amnt1_conv
	,szy55amnt2
	,szy55amnt2_conv
	,szaaq1
	,szaaq1_conv
	,szaaq2
	,szaaq2_conv
	,szaaq3
	,szaaq3_conv
	,szaaq4
	,szaaq4_conv
	,szy55time1
	,szy55time2
	,szy55date1
	,szy55date1_conv
	,szy55date2
	,szy55date2_conv
	,szuser
	,szuser_conv
	,szupmj
	,szupmj_conv
	,szupmt
	,szjobn
	,szjobn_conv
	,szpid
	,szpid_conv
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.szan83
	,cdc.szdoc
	,cdc.szaddj
	,cdc.szaddj_conv
	,cdc.szcmtb
	,cdc.szcmtb_conv
	,cdc.szptmb
	,cdc.szcmte
	,cdc.szcmte_conv
	,cdc.szptme
	,cdc.sztx1
	,cdc.sztx1_conv
	,cdc.szlnid
	,cdc.szlnid_conv
	,cdc.szaexp
	,cdc.szaexp_conv
	,cdc.szuprc
	,cdc.szuprc_conv
	,cdc.szecst
	,cdc.szecst_conv
	,cdc.szlprc
	,cdc.szlprc_conv
	,cdc.sztcst
	,cdc.sztcst_conv
	,cdc.szaopn
	,cdc.szaopn_conv
	,cdc.szdl02
	,cdc.szdl02_conv
	,cdc.szdods
	,cdc.szdods_conv
	,cdc.szcrcd
	,cdc.szcrcd_conv
	,cdc.sztdty
	,cdc.sztdty_conv
	,cdc.sztx2
	,cdc.sztx2_conv
	,cdc.szan81
	,cdc.szan82
	,cdc.szafit
	,cdc.szafit_conv
	,cdc.szgfl3
	,cdc.szgfl3_conv
	,cdc.szlitm
	,cdc.szlitm_conv
	,cdc.szcsht
	,cdc.szcsht_conv
	,cdc.sztkid
	,cdc.sztkid_conv
	,cdc.szuorg
	,cdc.szuorg_conv
	,cdc.szukid
	,cdc.szctr
	,cdc.szaccd21
	,cdc.szaccd21_conv
	,cdc.szshan
	,cdc.szan8
	,cdc.szcitm
	,cdc.szcitm_conv
	,cdc.szvend
	,cdc.szvend_conv
	,cdc.szemcu
	,cdc.szemcu_conv
	,cdc.szmcu
	,cdc.szmcu_conv
	,cdc.sza801
	,cdc.sza801_conv
	,cdc.szlocn
	,cdc.szlocn_conv
	,cdc.szttem
	,cdc.szttem_conv
	,cdc.szstpu
	,cdc.szdend
	,cdc.szdend_conv
	,cdc.szdntp
	,cdc.szlnty
	,cdc.szlnty_conv
	,cdc.szgfl5
	,cdc.szgfl5_conv
	,cdc.szgfl4
	,cdc.szgfl4_conv
	,cdc.szgfl6
	,cdc.szgfl6_conv
	,cdc.szekco
	,cdc.szekco_conv
	,cdc.szedct
	,cdc.szedct_conv
	,cdc.szedoc
	,cdc.szedln
	,cdc.szedln_conv
	,cdc.szedsp
	,cdc.szedsp_conv
	,cdc.szokco
	,cdc.szokco_conv
	,cdc.szoorn
	,cdc.szoorn_conv
	,cdc.szocto
	,cdc.szogno
	,cdc.szogno_conv
	,cdc.szgfl7
	,cdc.szgfl7_conv
	,cdc.szkcoo
	,cdc.szkcoo_conv
	,cdc.szdoco
	,cdc.szdcto
	,cdc.szlnic
	,cdc.szlnic_conv
	,cdc.szgfl8
	,cdc.szgfl8_conv
	,cdc.szrkco
	,cdc.szrkco_conv
	,cdc.szrorn
	,cdc.szrorn_conv
	,cdc.szrcto
	,cdc.szrlln
	,cdc.szrlln_conv
	,cdc.szgfl2
	,cdc.szgfl2_conv
	,cdc.szgflag1
	,cdc.szgflag1_conv
	,cdc.szgflag2
	,cdc.szgflag2_conv
	,cdc.szgflg
	,cdc.szgflg_conv
	,cdc.szdtbs
	,cdc.szbbdj
	,cdc.szbbdj_conv
	,cdc.szecod
	,cdc.szecod_conv
	,cdc.szedck
	,cdc.szedck_conv
	,cdc.szurat
	,cdc.szurat_conv
	,cdc.szurab
	,cdc.szurab_conv
	,cdc.szurnum12
	,cdc.szurnum12_conv
	,cdc.szurnum13
	,cdc.szurnum13_conv
	,cdc.szaa
	,cdc.szaa_conv
	,cdc.szaa1
	,cdc.szaa1_conv
	,cdc.szaa2
	,cdc.szaa2_conv
	,cdc.szaa3
	,cdc.szaa3_conv
	,cdc.szdsc
	,cdc.szdsc_conv
	,cdc.szdsc1
	,cdc.szdsc1_conv
	,cdc.szdsc2
	,cdc.szdsc2_conv
	,cdc.szdsc3
	,cdc.szdsc3_conv
	,cdc.szdsc4
	,cdc.szdsc4_conv
	,cdc.szdate01
	,cdc.szdate01_conv
	,cdc.szdate02
	,cdc.szdate02_conv
	,cdc.szdate03
	,cdc.szdate03_conv
	,cdc.szdate04
	,cdc.szdate04_conv
	,cdc.szcm01
	,cdc.szcm01_conv
	,cdc.szcm02
	,cdc.szcm02_conv
	,cdc.szcm03
	,cdc.szcm03_conv
	,cdc.szcm04
	,cdc.szcm04_conv
	,cdc.szcm05
	,cdc.szcm05_conv
	,cdc.szedtn
	,cdc.szedtn_conv
	,cdc.szeffutime
	,cdc.szeffutime_conv
	,cdc.szeetm
	,cdc.szeetm_conv
	,cdc.szedbt
	,cdc.szedbt_conv
	,cdc.szgfl1
	,cdc.szgfl1_conv
	,cdc.szaitm
	,cdc.szaitm_conv
	,cdc.szy55char1
	,cdc.szy55char1_conv
	,cdc.szy55char2
	,cdc.szy55char2_conv
	,cdc.szy55strg1
	,cdc.szy55strg1_conv
	,cdc.szy55strg2
	,cdc.szy55strg2_conv
	,cdc.szy55strg3
	,cdc.szy55strg3_conv
	,cdc.szy55strg4
	,cdc.szy55strg4_conv
	,cdc.szy55strg5
	,cdc.szy55strg5_conv
	,cdc.szy55amnt1
	,cdc.szy55amnt1_conv
	,cdc.szy55amnt2
	,cdc.szy55amnt2_conv
	,cdc.szaaq1
	,cdc.szaaq1_conv
	,cdc.szaaq2
	,cdc.szaaq2_conv
	,cdc.szaaq3
	,cdc.szaaq3_conv
	,cdc.szaaq4
	,cdc.szaaq4_conv
	,cdc.szy55time1
	,cdc.szy55time2
	,cdc.szy55date1
	,cdc.szy55date1_conv
	,cdc.szy55date2
	,cdc.szy55date2_conv
	,cdc.szuser
	,cdc.szuser_conv
	,cdc.szupmj
	,cdc.szupmj_conv
	,cdc.szupmt
	,cdc.szjobn
	,cdc.szjobn_conv
	,cdc.szpid
	,cdc.szpid_conv
FROM stg_jde.tmp_upsert_f554231h_cdc cdc
LEFT OUTER JOIN rep_jde.f554231h_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde.f554231h_new AF:{{ task_instance_key_str }}' ) 