-- Insert new rows from upsert table into rep new table
INSERT INTO rep_jde.f554901_new
(
    	sys_file_name
	,sys_file_ln
	,sys_integration_id
	,sys_extract_dt
	,sys_cdc_dt
	,sys_cdc_scn
	,sys_cdc_operation_type
	,sys_cdc_before_after
	,sys_line_modified_ind
	,ddvr01
	,ddvr01_conv
	,dddoco
	,ddlnid
	,ddlnid_conv
	,ddlitm
	,ddlitm_conv
	,ddy55doco
	,ddy55doco_conv
	,ddy55msgno
	,ddy55msgno_conv
	,ddy55insdj
	,ddy55insdj_conv
	,ddy55insdt
	,ddshpn
	,ddssts
	,ddkcoo
	,ddkcoo_conv
	,dddcto
	,ddy55dlqs
	,ddy55dlqs_conv
	,ddums
	,ddums_conv
	,ddtemp
	,ddtemp_conv
	,ddy55tnfl
	,ddy55tnfl_conv
	,ddy55orfg
	,ddy55orfg_conv
	,dddcdt
	,dddcdt_conv
	,dddldl
	,dddldl_conv
	,ddy55aclt
	,dddisn
	,ddy55xcrd
	,ddy55ycrd
	,ddcmqt
	,ddcmqt_conv
	,ddy55drcd
	,ddy55drcd_conv
	,dddlda
	,dddlda_conv
	,ddtdlf
	,ddy55tpdt
	,ddy55gpsf
	,ddy55pdflg
	,ddy55pdflg_conv
	,ddy55disn1
	,ddy55cttm
	,ddmcux
	,ddmcux_conv
	,ddshan
	,ddcrcp
	,ddcrcp_conv
	,ddfrvc
	,ddfrvc_conv
	,dddoc
	,ddgnrt
	,ddgnrt_conv
	,ddy55gnno
	,ddy55gnno_conv
	,ddtkid
	,ddtkid_conv
	,dddend
	,dddend_conv
	,ddqtyl
	,ddqtyl_conv
	,ddcert
	,ddy55govid
	,ddy55govid_conv
	,ddedbt
	,ddedbt_conv
	,ddedtn
	,ddedtn_conv
	,ddflag
	,ddflag_conv
	,dduser
	,dduser_conv
	,ddpid
	,ddpid_conv
	,ddjobn
	,ddjobn_conv
	,ddupmj
	,ddupmj_conv
	,ddupmt
	,ddurcd
	,ddurcd_conv
	,ddurdt
	,ddurdt_conv
	,ddurat
	,ddurat_conv
	,ddurrf
	,ddurrf_conv
	,ddurab
	,ddurab_conv
	,ddrcd
	,ddy55char1
	,ddy55char1_conv
	,ddy55char2
	,ddy55char2_conv
	,ddy55date1
	,ddy55date1_conv
	,ddy55date2
	,ddy55date2_conv
	,ddy55strg1
	,ddy55strg1_conv
	,ddy55strg2
	,ddy55strg2_conv
	,ddy55strg3
	,ddy55strg3_conv
	,ddy55strg4
	,ddy55strg4_conv
	,ddy55strg5
	,ddy55strg5_conv
	,ddy55strg6
	,ddy55strg6_conv
	,ddy55strg7
	,ddy55strg7_conv
	,ddy55strg8
	,ddy55strg8_conv
	,ddy55strg9
	,ddy55strg9_conv
	,ddy55strg10
	,ddy55strg10_conv
	,ddy55flg1
	,ddy55flg1_conv
	,ddy55flg2
	,ddy55flg2_conv
	,ddy55num3
	,ddy55num3_conv
	,ddy55num4
	,ddy55num4_conv
	,ddy55time1
	,ddy55time2
	,ddy55amnt1
	,ddy55amnt1_conv
	,ddy55amnt2
	,ddy55amnt2_conv
	,ddordnumid
	,ddordnumid_conv
	,ddrornumid
	,ddrornumid_conv
	,ddvmcu
	,ddvmcu_conv
	,ddflg2
	,ddflg2_conv
	,ddflg3
	,ddflg3_conv
	,ddflg4
	,ddflg4_conv
	,ddukid
	,ddboolean
	,ddppdj
	,ddppdj_conv
	,ddcflg
	,ddgovid1
	,ddgovid1_conv
	,ddot1
	,ddot1_conv
	,ddef01
	,ddflg1
	,ddflg1_conv
	,ddfmrund
	,ddfmrund_conv
	,ddsclq
	,ddsclq_conv
	,ddtme0
	,dddte
	,dddte_conv
	,ddancc
	,ddorgn
	,ddtdlt
	,dditm
	,ddxpitraid
	,ddxpitraid_conv
	,ddy55cert
	,ddy55cert_conv
	,ddy55qlty
	,ddy55qlty_conv
	,ddy55zdrcd
)
SELECT
    	cdc.sys_file_name
	,cdc.sys_file_ln
	,cdc.sys_integration_id
	,cdc.sys_extract_dt
	,cdc.sys_cdc_dt
	,cdc.sys_cdc_scn
	,cdc.sys_cdc_operation_type
	,cdc.sys_cdc_before_after
	,cdc.sys_line_modified_ind
	,cdc.ddvr01
	,cdc.ddvr01_conv
	,cdc.dddoco
	,cdc.ddlnid
	,cdc.ddlnid_conv
	,cdc.ddlitm
	,cdc.ddlitm_conv
	,cdc.ddy55doco
	,cdc.ddy55doco_conv
	,cdc.ddy55msgno
	,cdc.ddy55msgno_conv
	,cdc.ddy55insdj
	,cdc.ddy55insdj_conv
	,cdc.ddy55insdt
	,cdc.ddshpn
	,cdc.ddssts
	,cdc.ddkcoo
	,cdc.ddkcoo_conv
	,cdc.dddcto
	,cdc.ddy55dlqs
	,cdc.ddy55dlqs_conv
	,cdc.ddums
	,cdc.ddums_conv
	,cdc.ddtemp
	,cdc.ddtemp_conv
	,cdc.ddy55tnfl
	,cdc.ddy55tnfl_conv
	,cdc.ddy55orfg
	,cdc.ddy55orfg_conv
	,cdc.dddcdt
	,cdc.dddcdt_conv
	,cdc.dddldl
	,cdc.dddldl_conv
	,cdc.ddy55aclt
	,cdc.dddisn
	,cdc.ddy55xcrd
	,cdc.ddy55ycrd
	,cdc.ddcmqt
	,cdc.ddcmqt_conv
	,cdc.ddy55drcd
	,cdc.ddy55drcd_conv
	,cdc.dddlda
	,cdc.dddlda_conv
	,cdc.ddtdlf
	,cdc.ddy55tpdt
	,cdc.ddy55gpsf
	,cdc.ddy55pdflg
	,cdc.ddy55pdflg_conv
	,cdc.ddy55disn1
	,cdc.ddy55cttm
	,cdc.ddmcux
	,cdc.ddmcux_conv
	,cdc.ddshan
	,cdc.ddcrcp
	,cdc.ddcrcp_conv
	,cdc.ddfrvc
	,cdc.ddfrvc_conv
	,cdc.dddoc
	,cdc.ddgnrt
	,cdc.ddgnrt_conv
	,cdc.ddy55gnno
	,cdc.ddy55gnno_conv
	,cdc.ddtkid
	,cdc.ddtkid_conv
	,cdc.dddend
	,cdc.dddend_conv
	,cdc.ddqtyl
	,cdc.ddqtyl_conv
	,cdc.ddcert
	,cdc.ddy55govid
	,cdc.ddy55govid_conv
	,cdc.ddedbt
	,cdc.ddedbt_conv
	,cdc.ddedtn
	,cdc.ddedtn_conv
	,cdc.ddflag
	,cdc.ddflag_conv
	,cdc.dduser
	,cdc.dduser_conv
	,cdc.ddpid
	,cdc.ddpid_conv
	,cdc.ddjobn
	,cdc.ddjobn_conv
	,cdc.ddupmj
	,cdc.ddupmj_conv
	,cdc.ddupmt
	,cdc.ddurcd
	,cdc.ddurcd_conv
	,cdc.ddurdt
	,cdc.ddurdt_conv
	,cdc.ddurat
	,cdc.ddurat_conv
	,cdc.ddurrf
	,cdc.ddurrf_conv
	,cdc.ddurab
	,cdc.ddurab_conv
	,cdc.ddrcd
	,cdc.ddy55char1
	,cdc.ddy55char1_conv
	,cdc.ddy55char2
	,cdc.ddy55char2_conv
	,cdc.ddy55date1
	,cdc.ddy55date1_conv
	,cdc.ddy55date2
	,cdc.ddy55date2_conv
	,cdc.ddy55strg1
	,cdc.ddy55strg1_conv
	,cdc.ddy55strg2
	,cdc.ddy55strg2_conv
	,cdc.ddy55strg3
	,cdc.ddy55strg3_conv
	,cdc.ddy55strg4
	,cdc.ddy55strg4_conv
	,cdc.ddy55strg5
	,cdc.ddy55strg5_conv
	,cdc.ddy55strg6
	,cdc.ddy55strg6_conv
	,cdc.ddy55strg7
	,cdc.ddy55strg7_conv
	,cdc.ddy55strg8
	,cdc.ddy55strg8_conv
	,cdc.ddy55strg9
	,cdc.ddy55strg9_conv
	,cdc.ddy55strg10
	,cdc.ddy55strg10_conv
	,cdc.ddy55flg1
	,cdc.ddy55flg1_conv
	,cdc.ddy55flg2
	,cdc.ddy55flg2_conv
	,cdc.ddy55num3
	,cdc.ddy55num3_conv
	,cdc.ddy55num4
	,cdc.ddy55num4_conv
	,cdc.ddy55time1
	,cdc.ddy55time2
	,cdc.ddy55amnt1
	,cdc.ddy55amnt1_conv
	,cdc.ddy55amnt2
	,cdc.ddy55amnt2_conv
	,cdc.ddordnumid
	,cdc.ddordnumid_conv
	,cdc.ddrornumid
	,cdc.ddrornumid_conv
	,cdc.ddvmcu
	,cdc.ddvmcu_conv
	,cdc.ddflg2
	,cdc.ddflg2_conv
	,cdc.ddflg3
	,cdc.ddflg3_conv
	,cdc.ddflg4
	,cdc.ddflg4_conv
	,cdc.ddukid
	,cdc.ddboolean
	,cdc.ddppdj
	,cdc.ddppdj_conv
	,cdc.ddcflg
	,cdc.ddgovid1
	,cdc.ddgovid1_conv
	,cdc.ddot1
	,cdc.ddot1_conv
	,cdc.ddef01
	,cdc.ddflg1
	,cdc.ddflg1_conv
	,cdc.ddfmrund
	,cdc.ddfmrund_conv
	,cdc.ddsclq
	,cdc.ddsclq_conv
	,cdc.ddtme0
	,cdc.dddte
	,cdc.dddte_conv
	,cdc.ddancc
	,cdc.ddorgn
	,cdc.ddtdlt
	,cdc.dditm
	,cdc.ddxpitraid
	,cdc.ddxpitraid_conv
	,cdc.ddy55cert
	,cdc.ddy55cert_conv
	,cdc.ddy55qlty
	,cdc.ddy55qlty_conv
	,cdc.ddy55zdrcd
FROM stg_jde.tmp_upsert_f554901_cdc cdc
LEFT OUTER JOIN rep_jde.f554901_new f ON cdc.sys_integration_id = f.sys_integration_id
WHERE f.sys_integration_id IS NULL
OPTION ( LABEL = 'INSERT_rep_jde.f554901_new AF:{{ task_instance_key_str }}' ) 