--Create ext table for cdc
IF OBJECT_ID('stg_jde_qat.ext_f3112_cdc') IS NOT NULL
    DROP EXTERNAL TABLE stg_jde_qat.ext_f3112_cdc


CREATE EXTERNAL TABLE stg_jde_qat.ext_f3112_cdc
(
	[sys_file_name] [NVARCHAR](100) 
	,[sys_file_ln] [VARCHAR](20) 
	,[sys_integration_id] [NVARCHAR](200) 
	,[sys_extract_dt] [NVARCHAR](40) 
	,[sys_cdc_dt] [NVARCHAR](40) 
	,[sys_cdc_scn] [NVARCHAR](14) 
	,[sys_cdc_operation_type] [NVARCHAR](15) 
	,[sys_cdc_before_after] [NVARCHAR](10) 
	,[sys_line_modified_ind] [VARCHAR](20) 
	,[wldoco] [DECIMAL](38, 4) 
	,[wldcto] [NVARCHAR](2) 
	,[wlsfxo] [NVARCHAR](3) 
	,[wltrt] [NVARCHAR](3) 
	,[wlkit] [DECIMAL](38, 4) 
	,[wlkitl] [NVARCHAR](25) 
	,[wlkita] [NVARCHAR](25) 
	,[wlmmcu] [NVARCHAR](12) 
	,[wlline] [NVARCHAR](12) 
	,[wlmcu] [NVARCHAR](12) 
	,[wlald] [NVARCHAR](4) 
	,[wldsc1] [NVARCHAR](30) 
	,[wlopsq] [DECIMAL](38, 4) 
	,[wlopsc] [NVARCHAR](2) 
	,[wlopst] [NVARCHAR](2) 
	,[wlinpe] [NVARCHAR](2) 
	,[wltimb] [NVARCHAR](1) 
	,[wllamc] [NVARCHAR](1) 
	,[wlbfpf] [NVARCHAR](1) 
	,[wlpprf] [NVARCHAR](1) 
	,[wljbcd] [NVARCHAR](6) 
	,[wlan8] [DECIMAL](38, 4) 
	,[wlcrtr] [DECIMAL](38, 4) 
	,[wlsltr] [DECIMAL](38, 4) 
	,[wltrdj] [VARCHAR](20) 
	,[wldrqj] [VARCHAR](20) 
	,[wlstrt] [VARCHAR](20) 
	,[wlstrx] [VARCHAR](20) 
	,[wlrsft] [NVARCHAR](1) 
	,[wlssft] [NVARCHAR](1) 
	,[wlcsft] [NVARCHAR](1) 
	,[wlltpc] [DECIMAL](38, 4) 
	,[wlpovr] [DECIMAL](38, 4) 
	,[wlopyp] [DECIMAL](38, 4) 
	,[wlcpyp] [DECIMAL](38, 4) 
	,[wlnxop] [DECIMAL](38, 4) 
	,[wlsetc] [DECIMAL](38, 4) 
	,[wlmovd] [DECIMAL](38, 4) 
	,[wlqued] [DECIMAL](38, 4) 
	,[wlrunm] [DECIMAL](38, 4) 
	,[wlrunl] [DECIMAL](38, 4) 
	,[wlsetl] [DECIMAL](38, 4) 
	,[wlmaca] [DECIMAL](38, 4) 
	,[wllaba] [DECIMAL](38, 4) 
	,[wlseta] [DECIMAL](38, 4) 
	,[wlopsr] [DECIMAL](38, 4) 
	,[wluorg] [DECIMAL](38, 4) 
	,[wlsocn] [DECIMAL](38, 4) 
	,[wlsoqs] [DECIMAL](38, 4) 
	,[wlqmto] [DECIMAL](38, 4) 
	,[wlpwrt] [DECIMAL](38, 4) 
	,[wluom] [NVARCHAR](2) 
	,[wlcts2] [DECIMAL](38, 4) 
	,[wlcts3] [DECIMAL](38, 4) 
	,[wlcts4] [DECIMAL](38, 4) 
	,[wlcts5] [DECIMAL](38, 4) 
	,[wlcts6] [DECIMAL](38, 4) 
	,[wlapid] [NVARCHAR](12) 
	,[wlshno] [NVARCHAR](10) 
	,[wlomcu] [NVARCHAR](12) 
	,[wlobj] [NVARCHAR](6) 
	,[wlsub] [NVARCHAR](8) 
	,[wlvend] [DECIMAL](38, 4) 
	,[wlrkco] [NVARCHAR](5) 
	,[wlrorn] [NVARCHAR](8) 
	,[wlrcto] [NVARCHAR](2) 
	,[wlrlln] [DECIMAL](38, 4) 
	,[wldct] [NVARCHAR](2) 
	,[wlurcd] [NVARCHAR](2) 
	,[wlurdt] [VARCHAR](20) 
	,[wlurat] [DECIMAL](38, 4) 
	,[wlurrf] [NVARCHAR](15) 
	,[wlurab] [DECIMAL](38, 4) 
	,[wluser] [NVARCHAR](10) 
	,[wlpid] [NVARCHAR](10) 
	,[wljobn] [NVARCHAR](10) 
	,[wlupmj] [VARCHAR](20) 
	,[wltday] [DECIMAL](38, 4) 
	,[wllocn] [NVARCHAR](20) 
	,[wlruc] [DECIMAL](38, 4) 
	,[wlcapu] [NVARCHAR](2) 
	,[wlwmcu] [NVARCHAR](12) 
	,[wlcmhr] [DECIMAL](38, 4) 
	,[wlclhr] [DECIMAL](38, 4) 
	,[wlcshr] [DECIMAL](38, 4) 
	,[wlcost] [NVARCHAR](3) 
	,[wlactb] [NVARCHAR](10) 
	,[wlnumb] [DECIMAL](38, 4) 
	,[wlcts7] [DECIMAL](38, 4) 
	,[wlcts8] [DECIMAL](38, 4) 
	,[wlcts9] [DECIMAL](38, 4) 
	,[wllabp] [DECIMAL](38, 4) 
	,[wlmacr] [DECIMAL](38, 4) 
	,[wlsetr] [DECIMAL](38, 4) 
	,[wlapsc] [NVARCHAR](1) 
	,[wlsest] [DECIMAL](38, 4) 
	,[wlseet] [DECIMAL](38, 4) 
	,[wltmco] [DECIMAL](38, 4) 
	,[wld2j] [VARCHAR](20) 
	,[wlstti] [DECIMAL](38, 4) 
	,[wlcmpe] [NVARCHAR](3) 
	,[wlcmpc] [NVARCHAR](10) 
	,[wlcplvlfr] [DECIMAL](38, 4) 
	,[wlcplvlto] [DECIMAL](38, 4) 
	,[wlcmrq] [NVARCHAR](1) 
	,[wlansa] [DECIMAL](38, 4) 
	,[wlanpa] [DECIMAL](38, 4) 
	,[wlanp] [DECIMAL](38, 4) 
	,[wlwschf] [NVARCHAR](1) 
	,[wltraf] [NVARCHAR](1) 
)
WITH
(
    LOCATION='processing-clean/jde_qat/f3112/cdc/'
    ,DATA_SOURCE = [dw-landing-fs]
    ,FILE_FORMAT = [jde_fileformat_124_127_no_header]
)
