--Create ext table for cdc
IF OBJECT_ID('stg_jde_qat.ext_f38111_cdc') IS NOT NULL
    DROP EXTERNAL TABLE stg_jde_qat.ext_f38111_cdc


CREATE EXTERNAL TABLE stg_jde_qat.ext_f38111_cdc
(
	[sys_file_name] [NVARCHAR](100) 
	,[sys_file_ln] [VARCHAR](20) 
	,[sys_integration_id] [NVARCHAR](200) 
	,[sys_extract_dt] [NVARCHAR](40) 
	,[sys_cdc_dt] [NVARCHAR](40) 
	,[sys_cdc_scn] [NVARCHAR](14) 
	,[sys_cdc_operation_type] [NVARCHAR](15) 
	,[sys_cdc_before_after] [NVARCHAR](10) 
	,[sys_line_modified_ind] [VARCHAR](20) 
	,[dzdmct] [NVARCHAR](12) 
	,[dzdmcs] [DECIMAL](38, 4) 
	,[dzdmtc] [NVARCHAR](1) 
	,[dzan8] [DECIMAL](38, 4) 
	,[dzan8r] [DECIMAL](38, 4) 
	,[dzitm] [DECIMAL](38, 4) 
	,[dzmcu] [NVARCHAR](12) 
	,[dzco] [NVARCHAR](5) 
	,[dzlocn] [NVARCHAR](20) 
	,[dzlot] [NVARCHAR](30) 
	,[dztcaj] [NVARCHAR](1) 
	,[dztrdj] [VARCHAR](20) 
	,[dzadjj] [VARCHAR](20) 
	,[dzdct] [NVARCHAR](2) 
	,[dzdoc] [DECIMAL](38, 4) 
	,[dzkco] [NVARCHAR](5) 
	,[dzjeln] [DECIMAL](38, 4) 
	,[dzdoco] [DECIMAL](38, 4) 
	,[dzdcto] [NVARCHAR](2) 
	,[dzkcoo] [NVARCHAR](5) 
	,[dzlnid] [DECIMAL](38, 4) 
	,[dzvehi] [NVARCHAR](12) 
	,[dzvmcu] [NVARCHAR](12) 
	,[dztrp] [DECIMAL](38, 4) 
	,[dzcmpn] [DECIMAL](38, 4) 
	,[dzdto] [NVARCHAR](1) 
	,[dzdes] [NVARCHAR](12) 
	,[dzdesy] [NVARCHAR](2) 
	,[dzpsr] [NVARCHAR](12) 
	,[dzpsry] [NVARCHAR](2) 
	,[dzseq] [DECIMAL](38, 4) 
	,[dztrex] [NVARCHAR](30) 
	,[dztrqt] [DECIMAL](38, 4) 
	,[dzuom] [NVARCHAR](2) 
	,[dztemp] [DECIMAL](38, 4) 
	,[dzstpu] [NVARCHAR](1) 
	,[dzdnty] [DECIMAL](38, 4) 
	,[dzdntp] [NVARCHAR](1) 
	,[dzdetp] [DECIMAL](38, 4) 
	,[dzdtpu] [NVARCHAR](1) 
	,[dzambr] [DECIMAL](38, 4) 
	,[dzambu] [NVARCHAR](2) 
	,[dzvcf] [DECIMAL](38, 4) 
	,[dzstok] [DECIMAL](38, 4) 
	,[dzbum4] [NVARCHAR](2) 
	,[dzwgtr] [DECIMAL](38, 4) 
	,[dzbum5] [NVARCHAR](2) 
	,[dzstum] [DECIMAL](38, 4) 
	,[dzbum6] [NVARCHAR](2) 
	,[dzpras] [NVARCHAR](1) 
	,[dzaa] [DECIMAL](38, 4) 
	,[dzcrcd] [NVARCHAR](3) 
	,[dzuncs] [DECIMAL](38, 4) 
	,[dzpaid] [DECIMAL](38, 4) 
	,[dzdgl] [VARCHAR](20) 
	,[dzicu] [DECIMAL](38, 4) 
	,[dzicut] [NVARCHAR](2) 
	,[dzglpt] [NVARCHAR](4) 
	,[dzadzr] [NVARCHAR](1) 
	,[dzrcd] [NVARCHAR](3) 
	,[dzrecs] [NVARCHAR](1) 
	,[dzcrdj] [VARCHAR](20) 
	,[dzukid] [DECIMAL](38, 4) 
	,[dzupgl] [NVARCHAR](1) 
	,[dzsvpf] [NVARCHAR](1) 
	,[dzsvpd] [VARCHAR](20) 
	,[dzprtf] [NVARCHAR](1) 
	,[dzcrpo] [NVARCHAR](1) 
	,[dzcrso] [NVARCHAR](1) 
	,[dzcdmc] [NVARCHAR](1) 
	,[dzcand] [VARCHAR](20) 
	,[dzcanr] [NVARCHAR](3) 
	,[dztv01] [NVARCHAR](1) 
	,[dztv02] [NVARCHAR](1) 
	,[dztv03] [NVARCHAR](1) 
	,[dzurcd] [NVARCHAR](2) 
	,[dzurdt] [VARCHAR](20) 
	,[dzurat] [DECIMAL](38, 4) 
	,[dzurab] [DECIMAL](38, 4) 
	,[dzurrf] [NVARCHAR](15) 
	,[dzuser] [NVARCHAR](10) 
	,[dzpid] [NVARCHAR](10) 
	,[dzjobn] [NVARCHAR](10) 
	,[dzupmj] [VARCHAR](20) 
	,[dztday] [DECIMAL](38, 4) 
)
WITH
(
    LOCATION='processing-clean/jde_qat/f38111/cdc/'
    ,DATA_SOURCE = [dw-landing-fs]
    ,FILE_FORMAT = [jde_fileformat_124_127_no_header]
)
