--Create ext table for cdc
IF OBJECT_ID('stg_jde_qat.ext_f4111_cdc') IS NOT NULL
    DROP EXTERNAL TABLE stg_jde_qat.ext_f4111_cdc


CREATE EXTERNAL TABLE stg_jde_qat.ext_f4111_cdc
(
	[sys_file_name] [NVARCHAR](100) 
	,[sys_file_ln] [VARCHAR](20) 
	,[sys_integration_id] [NVARCHAR](200) 
	,[sys_extract_dt] [NVARCHAR](40) 
	,[sys_cdc_dt] [NVARCHAR](40) 
	,[sys_cdc_scn] [NVARCHAR](14) 
	,[sys_cdc_operation_type] [NVARCHAR](15) 
	,[sys_cdc_before_after] [NVARCHAR](10) 
	,[sys_line_modified_ind] [VARCHAR](20) 
	,[ilnlin] [DECIMAL](38, 4) 
	,[ilitm] [DECIMAL](38, 4) 
	,[illitm] [NVARCHAR](25) 
	,[ilaitm] [NVARCHAR](25) 
	,[ilmcu] [NVARCHAR](12) 
	,[illocn] [NVARCHAR](20) 
	,[illotn] [NVARCHAR](30) 
	,[ilplot] [NVARCHAR](30) 
	,[ilstun] [DECIMAL](38, 4) 
	,[illdsq] [DECIMAL](38, 4) 
	,[iltrno] [DECIMAL](38, 4) 
	,[ilfrto] [NVARCHAR](1) 
	,[illmcx] [NVARCHAR](1) 
	,[illots] [NVARCHAR](1) 
	,[illotp] [DECIMAL](38, 4) 
	,[illotg] [NVARCHAR](3) 
	,[ilkit] [DECIMAL](38, 4) 
	,[ilmmcu] [NVARCHAR](12) 
	,[ildmct] [NVARCHAR](12) 
	,[ildmcs] [DECIMAL](38, 4) 
	,[ilkco] [NVARCHAR](5) 
	,[ildoc] [DECIMAL](38, 4) 
	,[ildct] [NVARCHAR](2) 
	,[ilsfx] [NVARCHAR](3) 
	,[iljeln] [DECIMAL](38, 4) 
	,[ilicu] [DECIMAL](38, 4) 
	,[ildgl] [VARCHAR](20) 
	,[ilglpt] [NVARCHAR](4) 
	,[ildcto] [NVARCHAR](2) 
	,[ildoco] [DECIMAL](38, 4) 
	,[ilkcoo] [NVARCHAR](5) 
	,[illnid] [DECIMAL](38, 4) 
	,[ilipcd] [NVARCHAR](1) 
	,[iltrdj] [VARCHAR](20) 
	,[iltrum] [NVARCHAR](2) 
	,[ilan8] [DECIMAL](38, 4) 
	,[iltrex] [NVARCHAR](30) 
	,[iltref] [NVARCHAR](8) 
	,[ilrcd] [NVARCHAR](3) 
	,[iltrqt] [DECIMAL](38, 4) 
	,[iluncs] [DECIMAL](38, 4) 
	,[ilpaid] [DECIMAL](38, 4) 
	,[ilterm] [NVARCHAR](10) 
	,[ilukid] [DECIMAL](38, 4) 
	,[iltday] [DECIMAL](38, 4) 
	,[iluser] [NVARCHAR](10) 
	,[ilpid] [NVARCHAR](10) 
	,[ilcrdj] [VARCHAR](20) 
	,[ilaid] [NVARCHAR](8) 
	,[ilasid] [NVARCHAR](25) 
	,[ilmcuz] [NVARCHAR](12) 
	,[ilobj] [NVARCHAR](6) 
	,[ilsbl] [NVARCHAR](8) 
	,[ilsub] [NVARCHAR](8) 
	,[iluom2] [NVARCHAR](2) 
	,[ilcmoo] [NVARCHAR](1) 
	,[ilre] [NVARCHAR](1) 
	,[ilsblt] [NVARCHAR](1) 
	,[ilsqor] [DECIMAL](38, 4) 
	,[ilvpej] [VARCHAR](20) 
	,[ilhdgj] [VARCHAR](20) 
	,[ilshan] [DECIMAL](38, 4) 
	,[ilopsq] [DECIMAL](38, 4) 
	,[ilrfln] [DECIMAL](38, 4) 
	,[iltgn] [DECIMAL](38, 4) 
	,[illotc] [NVARCHAR](3) 
	,[ilsvdt] [VARCHAR](20) 
	,[illrcd] [NVARCHAR](3) 
	,[ilrlot] [NVARCHAR](30) 
	,[illpnu] [NVARCHAR](40) 
	,[ilpmpn] [NVARCHAR](30) 
	,[ilpns] [DECIMAL](38, 4) 
)
WITH
(
    LOCATION='processing-clean/jde_qat/f4111/cdc/'
    ,DATA_SOURCE = [dw-landing-fs]
    ,FILE_FORMAT = [jde_fileformat_124_127_no_header]
)
