--Create ext table for cdc
IF OBJECT_ID('stg_jde_qat.ext_f41511_cdc') IS NOT NULL
    DROP EXTERNAL TABLE stg_jde_qat.ext_f41511_cdc


CREATE EXTERNAL TABLE stg_jde_qat.ext_f41511_cdc
(
	[sys_file_name] [NVARCHAR](100) 
	,[sys_file_ln] [VARCHAR](20) 
	,[sys_integration_id] [NVARCHAR](200) 
	,[sys_extract_dt] [NVARCHAR](40) 
	,[sys_cdc_dt] [NVARCHAR](40) 
	,[sys_cdc_scn] [NVARCHAR](14) 
	,[sys_cdc_operation_type] [NVARCHAR](15) 
	,[sys_cdc_before_after] [NVARCHAR](10) 
	,[sys_line_modified_ind] [VARCHAR](20) 
	,[padoc] [DECIMAL](38, 4) 
	,[pajeln] [DECIMAL](38, 4) 
	,[padct] [NVARCHAR](2) 
	,[pakco] [NVARCHAR](5) 
	,[padoco] [DECIMAL](38, 4) 
	,[padcto] [NVARCHAR](2) 
	,[pakcoo] [NVARCHAR](5) 
	,[palnid] [DECIMAL](38, 4) 
	,[panlin] [DECIMAL](38, 4) 
	,[padgl] [VARCHAR](20) 
	,[patrdj] [VARCHAR](20) 
	,[paicu] [DECIMAL](38, 4) 
	,[patrcd] [NVARCHAR](1) 
	,[pamcu] [NVARCHAR](12) 
	,[patkid] [NVARCHAR](8) 
	,[paitm] [DECIMAL](38, 4) 
	,[patrno] [DECIMAL](38, 4) 
	,[patemp] [DECIMAL](38, 4) 
	,[pastpu] [NVARCHAR](1) 
	,[padnty] [DECIMAL](38, 4) 
	,[padntp] [NVARCHAR](1) 
	,[padetp] [DECIMAL](38, 4) 
	,[padtpu] [NVARCHAR](1) 
	,[paambr] [DECIMAL](38, 4) 
	,[pabum3] [NVARCHAR](2) 
	,[paambi] [DECIMAL](38, 4) 
	,[paambu] [NVARCHAR](2) 
	,[pavcf] [DECIMAL](38, 4) 
	,[pastok] [DECIMAL](38, 4) 
	,[pabum4] [NVARCHAR](2) 
	,[pawgtr] [DECIMAL](38, 4) 
	,[pabum5] [NVARCHAR](2) 
	,[pastum] [DECIMAL](38, 4) 
	,[pabum6] [NVARCHAR](2) 
	,[parcd] [NVARCHAR](3) 
	,[paupcf] [NVARCHAR](1) 
	,[palotn] [NVARCHAR](30) 
	,[palots] [NVARCHAR](1) 
	,[pammej] [VARCHAR](20) 
	,[pauncs] [DECIMAL](38, 4) 
	,[paecst] [DECIMAL](38, 4) 
	,[patrex] [NVARCHAR](30) 
	,[paan8] [DECIMAL](38, 4) 
	,[padmct] [NVARCHAR](12) 
	,[padmcs] [DECIMAL](38, 4) 
	,[paacor] [NVARCHAR](1) 
	,[pahcor] [NVARCHAR](1) 
	,[padipt] [NVARCHAR](1) 
	,[pagdip] [DECIMAL](38, 4) 
	,[pawdip] [DECIMAL](38, 4) 
	,[pavapp] [DECIMAL](38, 4) 
	,[papreu] [NVARCHAR](2) 
	,[palpgv] [DECIMAL](38, 4) 
	,[patpu1] [NVARCHAR](1) 
	,[paslip] [NVARCHAR](1) 
	,[pavapw] [DECIMAL](38, 4) 
	,[pabum0] [NVARCHAR](2) 
	,[pavapv] [DECIMAL](38, 4) 
	,[pabum9] [NVARCHAR](2) 
	,[paliqw] [DECIMAL](38, 4) 
	,[pabum7] [NVARCHAR](2) 
	,[paliqv] [DECIMAL](38, 4) 
	,[pabum8] [NVARCHAR](2) 
	,[paovol] [DECIMAL](38, 4) 
	,[pabum2] [NVARCHAR](2) 
	,[pardtm] [DECIMAL](38, 4) 
	,[padte] [VARCHAR](20) 
	,[pametn] [NVARCHAR](10) 
	,[paopnr] [DECIMAL](38, 4) 
	,[papncr] [DECIMAL](38, 4) 
	,[pavehi] [NVARCHAR](12) 
	,[pavmcu] [NVARCHAR](12) 
	,[patrp] [DECIMAL](38, 4) 
	,[pacmpn] [DECIMAL](38, 4) 
	,[pabfwt] [DECIMAL](38, 4) 
	,[pabwtu] [NVARCHAR](2) 
	,[paafwt] [DECIMAL](38, 4) 
	,[paawtu] [NVARCHAR](2) 
	,[pathdt] [VARCHAR](20) 
	,[paopdt] [VARCHAR](20) 
	,[palrst] [DECIMAL](38, 4) 
	,[parecs] [NVARCHAR](1) 
	,[papgms] [NVARCHAR](1) 
	,[paglrn] [DECIMAL](38, 4) 
	,[paptnr] [DECIMAL](38, 4) 
	,[paurcd] [NVARCHAR](2) 
	,[paurat] [DECIMAL](38, 4) 
	,[paurab] [DECIMAL](38, 4) 
	,[paurrf] [NVARCHAR](15) 
	,[paurdt] [VARCHAR](20) 
	,[pauser] [NVARCHAR](10) 
	,[papid] [NVARCHAR](10) 
	,[pajobn] [NVARCHAR](10) 
	,[paupmj] [VARCHAR](20) 
	,[patday] [DECIMAL](38, 4) 
	,[paukid] [DECIMAL](38, 4) 
	,[pabpas] [NVARCHAR](1) 
	,[palotc] [NVARCHAR](3) 
)
WITH
(
    LOCATION='processing-clean/jde_qat/f41511/cdc/'
    ,DATA_SOURCE = [dw-landing-fs]
    ,FILE_FORMAT = [jde_fileformat_124_127_no_header]
)
