--Create ext table for cdc
IF OBJECT_ID('stg_jde_qat.ext_f4321_cdc') IS NOT NULL
    DROP EXTERNAL TABLE stg_jde_qat.ext_f4321_cdc


CREATE EXTERNAL TABLE stg_jde_qat.ext_f4321_cdc
(
	[sys_file_name] [NVARCHAR](100) 
	,[sys_file_ln] [VARCHAR](20) 
	,[sys_integration_id] [NVARCHAR](200) 
	,[sys_extract_dt] [NVARCHAR](40) 
	,[sys_cdc_dt] [NVARCHAR](40) 
	,[sys_cdc_scn] [NVARCHAR](14) 
	,[sys_cdc_operation_type] [NVARCHAR](15) 
	,[sys_cdc_before_after] [NVARCHAR](10) 
	,[sys_line_modified_ind] [VARCHAR](20) 
	,[pbkcoo] [NVARCHAR](5) 
	,[pbdoco] [DECIMAL](38, 4) 
	,[pbdcto] [NVARCHAR](2) 
	,[pbsfxo] [NVARCHAR](3) 
	,[pblnid] [DECIMAL](38, 4) 
	,[pbdlan] [NVARCHAR](12) 
	,[pbcdf1] [DECIMAL](38, 4) 
	,[pbcdf2] [DECIMAL](38, 4) 
	,[pbcdf3] [DECIMAL](38, 4) 
	,[pbcdf4] [DECIMAL](38, 4) 
	,[pbvsd] [DECIMAL](38, 4) 
	,[pbvsw] [DECIMAL](38, 4) 
	,[pbvsm] [DECIMAL](38, 4) 
	,[pbcrec] [DECIMAL](38, 4) 
	,[pbcfro] [DECIMAL](38, 4) 
	,[pbcfab] [DECIMAL](38, 4) 
	,[pbcraw] [DECIMAL](38, 4) 
	,[pbdrqj] [VARCHAR](20) 
	,[pbfrdj] [VARCHAR](20) 
	,[pblrdj] [VARCHAR](20) 
	,[pbdoc] [DECIMAL](38, 4) 
	,[pbdct] [NVARCHAR](2) 
	,[pbvrn] [NVARCHAR](8) 
	,[pbvsst] [NVARCHAR](2) 
	,[pbrjyn] [NVARCHAR](1) 
	,[pborfd] [NVARCHAR](1) 
	,[pblrcj] [VARCHAR](20) 
	,[pblrqt] [DECIMAL](38, 4) 
	,[pbuopn] [DECIMAL](38, 4) 
	,[pburec] [DECIMAL](38, 4) 
	,[pbvssp] [NVARCHAR](2) 
	,[pbshlt] [DECIMAL](38, 4) 
	,[pbshqt] [DECIMAL](38, 4) 
	,[pbupc] [DECIMAL](38, 4) 
	,[pburcd] [NVARCHAR](2) 
	,[pburdt] [VARCHAR](20) 
	,[pburat] [DECIMAL](38, 4) 
	,[pburab] [DECIMAL](38, 4) 
	,[pburrf] [NVARCHAR](15) 
	,[pbuser] [NVARCHAR](10) 
	,[pbpid] [NVARCHAR](10) 
	,[pbjobn] [NVARCHAR](10) 
	,[pbupmj] [VARCHAR](20) 
	,[pbtday] [DECIMAL](38, 4) 
	,[pbvlot] [DECIMAL](38, 4) 
	,[pbrcpd] [VARCHAR](20) 
	,[pbmxqt] [DECIMAL](38, 4) 
	,[pbmwdh] [NVARCHAR](1) 
	,[pbltlv] [DECIMAL](38, 4) 
	,[pbdcap] [DECIMAL](38, 4) 
	,[pbda08] [NVARCHAR](1) 
)
WITH
(
    LOCATION='processing-clean/jde_qat/f4321/cdc/'
    ,DATA_SOURCE = [dw-landing-fs]
    ,FILE_FORMAT = [jde_fileformat_124_127_no_header]
)
