--Create ext table for init
IF OBJECT_ID('stg_jde.ext_f4941_init') IS NOT NULL
    DROP EXTERNAL TABLE stg_jde.ext_f4941_init

CREATE EXTERNAL TABLE stg_jde.ext_f4941_init
(
	[sys_file_name] [NVARCHAR](100) 
	,[sys_file_ln] [VARCHAR](20) 
	,[sys_integration_id] [NVARCHAR](200) 
	,[sys_extract_dt] [NVARCHAR](40) 
	,[sys_cdc_dt] [NVARCHAR](40) 
	,[sys_cdc_scn] [NVARCHAR](14) 
	,[sys_cdc_operation_type] [NVARCHAR](15) 
	,[sys_cdc_before_after] [NVARCHAR](10) 
	,[sys_line_modified_ind] [VARCHAR](20) 
	,[rsshpn] [DECIMAL](38, 4) 
	,[rsrssn] [DECIMAL](38, 4) 
	,[rsmot] [NVARCHAR](3) 
	,[rsovrm] [NVARCHAR](1) 
	,[rscars] [DECIMAL](38, 4) 
	,[rsovrc] [NVARCHAR](1) 
	,[rsrout] [NVARCHAR](3) 
	,[rsrtn] [DECIMAL](38, 4) 
	,[rsdlno] [DECIMAL](38, 4) 
	,[rsfrsc] [NVARCHAR](8) 
	,[rsczon] [NVARCHAR](10) 
	,[rsvmcu] [NVARCHAR](12) 
	,[rsldnm] [DECIMAL](38, 4) 
	,[rstrpl] [DECIMAL](38, 4) 
	,[rsstsq] [DECIMAL](38, 4) 
	,[rsanid] [DECIMAL](38, 4) 
	,[rsorgn] [DECIMAL](38, 4) 
	,[rsancc] [DECIMAL](38, 4) 
	,[rswgts] [DECIMAL](38, 4) 
	,[rswtum] [NVARCHAR](2) 
	,[rsscvl] [DECIMAL](38, 4) 
	,[rsvlum] [NVARCHAR](2) 
	,[rslgts] [DECIMAL](38, 4) 
	,[rswths] [DECIMAL](38, 4) 
	,[rshgts] [DECIMAL](38, 4) 
	,[rsgths] [DECIMAL](38, 4) 
	,[rsluom] [NVARCHAR](2) 
	,[rsnpcs] [DECIMAL](38, 4) 
	,[rsnctr] [DECIMAL](38, 4) 
	,[rsccub] [DECIMAL](38, 4) 
	,[rsdstn] [DECIMAL](38, 4) 
	,[rsumd1] [NVARCHAR](2) 
	,[rsdsrc] [NVARCHAR](1) 
	,[rseltm] [DECIMAL](38, 4) 
	,[rsum] [NVARCHAR](2) 
	,[rsaexp] [DECIMAL](38, 4) 
	,[rsfea] [DECIMAL](38, 4) 
	,[rscrcd] [NVARCHAR](3) 
	,[rsecst] [DECIMAL](38, 4) 
	,[rsppdj] [VARCHAR](20) 
	,[rspmdt] [DECIMAL](38, 4) 
	,[rsrsdj] [VARCHAR](20) 
	,[rsrsdt] [DECIMAL](38, 4) 
	,[rslddt] [VARCHAR](20) 
	,[rsldtm] [DECIMAL](38, 4) 
	,[rsaddj] [VARCHAR](20) 
	,[rsadtm] [DECIMAL](38, 4) 
	,[rsdldt] [VARCHAR](20) 
	,[rsdltm] [DECIMAL](38, 4) 
	,[rsrrtr] [NVARCHAR](1) 
	,[rsratr] [NVARCHAR](1) 
	,[rsdpcr] [NVARCHAR](1) 
	,[rsrefq] [NVARCHAR](2) 
	,[rsrefn] [NVARCHAR](30) 
	,[rsfrtd] [NVARCHAR](1) 
	,[rsfrtv] [NVARCHAR](1) 
	,[rsfrvc] [DECIMAL](38, 4) 
	,[rsfrvf] [DECIMAL](38, 4) 
	,[rscrcp] [NVARCHAR](3) 
	,[rsfrcc] [DECIMAL](38, 4) 
	,[rsfrcf] [DECIMAL](38, 4) 
	,[rscrdc] [NVARCHAR](3) 
	,[rsintf] [NVARCHAR](1) 
	,[rsibrs] [NVARCHAR](1) 
	,[rslslt] [DECIMAL](38, 4) 
	,[rslsut] [DECIMAL](38, 4) 
	,[rslalt] [DECIMAL](38, 4) 
	,[rslaut] [DECIMAL](38, 4) 
	,[rstpuf] [DECIMAL](38, 4) 
	,[rstput] [DECIMAL](38, 4) 
	,[rstdlf] [DECIMAL](38, 4) 
	,[rstdlt] [DECIMAL](38, 4) 
	,[rsdepu] [VARCHAR](20) 
	,[rsdlpu] [VARCHAR](20) 
	,[rsdedl] [VARCHAR](20) 
	,[rsdldl] [VARCHAR](20) 
	,[rsdkid] [NVARCHAR](20) 
	,[rsprnb] [DECIMAL](38, 4) 
	,[rsprte] [NVARCHAR](1) 
	,[rslnmb] [DECIMAL](38, 4) 
	,[rscnmr] [NVARCHAR](24) 
	,[rsurcd] [NVARCHAR](2) 
	,[rsurdt] [VARCHAR](20) 
	,[rsurat] [DECIMAL](38, 4) 
	,[rsurab] [DECIMAL](38, 4) 
	,[rsurrf] [NVARCHAR](15) 
	,[rsuser] [NVARCHAR](10) 
	,[rspid] [NVARCHAR](10) 
	,[rsjobn] [NVARCHAR](10) 
	,[rsupmj] [VARCHAR](20) 
	,[rstday] [DECIMAL](38, 4) 
)
WITH
(
    LOCATION='processing-clean/jde/f4941/init/'
    ,DATA_SOURCE = [dw-landing-fs]
    ,FILE_FORMAT = [jde_fileformat_124_127_no_header]
)
