--Create ext table for init
IF OBJECT_ID('stg_jde.ext_f4981_init') IS NOT NULL
    DROP EXTERNAL TABLE stg_jde.ext_f4981_init

CREATE EXTERNAL TABLE stg_jde.ext_f4981_init
(
	[sys_file_name] [NVARCHAR](100) 
	,[sys_file_ln] [VARCHAR](20) 
	,[sys_integration_id] [NVARCHAR](200) 
	,[sys_extract_dt] [NVARCHAR](40) 
	,[sys_cdc_dt] [NVARCHAR](40) 
	,[sys_cdc_scn] [NVARCHAR](14) 
	,[sys_cdc_operation_type] [NVARCHAR](15) 
	,[sys_cdc_before_after] [NVARCHAR](10) 
	,[sys_line_modified_ind] [VARCHAR](20) 
	,[fhuk01] [DECIMAL](38, 4) 
	,[fhshpn] [DECIMAL](38, 4) 
	,[fhrssn] [DECIMAL](38, 4) 
	,[fhvmcu] [NVARCHAR](12) 
	,[fhldnm] [DECIMAL](38, 4) 
	,[fhdlno] [DECIMAL](38, 4) 
	,[fhoseq] [DECIMAL](38, 4) 
	,[fhnmfc] [NVARCHAR](4) 
	,[fhdsgp] [NVARCHAR](3) 
	,[fhfrt1] [NVARCHAR](6) 
	,[fhfrt2] [NVARCHAR](6) 
	,[fhorgn] [DECIMAL](38, 4) 
	,[fhnmcu] [NVARCHAR](12) 
	,[fhblpb] [NVARCHAR](1) 
	,[fhovfg] [NVARCHAR](1) 
	,[fhovfh] [NVARCHAR](1) 
	,[fhmot] [NVARCHAR](3) 
	,[fhcars] [DECIMAL](38, 4) 
	,[fhcamd] [NVARCHAR](1) 
	,[fhwgts] [DECIMAL](38, 4) 
	,[fhwtum] [NVARCHAR](2) 
	,[fhscvl] [DECIMAL](38, 4) 
	,[fhvlum] [NVARCHAR](2) 
	,[fhfrsc] [NVARCHAR](8) 
	,[fhrtnm] [NVARCHAR](10) 
	,[fhsdsq] [DECIMAL](38, 4) 
	,[fhscsn] [DECIMAL](38, 4) 
	,[fhrtgb] [NVARCHAR](1) 
	,[fhrtdq] [DECIMAL](38, 4) 
	,[fhuom] [NVARCHAR](2) 
	,[fhcgc1] [NVARCHAR](3) 
	,[fhag] [DECIMAL](38, 4) 
	,[fhfaa] [DECIMAL](38, 4) 
	,[fhnamt] [DECIMAL](38, 4) 
	,[fhcrdc] [NVARCHAR](3) 
	,[fhnamf] [DECIMAL](38, 4) 
	,[fhcrcd] [NVARCHAR](3) 
	,[fhdoco] [DECIMAL](38, 4) 
	,[fhdcto] [NVARCHAR](2) 
	,[fhkcoo] [NVARCHAR](5) 
	,[fhlnid] [DECIMAL](38, 4) 
	,[fhodoc] [DECIMAL](38, 4) 
	,[fhodct] [NVARCHAR](2) 
	,[fhokco] [NVARCHAR](5) 
	,[fhjeln] [DECIMAL](38, 4) 
	,[fhdoc] [DECIMAL](38, 4) 
	,[fhdct] [NVARCHAR](2) 
	,[fhkco] [NVARCHAR](5) 
	,[fhdgj] [VARCHAR](20) 
	,[fhvinv] [NVARCHAR](25) 
	,[fhrefq] [NVARCHAR](2) 
	,[fhrefn] [NVARCHAR](30) 
	,[fhshan] [DECIMAL](38, 4) 
	,[fhcty1] [NVARCHAR](25) 
	,[fhadds] [NVARCHAR](3) 
	,[fhaddz] [NVARCHAR](12) 
	,[fhzon] [NVARCHAR](3) 
	,[fhczon] [NVARCHAR](10) 
	,[fhfrth] [NVARCHAR](3) 
	,[fhrtn] [DECIMAL](38, 4) 
	,[fhaddj] [VARCHAR](20) 
	,[fhukid] [DECIMAL](38, 4) 
	,[fhurcd] [NVARCHAR](2) 
	,[fhurdt] [VARCHAR](20) 
	,[fhurat] [DECIMAL](38, 4) 
	,[fhurab] [DECIMAL](38, 4) 
	,[fhurrf] [NVARCHAR](15) 
	,[fhuser] [NVARCHAR](10) 
	,[fhpid] [NVARCHAR](10) 
	,[fhjobn] [NVARCHAR](10) 
	,[fhupmj] [VARCHAR](20) 
	,[fhtday] [DECIMAL](38, 4) 
	,[fhfrsn] [NVARCHAR](3) 
	,[fhani] [NVARCHAR](29) 
	,[fhtxa1] [NVARCHAR](10) 
	,[fhexr1] [NVARCHAR](2) 
	,[fhctyo] [NVARCHAR](25) 
	,[fhadso] [NVARCHAR](3) 
	,[fhadzo] [NVARCHAR](12) 
	,[fhctro] [NVARCHAR](3) 
	,[fhsct1] [NVARCHAR](3) 
	,[fhsct2] [NVARCHAR](3) 
	,[fhsct3] [NVARCHAR](3) 
	,[fhsc1o] [NVARCHAR](3) 
	,[fhsc2o] [NVARCHAR](3) 
	,[fhsc3o] [NVARCHAR](3) 
	,[fhlnmb] [DECIMAL](38, 4) 
	,[fhcnmr] [NVARCHAR](24) 
	,[fhstam] [DECIMAL](38, 4) 
	,[fhctam] [DECIMAL](38, 4) 
	,[fhtx] [NVARCHAR](1) 
	,[fhovrtax] [NVARCHAR](1) 
	,[fhatxa] [DECIMAL](38, 4) 
	,[fhctxa] [DECIMAL](38, 4) 
)
WITH
(
    LOCATION='processing-clean/jde/f4981/init/'
    ,DATA_SOURCE = [dw-landing-fs]
    ,FILE_FORMAT = [jde_fileformat_124_127_no_header]
)
