-- Apply updates from upsert table onto rep new table
UPDATE rep_jde_qat.f41022_new
SET
	[sys_file_name] = cdc.[sys_file_name]
	,[sys_file_ln] = cdc.[sys_file_ln]
	,[sys_extract_dt] = cdc.[sys_extract_dt]
	,[sys_cdc_dt] = cdc.[sys_cdc_dt]
	,[sys_cdc_scn] = cdc.[sys_cdc_scn]
	,[sys_cdc_operation_type] = cdc.[sys_cdc_operation_type]
	,[sys_cdc_before_after] = cdc.[sys_cdc_before_after]
	,[sys_line_modified_ind] = cdc.[sys_line_modified_ind]
	,[pnmcu] = cdc.[pnmcu]
	,[pnmcu_conv] = cdc.[pnmcu_conv]
	,[pnitm] = cdc.[pnitm]
	,[pnstvl] = cdc.[pnstvl]
	,[pnstvl_conv] = cdc.[pnstvl_conv]
	,[pnbum0] = cdc.[pnbum0]
	,[pnlrfg] = cdc.[pnlrfg]
	,[pnlrfg_conv] = cdc.[pnlrfg_conv]
	,[pnhcor] = cdc.[pnhcor]
	,[pnhcor_conv] = cdc.[pnhcor_conv]
	,[pnacor] = cdc.[pnacor]
	,[pnacor_conv] = cdc.[pnacor_conv]
	,[pnabbl] = cdc.[pnabbl]
	,[pnabbl_conv] = cdc.[pnabbl_conv]
	,[pnatwh] = cdc.[pnatwh]
	,[pnatwh_conv] = cdc.[pnatwh_conv]
	,[pnrplt] = cdc.[pnrplt]
	,[pnbcat] = cdc.[pnbcat]
	,[pnfcat] = cdc.[pnfcat]
	,[pnrecd] = cdc.[pnrecd]
	,[pnrecd_conv] = cdc.[pnrecd_conv]
	,[pnurcd] = cdc.[pnurcd]
	,[pnurcd_conv] = cdc.[pnurcd_conv]
	,[pnurat] = cdc.[pnurat]
	,[pnurat_conv] = cdc.[pnurat_conv]
	,[pnurab] = cdc.[pnurab]
	,[pnurab_conv] = cdc.[pnurab_conv]
	,[pnurrf] = cdc.[pnurrf]
	,[pnurrf_conv] = cdc.[pnurrf_conv]
	,[pnurdt] = cdc.[pnurdt]
	,[pnurdt_conv] = cdc.[pnurdt_conv]
	,[pnuser] = cdc.[pnuser]
	,[pnuser_conv] = cdc.[pnuser_conv]
	,[pnpid] = cdc.[pnpid]
	,[pnpid_conv] = cdc.[pnpid_conv]
	,[pnjobn] = cdc.[pnjobn]
	,[pnjobn_conv] = cdc.[pnjobn_conv]
	,[pnupmj] = cdc.[pnupmj]
	,[pnupmj_conv] = cdc.[pnupmj_conv]
	,[pntday] = cdc.[pntday]
	,[pnrtob] = cdc.[pnrtob] -- exclude distribution column
FROM stg_jde_qat.tmp_upsert_f41022_cdc cdc
WHERE
    rep_jde_qat.f41022_new.sys_integration_id = cdc.sys_integration_id
    AND rep_jde_qat.f41022_new.sys_cdc_scn < cdc.sys_cdc_scn 
OPTION ( LABEL = 'UPDATE_rep_jde_qat.f41022_new AF:{{ task_instance_key_str }}' ) 
